import {z} from 'zod';
import {slaDeadlines,planAutomation,automationEffects} from './automation';
import {Operations} from './operations';
import {HttpError} from './service';
import {permissions,roles,priorities,type Capability} from '../domain';
const id=z.string().min(1).max(150),name=z.string().trim().min(1).max(120),version=z.number().int().nonnegative();
const capabilities=z.array(z.enum(permissions.Owner as [Capability,...Capability[]])).max(10);
export function parseCSV(text:string){
 const rows:string[][]=[];let row:string[]=[],field='',quoted=false,ended=false;
 text=text.replace(/^\uFEFF/,'');
 for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'){if(text[i+1]==='"'){field+='"';i++}else{quoted=false;ended=true}}else field+=c;continue}
 if(c==='"'){if(field||ended)throw new HttpError(400,'Invalid CSV quotation.');quoted=true}else if(c===','||c==='\n'||c==='\r'){row.push(field.trim());field='';ended=false;if(c!==','){if(row.some(Boolean))rows.push(row);row=[];if(c==='\r'&&text[i+1]==='\n')i++}}else{if(ended&&!/\s/.test(c))throw new HttpError(400,'Unexpected text after a quoted CSV value.');if(!ended)field+=c}}
 if(quoted)throw new HttpError(400,'Unclosed quoted CSV value.');row.push(field.trim());if(row.some(Boolean))rows.push(row);
 if(rows.length<2||rows.length>501)throw new HttpError(400,'Include a header and between 1 and 500 records.');
 const headers=rows.shift()!.map(x=>x.toLowerCase().replace(/[ _-]/g,''));if(new Set(headers).size!==headers.length||headers.some(x=>!x))throw new HttpError(400,'CSV headers must be nonempty and unique.');
 return rows.map((r,i)=>{if(r.length!==headers.length)throw new HttpError(400,`Row ${i+2} has ${r.length} columns; expected ${headers.length}.`);return Object.fromEntries(headers.map((h,j)=>[h,r[j]]))});
}
const metadataInput=z.object({type:z.string().max(80).default(''),subtype:z.string().max(80).default(''),tags:z.string().max(500).default(''),due:z.union([z.literal(''),z.string().datetime()]).default(''),estimatedHours:z.number().min(0).max(100000).default(0),agreement:z.string().max(200).default(''),resources:z.array(id).max(30).default([]),customFields:z.record(z.string().max(80),z.string().max(2000)).refine(x=>Object.keys(x).length<=30).default({}),version:version.default(0)}).strict();
const configBase={name,version:version.optional()};
const configSchemas={
 'saved-view':z.object({...configBase,query:z.string().max(200),priority:z.string().max(30),sort:z.string().max(30),view:z.enum(['all','open','mine','unassigned','critical','waiting']),board:z.string().max(150),company:z.string().max(150),layout:z.enum(['table','compact','kanban'])}).strict(),
 recurring:z.object({...configBase,title:z.string().trim().min(1).max(180),description:z.string().max(10000).default(''),companyId:id,boardId:id,assigneeId:id.nullable().default(null),priority:z.enum(priorities),intervalDays:z.number().int().min(1).max(366),nextDue:z.string().datetime(),enabled:z.boolean()}).strict(),
 'project-template':z.object({...configBase,tasks:z.string().min(1).max(10000)}).strict(),
 'reply-template':z.object({...configBase,body:z.string().min(1).max(10000)}).strict(),
 'ticket-fields':z.object({...configBase,types:z.string().max(2000),subtypes:z.string().max(2000),fields:z.string().max(2000)}).strict(),
 agreement:z.object({...configBase,companyId:id,start:z.string().max(10),end:z.string().max(10),monthlyFee:z.number().min(0).max(100000000),includedHours:z.number().min(0).max(100000),hourlyRate:z.number().min(0).max(100000),notes:z.string().max(10000)}).strict(),
 'business-hours':z.object({...configBase,enabled:z.boolean(),startHour:z.number().int().min(0).max(23),endHour:z.number().int().min(1).max(24),weekdays:z.array(z.number().int().min(0).max(6)).min(1).max(7),holidays:z.string().max(5000)}).strict().refine(v=>v.endHour>v.startHour,'Closing time must follow opening time'),
};
export class Advanced extends Operations {
 async runRecurring(org:string){await this.context(org,'automation:write');const templates=await this.configs(org,'recurring');let created=0;for(const row of templates.records.slice(0,100)){const p=configSchemas.recurring.parse(Object.fromEntries(Object.entries(row).filter(([k])=>k!=='id')));if(!p.enabled||Date.parse(p.nextDue)>Date.now())continue;const initial=await this.references(org,{...p,contactId:null}),plan=await planAutomation(this,org,['Ticket created'],{title:p.title,description:p.description,companyId:p.companyId,boardId:p.boardId,assigneeId:p.assigneeId,contactId:null,priority:p.priority,status:initial.name}),v=plan.values as {title:string;description:string;companyId:string;boardId:string;assigneeId:string|null;contactId:null;priority:string;status:string},status=await this.references(org,v),at=new Date().toISOString(),sla=await slaDeadlines(this,org,v.priority,at,v.boardId),next={...p,nextDue:new Date(Date.parse(p.nextDue)+(Math.floor((Date.now()-Date.parse(p.nextDue))/(p.intervalDays*86400000))+1)*p.intervalDays*86400000).toISOString()},marker=crypto.randomUUID(),guard='EXISTS(SELECT 1 FROM audit_events WHERE id=?)';
 const r=await this.db.batch([this.stmt("INSERT INTO audit_events(id,org_id,entity_id,action,author_id,at) SELECT ?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM configurations WHERE org_id=? AND id=? AND version=?) AND NOT EXISTS(SELECT 1 FROM recurring_runs WHERE org_id=? AND config_id=? AND due=?)",marker,org,'recurring:'+row.id,'Recurring ticket generated',this.user.id,at,org,row.id,row.version,org,row.id,p.nextDue),this.stmt(`INSERT INTO tickets(org_id,id,title,description,company_id,board_id,assignee_id,status,closed,priority,created,updated,response_due,resolution_due,resolved) SELECT ?,COALESCE(MAX(id),1000)+1,?,?,?,?,?,?,?,?,?,?,?,?,? FROM tickets WHERE org_id=? HAVING ${guard}`,org,v.title,v.description,v.companyId,v.boardId,v.assigneeId,status.name,Number(status.closed),v.priority,at,at,sla.responseDue,sla.resolutionDue,status.closed?at:null,org,marker),this.stmt(`INSERT INTO recurring_runs(org_id,config_id,due,ticket_id) SELECT ?,?,?,MAX(id) FROM tickets WHERE org_id=? HAVING ${guard}`,org,row.id,p.nextDue,org,marker),this.stmt(`UPDATE configurations SET data=?,version=version+1 WHERE org_id=? AND id=? AND ${guard}`,JSON.stringify(next),org,row.id,marker),...(plan.note?[this.stmt(`INSERT INTO ticket_notes(id,org_id,ticket_id,author_id,body,at) SELECT ?,?,MAX(id),?,?,? FROM tickets WHERE org_id=? HAVING ${guard}`,crypto.randomUUID(),org,this.user.id,plan.note,at,org,marker)]:[]),...await automationEffects(this,org,'new',plan.effects,marker,v)]);created+=r[0].meta.changes?1:0;}return {created};}
 async applyProjectTemplate(org:string,payload:unknown){await this.context(org,'projects:write');const p=z.object({templateId:id,projectId:id,version:z.number().int().positive()}).strict().parse(payload),project=await this.project(org,p.projectId),template=await this.one<{data:string}>("SELECT data FROM configurations WHERE org_id=? AND id=? AND kind='project-template'",org,p.templateId);if(!template)throw new HttpError(404,'Template not found.');const tasks=String(JSON.parse(template.data).tasks).split('\n').map(t=>t.trim()).filter(Boolean);if(tasks.length>100||tasks.some(t=>t.length>180))throw new HttpError(400,'Use at most 100 tasks, each up to 180 characters.');const marker=crypto.randomUUID(),r=await this.db.batch([this.stmt('INSERT INTO audit_events(id,org_id,entity_id,action,author_id,at) SELECT ?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM projects WHERE org_id=? AND id=? AND version=?)',marker,org,'project:'+p.projectId,'Project template applied',this.user.id,new Date().toISOString(),org,p.projectId,p.version),...tasks.map(t=>this.stmt('INSERT INTO project_tasks(org_id,id,project_id,title) SELECT ?,?,?,? WHERE EXISTS(SELECT 1 FROM audit_events WHERE id=?)',org,crypto.randomUUID(),p.projectId,t,marker)),this.stmt('UPDATE projects SET version=version+1 WHERE org_id=? AND id=? AND EXISTS(SELECT 1 FROM audit_events WHERE id=?)',org,p.projectId,marker)]);if(!r[0].meta.changes)throw new HttpError(409,'Project changed. Reload before applying.');return {created:tasks.length};}
 async dependencies(org:string,projectId:string){await this.project(org,projectId);return {dependencies:await this.rows('SELECT d.task_id taskId,d.dependency_id dependencyId FROM task_dependencies d JOIN project_tasks t ON t.org_id=d.org_id AND t.id=d.task_id WHERE t.org_id=? AND t.project_id=?',org,projectId)};}
 async dependencySave(org:string,payload:unknown){await this.context(org,'projects:write');const p=z.object({taskId:id,dependencyId:id,remove:z.boolean().default(false)}).strict().parse(payload),task=await this.one<{project_id:string;done:number}>('SELECT project_id,done FROM project_tasks WHERE org_id=? AND id=?',org,p.taskId),dependency=await this.one<{project_id:string;done:number}>('SELECT project_id,done FROM project_tasks WHERE org_id=? AND id=?',org,p.dependencyId);if(!task||!dependency||task.project_id!==dependency.project_id)throw new HttpError(400,'Choose tasks in the same project.');if(!p.remove&&task.done&&!dependency.done)throw new HttpError(409,'Reopen the completed task before adding an incomplete prerequisite.');await this.db.batch([p.remove?this.stmt('DELETE FROM task_dependencies WHERE org_id=? AND task_id=? AND dependency_id=?',org,p.taskId,p.dependencyId):this.stmt('INSERT INTO task_dependencies(org_id,task_id,dependency_id) VALUES(?,?,?) ON CONFLICT DO NOTHING',org,p.taskId,p.dependencyId),this.log(org,'project:'+task.project_id,p.remove?'Task dependency removed':'Task dependency added',null,p)]);return {ok:true};}
 async companyProfile(org:string,cid:string){await this.context(org);await this.company(org,cid);return {company:await this.one('SELECT * FROM companies WHERE org_id=? AND id=?',org,cid),tickets:await this.rows('SELECT id,title,status,priority,closed FROM tickets WHERE org_id=? AND company_id=? ORDER BY updated DESC LIMIT 30',org,cid),contacts:await this.rows('SELECT id,name,email,phone,title FROM contacts WHERE org_id=? AND company_id=? ORDER BY name',org,cid),projects:await this.rows('SELECT id,name,status,due FROM projects WHERE org_id=? AND company_id=? ORDER BY name',org,cid),assets:await this.rows('SELECT id,name,kind,serial,status FROM assets WHERE org_id=? AND company_id=? ORDER BY name',org,cid),time:await this.one('SELECT COALESCE(SUM(e.minutes),0) minutes,COALESCE(SUM(CASE WHEN e.billable=1 THEN e.minutes ELSE 0 END),0) billableMinutes FROM time_entries e JOIN tickets t ON t.org_id=e.org_id AND t.id=e.ticket_id WHERE t.org_id=? AND t.company_id=?',org,cid),activity:await this.rows("SELECT a.id,a.action,a.at,u.name author FROM audit_events a JOIN users u ON u.id=a.author_id WHERE a.org_id=? AND (a.entity_id=? OR a.entity_id IN (SELECT 'ticket:'||id FROM tickets WHERE org_id=? AND company_id=?)) ORDER BY a.at DESC LIMIT 30",org,'companies:'+cid,org,cid),agreements:(await this.configs(org,'agreement')).records.filter(r=>r.companyId===cid)};}
 async customRoles(org:string){await this.context(org,'team:write');return {roles:(await this.rows<{id:string;name:string;capabilities:string;version:number}>('SELECT * FROM custom_roles WHERE org_id=? ORDER BY name',org)).map(r=>({...r,capabilities:JSON.parse(r.capabilities)})),assignments:await this.rows('SELECT user_id userId,role_id roleId FROM role_assignments WHERE org_id=?',org)};}
 async customRoleSave(org:string,payload:unknown){const actor=await this.context(org,'team:write');if(!['Owner','Administrator'].includes(actor.role))throw new HttpError(403,'Only an owner or administrator can manage role definitions.');const p=z.object({id:id.optional(),name,capabilities,version:version.optional()}).strict().parse(payload);if(roles.some(r=>r.toLowerCase()===p.name.toLowerCase()))throw new HttpError(400,'Choose a name distinct from built-in roles.');if(p.capabilities.some(c=>c==='organization:write'||c==='team:write'))throw new HttpError(400,'Organization and team administration are reserved for built-in administrators.');const rid=p.id??crypto.randomUUID(),json=JSON.stringify([...new Set(p.capabilities)]);const results=await this.db.batch([p.id?this.stmt('UPDATE custom_roles SET name=?,capabilities=?,version=version+1 WHERE org_id=? AND id=? AND version=?',p.name,json,org,rid,p.version??0):this.stmt('INSERT INTO custom_roles(org_id,id,name,capabilities) VALUES(?,?,?,?)',org,rid,p.name,json),this.log(org,'role:'+rid,'Custom role saved',null,p,true)]);if(!results[0].meta.changes)throw new HttpError(409,'Role changed. Reload before saving.');return {id:rid};}
 async customRoleAssign(org:string,payload:unknown){const actor=await this.context(org,'team:write');if(!['Owner','Administrator'].includes(actor.role))throw new HttpError(403,'Only an administrator can assign custom roles.');const p=z.object({userId:id,roleId:id.nullable()}).strict().parse(payload),target=await this.one<{role:string}>('SELECT role FROM memberships WHERE org_id=? AND user_id=?',org,p.userId);if(!target)throw new HttpError(404,'Member not found.');if(['Owner','Administrator'].includes(target.role)||p.userId===this.user.id)throw new HttpError(403,'Choose a non-administrator member other than yourself.');if(p.roleId&&!await this.one('SELECT id FROM custom_roles WHERE org_id=? AND id=?',org,p.roleId))throw new HttpError(400,'Choose a role in this organization.');await this.db.batch([p.roleId?this.stmt('INSERT INTO role_assignments(org_id,user_id,role_id) VALUES(?,?,?) ON CONFLICT(org_id,user_id) DO UPDATE SET role_id=excluded.role_id',org,p.userId,p.roleId):this.stmt('DELETE FROM role_assignments WHERE org_id=? AND user_id=?',org,p.userId),this.log(org,'member:'+p.userId,'Custom role assignment changed',null,p)]);return {ok:true};}
 async relations(org:string,n:number){await this.ticket(org,n);return {relations:await this.rows("SELECT r.ticket_id ticketId,r.target_id targetId,r.kind,t.title,t.closed FROM ticket_relations r JOIN tickets t ON t.org_id=r.org_id AND t.id=CASE WHEN r.ticket_id=? THEN r.target_id ELSE r.ticket_id END WHERE r.org_id=? AND (r.ticket_id=? OR r.target_id=?)",n,org,n,n)};}
 async relationSave(org:string,n:number,payload:unknown){await this.context(org,'tickets:write');const p=z.object({kind:z.enum(['parent','merge']),targetId:z.number().int().positive().nullable(),version:z.number().int().positive(),targetVersion:z.number().int().positive().optional()}).strict().parse(payload),source=await this.ticket(org,n);if(source.version!==p.version)throw new HttpError(409,'Ticket changed. Reload it first.');if(await this.one("SELECT ticket_id FROM ticket_relations WHERE org_id=? AND ticket_id=? AND kind='merge'",org,n))throw new HttpError(409,'This ticket is already merged.');if(p.kind==='merge'&&!p.targetId)throw new HttpError(400,'Choose a destination.');if(p.targetId===n)throw new HttpError(400,'A ticket cannot relate to itself.');
 const target=p.targetId?await this.ticket(org,p.targetId):null;if(target&&target.companyId!==source.companyId)throw new HttpError(400,'Related tickets must belong to the same company.');if(target&&await this.one("SELECT ticket_id FROM ticket_relations WHERE org_id=? AND ticket_id=? AND kind='merge'",org,target.id))throw new HttpError(409,'Choose an unmerged destination.');
 if(target&&await this.one("WITH RECURSIVE ancestors(id) AS (SELECT target_id FROM ticket_relations WHERE org_id=? AND ticket_id=? UNION SELECT r.target_id FROM ticket_relations r JOIN ancestors a ON r.ticket_id=a.id WHERE r.org_id=?) SELECT id FROM ancestors WHERE id=?",org,target.id,org,n))throw new HttpError(400,'This relationship would create a cycle.');
 if(p.kind==='merge'&&target){if(target.closed)throw new HttpError(400,'Reopen the destination before merging.');if(target.version!==p.targetVersion)throw new HttpError(409,'Destination changed. Preview it again.');if(await this.one('SELECT ticket_id FROM ticket_relations WHERE org_id=? AND (ticket_id=? OR target_id=?)',org,n,n))throw new HttpError(409,'Remove parent/child relationships before merging this ticket.');}
 const marker=crypto.randomUUID(),at=new Date().toISOString(),guard='EXISTS(SELECT 1 FROM audit_events WHERE id=?)';
 const statements=[this.stmt(`INSERT INTO audit_events(id,org_id,entity_id,action,author_id,after,at) SELECT ?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM tickets WHERE org_id=? AND id=? AND version=?) ${target?'AND EXISTS(SELECT 1 FROM tickets WHERE org_id=? AND id=? AND version=?)':''}`,marker,org,'ticket:'+n,p.kind==='merge'?'Ticket merged':'Parent ticket changed',this.user.id,JSON.stringify(p),at,org,n,p.version,...(target?[org,target.id,target.version]:[]))];
 if(p.kind==='merge'&&target){const board=await this.one<{statuses:string}>('SELECT statuses FROM boards WHERE org_id=? AND id=?',org,source.boardId);const status=JSON.parse(board!.statuses).find((s:{closed:boolean})=>s.closed).name;
 statements.push(this.stmt(`UPDATE tickets SET closed=1,status=?,resolved=?,updated=?,version=version+1 WHERE org_id=? AND id=? AND ${guard}`,status,at,at,org,n,marker),this.stmt(`UPDATE tickets SET updated=?,version=version+1 WHERE org_id=? AND id=? AND ${guard}`,at,org,target.id,marker));
 // Keep original ticket and audit history; consolidate mutable work and conversations.
 for(const table of ['ticket_notes','public_messages','attachments','time_entries','scheduled_work','running_timers'])statements.push(this.stmt(`UPDATE ${table} SET ticket_id=? WHERE org_id=? AND ticket_id=? AND ${guard}`,target.id,org,n,marker));
 statements.push(this.stmt(`INSERT INTO ticket_notes(id,org_id,ticket_id,author_id,body,at) SELECT ?,?,?,?,?,? WHERE ${guard}`,crypto.randomUUID(),org,target.id,this.user.id,`Merged #${n}: ${source.title}\n\n${source.description}\n\nOriginal audit history and project/asset links remain on #${n}.`,at,marker));
 }
 if(target)statements.push(this.stmt(`INSERT INTO ticket_relations(org_id,ticket_id,target_id,kind) SELECT ?,?,?,? WHERE ${guard} ON CONFLICT(org_id,ticket_id,kind) DO UPDATE SET target_id=excluded.target_id`,org,n,target.id,p.kind,marker));else statements.push(this.stmt(`DELETE FROM ticket_relations WHERE org_id=? AND ticket_id=? AND kind=? AND ${guard}`,org,n,p.kind,marker));
 if(p.kind==='parent')statements.push(this.stmt(`UPDATE tickets SET version=version+1,updated=? WHERE org_id=? AND id=? AND ${guard}`,at,org,n,marker));
 const result=await this.db.batch(statements);if(!result[0].meta.changes)throw new HttpError(409,'A ticket changed. Reload and try again.');return {ok:true,targetId:target?.id};
 }
 async metadata(org:string,n:number){await this.ticket(org,n);const row=await this.one<{data:string;version:number}>('SELECT data,version FROM ticket_metadata WHERE org_id=? AND ticket_id=?',org,n);return row?{...JSON.parse(row.data),version:row.version}:metadataInput.parse({});}
 async metadataSave(org:string,n:number,payload:unknown){await this.context(org,'tickets:write');await this.ticket(org,n);await this.writableTicket(org,n);const {version:v,...p}=metadataInput.parse(payload);for(const m of p.resources)await this.member(org,m);const r=await this.db.batch([v?this.stmt('UPDATE ticket_metadata SET data=?,version=version+1 WHERE org_id=? AND ticket_id=? AND version=?',JSON.stringify(p),org,n,v):this.stmt('INSERT INTO ticket_metadata(org_id,ticket_id,data) VALUES(?,?,?)',org,n,JSON.stringify(p)),this.log(org,'ticket:'+n,'Ticket details saved',null,p,true)]);if(!r[0].meta.changes)throw new HttpError(409,'Details changed. Reload first.');return {ok:true};}
 async configs(org:string,kind:string){await this.context(org);if(!Object.hasOwn(configSchemas,kind))throw new HttpError(404,'Configuration not found.');return {records:(await this.rows<{id:string;data:string;name:string;version:number}>('SELECT id,name,data,version FROM configurations WHERE org_id=? AND kind=? ORDER BY name',org,kind)).map(r=>({id:r.id,...JSON.parse(r.data),name:r.name,version:r.version}))};}
 async configSave(org:string,kind:string,payload:unknown,rid?:string){await this.context(org,kind==='recurring'?'automation:write':kind==='project-template'?'projects:write':['reply-template','saved-view'].includes(kind)?'tickets:write':'organization:write');if(!Object.hasOwn(configSchemas,kind))throw new HttpError(404,'Configuration not found.');const p=configSchemas[kind as keyof typeof configSchemas].parse(payload);if(kind==='business-hours'&&!rid&&await this.one("SELECT id FROM configurations WHERE org_id=? AND kind='business-hours'",org))throw new HttpError(409,'Edit the existing business calendar.');if('companyId' in p)await this.company(org,p.companyId);if(kind==='recurring'){const r=configSchemas.recurring.parse(p);await this.references(org,{...r,contactId:null});}const n=rid??crypto.randomUUID(),r=await this.db.batch([rid?this.stmt('UPDATE configurations SET name=?,data=?,version=version+1 WHERE org_id=? AND id=? AND kind=? AND version=?',p.name,JSON.stringify(p),org,n,kind,p.version??0):this.stmt('INSERT INTO configurations(org_id,id,kind,name,data) VALUES(?,?,?,?,?)',org,n,kind,p.name,JSON.stringify(p)),this.log(org,kind+':'+n,'Configuration saved',null,p,true)]);if(!r[0].meta.changes)throw new HttpError(409,'Record changed. Reload before saving.');return {id:n};}
 async configDelete(org:string,kind:string,rid:string){await this.context(org,kind==='recurring'?'automation:write':kind==='project-template'?'projects:write':['reply-template','saved-view'].includes(kind)?'tickets:write':'organization:write');if(kind==='recurring')throw new HttpError(400,'Disable recurring templates to preserve run history.');await this.db.batch([this.stmt('DELETE FROM configurations WHERE org_id=? AND id=? AND kind=?',org,rid,kind),this.log(org,kind+':'+rid,'Configuration deleted',null,null,true)]);return {ok:true};}
 async importCSV(org:string,payload:unknown){const p=z.object({kind:z.enum(['companies','contacts','assets','users']),csv:z.string().max(500000),apply:z.boolean().default(false)}).strict().parse(payload);await this.context(org,p.kind==='users'?'team:write':p.kind==='assets'?'assets:write':'directory:write');const records=parseCSV(p.csv),companies=await this.rows<{id:string;name:string}>('SELECT id,name FROM companies WHERE org_id=?',org),existing=await this.rows<Record<string,string>>(p.kind==='users'?'SELECT email FROM invitations WHERE org_id=?':`SELECT * FROM ${p.kind} WHERE org_id=?`,org),seen=new Set<string>(),errors:string[]=[],preview:Record<string,unknown>[]=[],statements:D1PreparedStatement[]=[];let skipped=0;
 const email=z.union([z.literal(''),z.string().email().max(254)]),field=(r:Record<string,string>,key:string,max=1000)=>z.string().max(max).parse(r[key]??'');
 for(let i=0;i<records.length;i++){const r=records[i];try{const n=name.parse(r.name??(p.kind==='users'?r.email:undefined)),e=email.parse((r.email??'').toLowerCase()),company=p.kind==='contacts'||p.kind==='assets'?companies.filter(c=>c.name.toLowerCase()===(r.company??'').toLowerCase()):[];if(['contacts','assets'].includes(p.kind)&&company.length!==1)throw new Error('Company must uniquely match an existing company name.');const cid=company[0]?.id??'',key=p.kind==='companies'?n.toLowerCase():p.kind==='users'?e:cid+'|'+n.toLowerCase()+'|'+(p.kind==='contacts'?e:field(r,'serial',200));if(!key)throw new Error('Email is required.');const duplicate=seen.has(key)||existing.some(x=>p.kind==='companies'?x.name.toLowerCase()===n.toLowerCase():p.kind==='users'?x.email.toLowerCase()===e:x.company_id===cid&&x.name.toLowerCase()===n.toLowerCase()&&(p.kind==='contacts'?x.email.toLowerCase()===e:x.serial===field(r,'serial',200)));seen.add(key);if(duplicate){skipped++;continue}const rid=crypto.randomUUID();if(p.kind==='companies')statements.push(this.stmt('INSERT INTO companies(org_id,id,name,email,phone,address,notes) VALUES(?,?,?,?,?,?,?)',org,rid,n,e,field(r,'phone',60),field(r,'address'),field(r,'notes',10000)));if(p.kind==='contacts')statements.push(this.stmt('INSERT INTO contacts(org_id,id,company_id,name,email,phone,title) VALUES(?,?,?,?,?,?,?)',org,rid,cid,n,e,field(r,'phone',60),field(r,'title',120)));if(p.kind==='assets')statements.push(this.stmt('INSERT INTO assets(org_id,id,company_id,name,kind,serial,manufacturer,model,location,notes,status) VALUES(?,?,?,?,?,?,?,?,?,?,?)',org,rid,cid,n,field(r,'kind',80)||'Computer',field(r,'serial',200),field(r,'manufacturer',120),field(r,'model',120),field(r,'location',200),field(r,'notes',10000),'Active'));if(p.kind==='users'){if(!e)throw new Error('Email is required.');if(await this.one('SELECT m.user_id FROM memberships m JOIN users u ON u.id=m.user_id WHERE m.org_id=? AND lower(u.email)=?',org,e)){skipped++;continue}statements.push(this.stmt('INSERT INTO invitations(id,org_id,email,role,expires) VALUES(?,?,?,?,?)',rid,org,e,'Viewer',new Date(Date.now()+7*86400000).toISOString()));}preview.push({row:i+2,name:n,email:e,company:r.company??''});}catch(e){errors.push(`Row ${i+2}: ${e instanceof z.ZodError?e.issues.map(x=>x.message).join('; '):e instanceof Error?e.message:'Invalid record'}`)}}
 if(p.apply){if(errors.length)throw new HttpError(400,'Correct the CSV errors before importing.');if(statements.length)await this.db.batch([...statements,this.log(org,'imports','CSV imported',null,{kind:p.kind,created:statements.length,skipped})]);}
 return {created:statements.length,skipped,errors,preview:preview.slice(0,20),applied:p.apply};
 }
 async search(org:string,url:URL){await this.context(org);const q=(url.searchParams.get('q')??'').trim().slice(0,150);if(!q)return {results:[]};const results:unknown[]=[];const specifications=[['companies','name||\' \'||email','name'],['contacts','name||\' \'||email','name'],['projects','name||\' \'||description','name'],['assets','name||\' \'||serial||\' \'||model','name']] as const;for(const [table,hay,label] of specifications){results.push(...(await this.rows(`SELECT id,${label} label FROM ${table} WHERE org_id=? AND instr(lower(${hay}),lower(?))>0 LIMIT 8`,org,q)).map(r=>({...r,kind:table})))}results.push(...(await this.listTickets(org,new URL('https://local/?view=all&q='+encodeURIComponent(q)))).tickets.map(t=>({id:t.id,label:'#'+t.id+' · '+t.title,kind:'tickets'})));results.push(...(await this.rows('SELECT u.id,u.name label FROM memberships m JOIN users u ON u.id=m.user_id WHERE m.org_id=? AND instr(lower(u.name||u.email),lower(?))>0 LIMIT 8',org,q)).map(r=>({...r,kind:'settings'})));return {results};}
 async dashboard(org:string){await this.context(org);const now=new Date().toISOString(),day=now.slice(0,10);return {metrics:await this.one("SELECT SUM(closed=0) open,SUM(closed=0 AND assignee_id IS NULL) unassigned,SUM(closed=0 AND resolution_due<?) overdue,SUM(closed=0 AND resolution_due>=? AND resolution_due<?) risk,SUM(substr(created,1,10)=?) createdToday,SUM(substr(resolved,1,10)=?) closedToday FROM tickets WHERE org_id=?",now,now,new Date(Date.now()+3600000).toISOString(),day,day,org),tickets:await this.rows("SELECT id,title,status,priority,updated,assignee_id assigneeId FROM tickets WHERE org_id=? AND closed=0 ORDER BY CASE priority WHEN 'Critical' THEN 0 WHEN 'High' THEN 1 ELSE 2 END,updated DESC LIMIT 30",org),schedule:await this.rows('SELECT s.id,s.title,s.starts,u.name member FROM scheduled_work s JOIN users u ON u.id=s.member_id WHERE s.org_id=? AND s.cancelled=0 AND s.ends>? ORDER BY s.starts LIMIT 10',org,now),projects:await this.one("SELECT COUNT(*) total FROM projects WHERE org_id=? AND status NOT IN ('Completed','Cancelled')",org),load:(await this.dispatch(org)).members};}
 async prefs(org:string,payload?:unknown){await this.context(org);if(payload!==undefined){const p=z.object({hiddenWidgets:z.array(z.string().max(30)).max(20).default([]),widgetOrder:z.array(z.string().max(30)).max(20).default([]),assignment:z.boolean().default(true),schedule:z.boolean().default(true),replies:z.boolean().default(true),projects:z.boolean().default(true),sla:z.boolean().default(true),mentions:z.boolean().default(true)}).strict().parse(payload);await this.stmt('INSERT INTO preferences(org_id,user_id,data) VALUES(?,?,?) ON CONFLICT(org_id,user_id) DO UPDATE SET data=excluded.data',org,this.user.id,JSON.stringify(p)).run();}const row=await this.one<{data:string}>('SELECT data FROM preferences WHERE org_id=? AND user_id=?',org,this.user.id);return {hiddenWidgets:[],widgetOrder:[],assignment:true,schedule:true,replies:true,projects:true,sla:true,mentions:true,...(row?JSON.parse(row.data):{})};}
 async timesheet(org:string,url:URL){const ctx=await this.context(org),from=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).parse(url.searchParams.get('from')??new Date().toISOString().slice(0,10)),end=new Date(from+'T00:00:00Z');if(!Number.isFinite(+end))throw new HttpError(400,'Invalid week.');end.setUTCDate(end.getUTCDate()+7);return {entries:await this.rows('SELECT e.id,e.ticket_id ticketId,t.title,u.name person,substr(e.starts,1,10) day,e.minutes,e.billable,e.description FROM time_entries e JOIN tickets t ON t.org_id=e.org_id AND t.id=e.ticket_id JOIN users u ON u.id=e.user_id WHERE e.org_id=? AND e.user_id=? AND e.starts>=? AND e.starts<? ORDER BY e.starts',org,this.user.id,from,end.toISOString())};}
}
