import type {Service} from './service';
import type {Rule} from '../domain';
export async function planAutomation(s:Service,org:string,events:string[],values:Record<string,unknown>){
 const rules=await s.rows<Rule & {actions:string}>('SELECT id,name,trigger_type trigger,priority,board_id boardId,status,actions,enabled,version FROM automations WHERE org_id=? AND enabled=1 ORDER BY rowid LIMIT 50',org);
 const rule=rules.find(r=>events.includes(r.trigger)&&(!r.priority||r.priority===values.priority)&&(!r.boardId||r.boardId===values.boardId)&&(!r.status||r.status===values.status));
 if(!rule)return {values,note:'',effects:{},rule:null};
 const {note='',notifyUserId,taskTitle,followupTitle,...actions}=JSON.parse(rule.actions) as Rule['actions'];
 return {values:{...values,...actions,...(actions.boardId&&actions.boardId!==values.boardId&&!actions.status?{status:undefined}:{})},note,effects:{notifyUserId,taskTitle,followupTitle},rule:{id:rule.id,name:rule.name}};
}
export function businessDeadline(created:string,minutes:number,calendar:{enabled:boolean;startHour:number;endHour:number;weekdays:number[];holidays:string}|null){if(!calendar?.enabled)return new Date(Date.parse(created)+minutes*60000).toISOString();let cursor=new Date(created),remaining=minutes*60000;const holidays=new Set(calendar.holidays.split('\n').map(s=>s.trim()).filter(Boolean));for(let days=0;days<40000;days++){const date=cursor.toISOString().slice(0,10),start=new Date(date+'T00:00:00Z');start.setUTCHours(calendar.startHour);const end=new Date(date+'T00:00:00Z');end.setUTCHours(calendar.endHour);if(calendar.weekdays.includes(cursor.getUTCDay())&&!holidays.has(date)){cursor=new Date(Math.max(+cursor,+start));const available=Math.max(0,+end-+cursor);if(remaining<=available)return new Date(+cursor+remaining).toISOString();remaining-=available;}cursor=new Date(date+'T00:00:00Z');cursor.setUTCDate(cursor.getUTCDate()+1);}throw new Error('Business calendar exceeds supported deadline range.');}
export async function slaDeadlines(s:Service,org:string,priority:string,created:string,boardId?:string){const custom=boardId?await s.one<{targets:string}>('SELECT targets FROM board_settings WHERE org_id=? AND board_id=?',org,boardId):null;const override=custom?JSON.parse(custom.targets)[priority]:null;const p=override??await s.one<{response:number;resolution:number}>('SELECT response_minutes response,resolution_minutes resolution FROM sla_policies WHERE org_id=? AND priority=? AND enabled=1',org,priority);const row=p?await s.one<{data:string}>("SELECT data FROM configurations WHERE org_id=? AND kind='business-hours' ORDER BY rowid DESC LIMIT 1",org):null,calendar=row?JSON.parse(row.data):null;return {responseDue:p?businessDeadline(created,p.response,calendar):null,resolutionDue:p?businessDeadline(created,p.resolution,calendar):null};}

export async function automationEffects(s:Service,org:string,ticketId:number|'new',effects:{notifyUserId?:string;taskTitle?:string;followupTitle?:string},marker:string,source:{companyId:string;boardId:string;priority:string;assigneeId:string|null}){const n=ticketId==='new'?'(SELECT MAX(id) FROM tickets WHERE org_id=?)':'?',args=[ticketId==='new'?org:ticketId],guard='EXISTS(SELECT 1 FROM audit_events WHERE id=?)',at=new Date().toISOString(),stmts:D1PreparedStatement[]=[];if(effects.notifyUserId)stmts.push(s.stmt(`INSERT INTO notifications(id,org_id,user_id,ticket_id,title,at) SELECT ?,?,?,${n},?,? WHERE ${guard}`,crypto.randomUUID(),org,effects.notifyUserId,...args,'Automation: ticket needs your attention',at,marker));if(effects.taskTitle)stmts.push(s.stmt(`INSERT INTO project_tasks(org_id,id,project_id,title) SELECT ?,?,l.project_id,? FROM ticket_links l WHERE l.org_id=? AND l.ticket_id=${n} AND l.project_id IS NOT NULL AND ${guard}`,org,crypto.randomUUID(),effects.taskTitle,org,...args,marker));if(effects.followupTitle){const status=await s.references(org,{...source,contactId:null,status:undefined}),sla=await slaDeadlines(s,org,source.priority,at,source.boardId);stmts.push(s.stmt(`INSERT INTO tickets(org_id,id,title,description,company_id,board_id,assignee_id,status,closed,priority,created,updated,response_due,resolution_due) SELECT ?,COALESCE(MAX(id),1000)+1,?,?,?,?,?,?,0,?,?,?,?,? FROM tickets WHERE org_id=? HAVING ${guard}`,org,effects.followupTitle,'Created by an automation. Review and add the details needed for this follow-up.',source.companyId,source.boardId,source.assigneeId,status.name,source.priority,at,at,sla.responseDue,sla.resolutionDue,org,marker),s.stmt(`INSERT INTO audit_events(id,org_id,entity_id,action,author_id,at) SELECT ?,?,'ticket:'||MAX(id),?,?,? FROM tickets WHERE org_id=? HAVING ${guard}`,crypto.randomUUID(),org,'Follow-up ticket created by automation',s.user.id,at,org,marker));}return stmts;}
