import {z} from 'zod';
import {Advanced} from './advanced';
import {HttpError} from './service';
const id=z.string().min(1).max(150),name=z.string().trim().min(1).max(180),notes=z.string().trim().max(10000).default(''),date=z.union([z.literal(''),z.string().date()]),version=z.number().int().positive().optional();
const money=z.number().finite().min(0).max(100000000).refine(n=>Math.abs(n*100-Math.round(n*100))<0.00001,'Use at most two decimal places');
const planInput=z.object({budget:money,laborRate:money,currency:z.enum(['USD','CAD','GBP','EUR','AUD']),startDate:date,notes,version:z.number().int().nonnegative()}).strict();
const milestoneInput=z.object({projectId:id,title:name,due:date,memberId:id.nullable(),completed:z.boolean(),notes,version}).strict();
const expenseInput=z.object({currency:z.enum(['USD','CAD','GBP','EUR','AUD']),projectId:id,description:name,vendor:z.string().trim().max(180).default(''),category:z.enum(['Hardware','Software','Travel','Subcontractor','Other']),amount:money,date:z.string().date(),status:z.enum(['Planned','Committed','Paid','Voided']),version}).strict();
const locationInput=z.object({companyId:id,name,address:z.string().trim().max(1000),phone:z.string().trim().max(60),notes,active:z.boolean(),version}).strict();
const profileInput=z.object({mobile:z.string().trim().max(60),preferred:z.enum(['Email','Phone','Mobile','Portal']),locationId:id.nullable(),notes,version:z.number().int().nonnegative()}).strict();
export class Delivery extends Advanced {
 async projectFinance(org:string,pid:string){await this.context(org,'projects:write');const project=await this.project(org,pid),plan=await this.one<{budget_cents:number;labor_rate_cents:number;currency:string;start_date:string;notes:string;version:number}>('SELECT * FROM project_plans WHERE org_id=? AND project_id=?',org,pid),time=await this.one<{minutes:number;billableMinutes:number}>('SELECT COALESCE(SUM(e.minutes),0) minutes,COALESCE(SUM(CASE WHEN e.billable=1 THEN e.minutes ELSE 0 END),0) billableMinutes FROM time_entries e JOIN ticket_links l ON l.org_id=e.org_id AND l.ticket_id=e.ticket_id WHERE l.org_id=? AND l.project_id=?',org,pid),expenses=await this.rows<{id:string;projectId:string;description:string;vendor:string;category:string;amountCents:number;date:string;status:string;version:number}>('SELECT id,project_id projectId,description,vendor,category,amount_cents amountCents,date,status,version FROM project_expenses WHERE org_id=? AND project_id=? ORDER BY date DESC,id',org,pid);const actualExpense=expenses.filter(e=>['Committed','Paid'].includes(e.status)).reduce((sum,e)=>sum+e.amountCents,0),plannedExpense=expenses.filter(e=>e.status==='Planned').reduce((sum,e)=>sum+e.amountCents,0),laborCost=Math.round((time?.minutes??0)*(plan?.labor_rate_cents??0)/60);return {plan:plan?{budget:plan.budget_cents/100,laborRate:plan.labor_rate_cents/100,currency:plan.currency,startDate:plan.start_date,notes:plan.notes,version:plan.version}:{budget:0,laborRate:0,currency:'USD',startDate:'',notes:'',version:0},expenses:expenses.map(({amountCents,...e})=>({...e,amount:amountCents/100})),totals:{hours:(time?.minutes??0)/60,billableHours:(time?.billableMinutes??0)/60,estimatedHours:(await this.one<{hours:number}>('SELECT estimated_hours hours FROM projects WHERE org_id=? AND id=?',org,pid))?.hours??0,laborCost:laborCost/100,actualExpenses:actualExpense/100,plannedExpenses:plannedExpense/100,remaining:((plan?.budget_cents??0)-actualExpense-laborCost)/100}};}
 async planSave(org:string,pid:string,payload:unknown){await this.context(org,'projects:write');await this.project(org,pid);const p=planInput.parse(payload),before=await this.one<{currency:string}>('SELECT currency FROM project_plans WHERE org_id=? AND project_id=?',org,pid);if(before&&before.currency!==p.currency&&await this.one('SELECT id FROM project_expenses WHERE org_id=? AND project_id=? LIMIT 1',org,pid))throw new HttpError(409,'Currency cannot change after expenses have been recorded.');const values=[Math.round(p.budget*100),Math.round(p.laborRate*100),p.currency,p.startDate,p.notes];const result=await this.db.batch([p.version?this.stmt('UPDATE project_plans SET budget_cents=?,labor_rate_cents=?,currency=?,start_date=?,notes=?,version=version+1 WHERE org_id=? AND project_id=? AND version=?',...values,org,pid,p.version):this.stmt('INSERT INTO project_plans(budget_cents,labor_rate_cents,currency,start_date,notes,org_id,project_id) VALUES(?,?,?,?,?,?,?)',...values,org,pid),this.log(org,'project:'+pid,'Project financial plan saved',null,p,true)]);if(!result[0].meta.changes)throw new HttpError(409,'The financial plan changed. Reload it before saving.');return {ok:true};}
 async milestones(org:string,pid:string){await this.project(org,pid);return {milestones:await this.rows('SELECT m.id,m.project_id projectId,m.title,m.due,m.member_id memberId,m.completed,m.notes,m.version,COALESCE(u.name,\'Unassigned\') member FROM milestones m LEFT JOIN users u ON u.id=m.member_id WHERE m.org_id=? AND m.project_id=? ORDER BY m.completed,m.due,m.title',org,pid)};}
 async milestoneSave(org:string,payload:unknown,rid?:string){await this.context(org,'projects:write');const p=milestoneInput.parse(payload);await this.project(org,p.projectId);await this.member(org,p.memberId);if(rid)await this.fixedParent(org,'milestones',rid,'project_id',p.projectId);return this.saveRecord(org,'milestones',p,rid,'Project milestone');}
 async expenseSave(org:string,payload:unknown,rid?:string){await this.context(org,'projects:write');const {amount,currency,...p}=expenseInput.parse(payload);await this.project(org,p.projectId);if(!await this.one('SELECT project_id FROM project_plans WHERE org_id=? AND project_id=? AND currency=?',org,p.projectId,currency))throw new HttpError(409,'Save or reload the financial plan before recording expenses.');if(rid)await this.fixedParent(org,'project_expenses',rid,'project_id',p.projectId);const n=rid??crypto.randomUUID(),v=[p.description,p.vendor,p.category,Math.round(amount*100),p.date,p.status],result=await this.db.batch([rid?this.stmt('UPDATE project_expenses SET description=?,vendor=?,category=?,amount_cents=?,date=?,status=?,version=version+1 WHERE org_id=? AND id=? AND version=? AND EXISTS(SELECT 1 FROM project_plans WHERE org_id=? AND project_id=? AND currency=?)',...v,org,n,p.version??0,org,p.projectId,currency):this.stmt('INSERT INTO project_expenses(description,vendor,category,amount_cents,date,status,org_id,id,project_id) SELECT ?,?,?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM project_plans WHERE org_id=? AND project_id=? AND currency=?)',...v,org,n,p.projectId,org,p.projectId,currency),this.log(org,'project:'+p.projectId,rid?'Project expense updated':'Project expense created',null,{...p,amount,currency},true)]);if(!result[0].meta.changes)throw new HttpError(409,'Expense or currency changed. Reload before saving.');return {id:n};}

 async fixedParent(org:string,table:'milestones'|'project_expenses'|'company_locations',rid:string,column:'project_id'|'company_id',expected:string){const row=await this.one<Record<string,string>>(`SELECT ${column} parent FROM ${table} WHERE org_id=? AND id=?`,org,rid);if(!row)throw new HttpError(404,'Record not found.');if(row.parent!==expected)throw new HttpError(409,'This record cannot be moved to another project or company.');}
 async locations(org:string,cid:string){await this.context(org);await this.company(org,cid);return {locations:await this.rows('SELECT id,company_id companyId,name,address,phone,notes,active,version FROM company_locations WHERE org_id=? AND company_id=? ORDER BY active DESC,name',org,cid)};}
 async locationSave(org:string,payload:unknown,rid?:string){await this.context(org,'directory:write');const p=locationInput.parse(payload);await this.company(org,p.companyId);if(rid)await this.fixedParent(org,'company_locations',rid,'company_id',p.companyId);return this.saveRecord(org,'company_locations',p,rid,'Company location');}
 async contactProfile(org:string,cid:string){await this.context(org);const contact=await this.one<{id:string;name:string;companyId:string}>('SELECT id,name,company_id companyId FROM contacts WHERE org_id=? AND id=?',org,cid);if(!contact)throw new HttpError(404,'Contact not found.');return {contact,profile:await this.one('SELECT mobile,preferred,location_id locationId,notes,version FROM contact_profiles WHERE org_id=? AND contact_id=?',org,cid)??{mobile:'',preferred:'Email',locationId:null,notes:'',version:0},locations:(await this.locations(org,contact.companyId)).locations,tickets:await this.rows('SELECT id,title,status FROM tickets WHERE org_id=? AND contact_id=? ORDER BY updated DESC LIMIT 30',org,cid)};}
 async contactProfileSave(org:string,cid:string,payload:unknown){await this.context(org,'directory:write');const p=profileInput.parse(payload),{contact}=await this.contactProfile(org,cid);if(p.locationId&&!await this.one('SELECT id FROM company_locations WHERE org_id=? AND id=? AND company_id=?',org,p.locationId,contact.companyId))throw new HttpError(400,'Choose a location belonging to this contact’s company.');const values=[p.mobile,p.preferred,p.locationId,p.notes],r=await this.db.batch([p.version?this.stmt('UPDATE contact_profiles SET mobile=?,preferred=?,location_id=?,notes=?,version=version+1 WHERE org_id=? AND contact_id=? AND version=?',...values,org,cid,p.version):this.stmt('INSERT INTO contact_profiles(mobile,preferred,location_id,notes,org_id,contact_id) VALUES(?,?,?,?,?,?)',...values,org,cid),this.log(org,'contacts:'+cid,'Contact profile saved',null,p,true)]);if(!r[0].meta.changes)throw new HttpError(409,'The contact profile changed. Reload before saving.');return {ok:true};}
}
