import {env} from 'cloudflare:workers';
import type {Enterprise} from './enterprise';
import {HttpError} from './service';
import {mutationGuard} from './files';
export async function documentRequest(s:Enterprise,request:Request,org:string,kind:string,rid:string,fileId?:string,portal=false){if(!['company','project'].includes(kind))throw new HttpError(404,'Document collection not found.');let company=rid;if(portal){if(kind!=='company')throw new HttpError(404,'Not found.');await s.portalContext(org,rid);}else{await s.context(org,request.method==='POST'?(kind==='project'?'projects:write':'directory:write'):undefined);if(kind==='project'){const p=await s.one<{company_id:string}>('SELECT company_id FROM projects WHERE org_id=? AND id=?',org,rid);if(!p)throw new HttpError(404,'Project not found.');company=p.company_id;}else await s.company(org,rid);}
 const filter=portal?"d.org_id=? AND d.company_id=? AND d.visibility='Customer' AND (d.project_id IS NULL OR EXISTS(SELECT 1 FROM projects p WHERE p.org_id=d.org_id AND p.id=d.project_id AND p.visible=1))":kind==='company'?'d.org_id=? AND d.company_id=?':'d.org_id=? AND d.project_id=?';
 if(request.method==='GET'){if(!fileId)return {files:await s.rows(`SELECT d.id,d.name,d.size,d.at,d.visibility FROM documents d WHERE ${filter} ORDER BY d.at DESC`,org,rid)};const f=await s.one<{name:string;object_key:string}>(`SELECT d.name,d.object_key FROM documents d WHERE ${filter} AND d.id=?`,org,rid,fileId);if(!f)throw new HttpError(404,'File not found.');if(!env.BUCKET)throw new HttpError(503,'File storage is unavailable.');const o=await env.BUCKET.get(f.object_key);if(!o)throw new HttpError(404,'File not found.');return new Response(o.body,{headers:{'Content-Type':'application/octet-stream','Content-Disposition':"attachment; filename*=UTF-8''"+encodeURIComponent(f.name),'X-Content-Type-Options':'nosniff','Cache-Control':'private, no-store'}});}
 if(portal||request.method!=='POST'||fileId)throw new HttpError(405,'This action is unavailable.');mutationGuard(request);if(!env.BUCKET)throw new HttpError(503,'File storage is unavailable.');const reader=request.body?.getReader();if(!reader)throw new HttpError(400,'Choose a file.');const chunks:Uint8Array[]=[];let size=0;while(true){const {value,done}=await reader.read();if(done)break;size+=value.length;if(size>5*1024*1024+65536){await reader.cancel();throw new HttpError(413,'Files must be 5 MB or smaller.');}chunks.push(value)}const bytes=new Uint8Array(size);let offset=0;for(const c of chunks){bytes.set(c,offset);offset+=c.length}let form:FormData;try{form=await new Request(request.url,{method:'POST',headers:{'Content-Type':request.headers.get('content-type')??''},body:bytes}).formData()}catch{throw new HttpError(400,'Choose a valid file.');}const file=form.get('file');if(!file||typeof file==='string'||file.size>5*1024*1024||!file.size)throw new HttpError(400,'Choose a non-empty file up to 5 MB.');const visibility=form.get('visibility')==='Customer'?'Customer':'Internal',name=file.name.replace(/[\x00-\x1f/\\]/g,'_').slice(0,220)||'document',id=crypto.randomUUID(),key=org+'/documents/'+id;await s.register();await env.BUCKET.put(key,await file.arrayBuffer());try{await s.db.batch([s.stmt('INSERT INTO documents(id,org_id,company_id,project_id,name,size,object_key,visibility,author_id,at) VALUES(?,?,?,?,?,?,?,?,?,?)',id,org,company,kind==='project'?rid:null,name,file.size,key,visibility,s.user.id,new Date().toISOString()),s.log(org,(kind==='project'?'project:':'companies:')+rid,'Document uploaded',null,{id,name,visibility})]);}catch(e){await env.BUCKET.delete(key);throw e}return {id};
}
