import {z} from 'zod';
import {Delivery} from './delivery';
import {HttpError} from './service';
import {priorities,type Capability} from '../domain';
const id=z.string().min(1).max(150),name=z.string().trim().min(1).max(180),version=z.number().int().positive().optional(),notes=z.string().trim().max(10000).default('');
const currencies=z.enum(['USD','CAD','GBP','EUR','AUD']);
const item=z.object({description:name,quantity:z.number().int().min(1).max(100000),unitCost:z.number().min(0).max(1000000).refine(v=>Math.abs(v*100-Math.round(v*100))<.00001,'Use at most two decimals')}).strict();
const purchaseInput=z.object({projectId:id,vendor:name,reference:z.string().trim().max(180),currency:currencies,items:z.array(item).min(1).max(100),notes,version}).strict();
const templateInput=z.object({name,version,tasks:z.array(z.object({title:name,role:z.string().trim().max(80),days:z.number().int().min(0).max(3650),dependsOn:z.number().int().min(0).max(99).nullable()}).strict()).min(1).max(100),milestones:z.array(z.object({title:name,days:z.number().int().min(0).max(3650)}).strict()).max(30)}).strict().refine(t=>t.tasks.every((v,i)=>v.dependsOn===null||v.dependsOn<i),'Prerequisites must refer to an earlier task');
export class Enterprise extends Delivery {
 async boardSettings(org:string,bid:string){await this.context(org);if(!await this.one('SELECT id FROM boards WHERE org_id=? AND id=?',org,bid))throw new HttpError(404,'Board not found.');const r=await this.one<{default_member_id:string|null;email:string;labels:string;targets:string;version:number}>('SELECT * FROM board_settings WHERE org_id=? AND board_id=?',org,bid);return r?{defaultMemberId:r.default_member_id,email:r.email,labels:JSON.parse(r.labels),targets:JSON.parse(r.targets),version:r.version}:{defaultMemberId:null,email:'',labels:Object.fromEntries(priorities.map(p=>[p,p])),targets:{},version:0};}
 async boardSettingsSave(org:string,bid:string,payload:unknown){await this.context(org,'boards:write');await this.boardSettings(org,bid);const p=z.object({defaultMemberId:id.nullable(),email:z.union([z.literal(''),z.string().email().max(254)]),labels:z.object({Critical:name,High:name,Normal:name,Low:name}).strict().refine(l=>new Set(Object.values(l).map(s=>s.toLowerCase())).size===4,'Priority names must be unique'),targets:z.record(z.enum(priorities),z.object({response:z.number().int().min(1).max(525600),resolution:z.number().int().min(1).max(525600)}).strict()),version:z.number().int().nonnegative()}).strict().parse(payload);await this.member(org,p.defaultMemberId);const args=[p.defaultMemberId,p.email,JSON.stringify(p.labels),JSON.stringify(p.targets)],r=await this.db.batch([p.version?this.stmt('UPDATE board_settings SET default_member_id=?,email=?,labels=?,targets=?,version=version+1 WHERE org_id=? AND board_id=? AND version=?',...args,org,bid,p.version):this.stmt('INSERT INTO board_settings(default_member_id,email,labels,targets,org_id,board_id) VALUES(?,?,?,?,?,?)',...args,org,bid),this.log(org,'boards:'+bid,'Advanced board settings saved',null,p,true)]);if(!r[0].meta.changes)throw new HttpError(409,'Board settings changed. Reload before saving.');return {ok:true};}
 async purchasing(org:string,pid:string){await this.context(org,'projects:write');await this.project(org,pid);return {purchases:(await this.rows<{items:string}>('SELECT id,project_id projectId,vendor,reference,currency,items,total_cents totalCents,status,notes,created,version FROM purchases WHERE org_id=? AND project_id=? ORDER BY created DESC',org,pid)).map(p=>({...p,items:JSON.parse(p.items)}))};}
 async purchaseSave(org:string,payload:unknown,rid?:string){await this.context(org,'projects:write');const p=purchaseInput.parse(payload);await this.project(org,p.projectId);const total=p.items.reduce((s,i)=>s+Math.round(i.unitCost*100)*i.quantity,0);if(!Number.isSafeInteger(total)||total>10000000000)throw new HttpError(400,'Purchase total exceeds 100 million.');const n=rid??crypto.randomUUID();const values=[p.vendor,p.reference,p.currency,JSON.stringify(p.items),total,p.notes];const r=await this.db.batch([rid?this.stmt("UPDATE purchases SET vendor=?,reference=?,currency=?,items=?,total_cents=?,notes=?,version=version+1 WHERE org_id=? AND id=? AND project_id=? AND version=? AND status='Draft'",...values,org,n,p.projectId,p.version??0):this.stmt('INSERT INTO purchases(vendor,reference,currency,items,total_cents,notes,org_id,id,project_id,created) VALUES(?,?,?,?,?,?,?,?,?,?)',...values,org,n,p.projectId,new Date().toISOString()),this.log(org,'project:'+p.projectId,'Purchase draft saved',null,{...p,totalCents:total},true)]);if(!r[0].meta.changes)throw new HttpError(409,'Only the latest draft can be edited.');return {id:n};}
 async purchaseTransition(org:string,rid:string,payload:unknown){await this.context(org,'projects:write');const p=z.object({status:z.enum(['Approved','Ordered','Received','Cancelled']),version:z.number().int().positive()}).strict().parse(payload),before=await this.one<{status:string;project_id:string}>('SELECT status,project_id FROM purchases WHERE org_id=? AND id=?',org,rid);if(!before)throw new HttpError(404,'Purchase not found.');const allowed:Record<string,string[]>={Draft:['Approved','Cancelled'],Approved:['Ordered','Cancelled'],Ordered:['Received','Cancelled'],Received:[],Cancelled:[]};if(!allowed[before.status]?.includes(p.status))throw new HttpError(409,'This status transition is not allowed.');const r=await this.db.batch([this.stmt('UPDATE purchases SET status=?,version=version+1 WHERE org_id=? AND id=? AND version=? AND status=?',p.status,org,rid,p.version,before.status),this.log(org,'project:'+before.project_id,'Purchase '+p.status.toLowerCase(),before,{purchaseId:rid,...p},true)]);if(!r[0].meta.changes)throw new HttpError(409,'Purchase changed. Reload it first.');return {ok:true};}
 async linkedAssets(org:string,cid:string){const {contact}=await this.contactProfile(org,cid);return {assets:await this.rows('SELECT id,name,serial,status FROM assets WHERE org_id=? AND company_id=? ORDER BY name',org,contact.companyId),links:await this.rows('SELECT asset_id assetId FROM contact_assets WHERE org_id=? AND contact_id=?',org,cid)};}
 async linkAsset(org:string,cid:string,payload:unknown){await this.context(org,'directory:write');const p=z.object({assetId:id,remove:z.boolean()}).strict().parse(payload),{contact}=await this.contactProfile(org,cid);if(!await this.one('SELECT id FROM assets WHERE org_id=? AND id=? AND company_id=?',org,p.assetId,contact.companyId))throw new HttpError(400,'Choose equipment from the contact’s company.');await this.db.batch([p.remove?this.stmt('DELETE FROM contact_assets WHERE org_id=? AND contact_id=? AND asset_id=?',org,cid,p.assetId):this.stmt('INSERT INTO contact_assets(org_id,contact_id,asset_id) VALUES(?,?,?) ON CONFLICT DO NOTHING',org,cid,p.assetId),this.log(org,'contacts:'+cid,p.remove?'Equipment unlinked':'Equipment linked',null,p)]);return {ok:true};}
 async deliveryTemplates(org:string){await this.context(org);return {templates:(await this.rows<{id:string;name:string;data:string;version:number}>('SELECT * FROM delivery_templates WHERE org_id=? ORDER BY name',org)).map(t=>({id:t.id,name:t.name,...JSON.parse(t.data),version:t.version}))};}
 async templateSave(org:string,payload:unknown,rid?:string){await this.context(org,'projects:write');const p=templateInput.parse(payload);return this.saveRecord(org,'delivery_templates',{name:p.name,data:JSON.stringify({tasks:p.tasks,milestones:p.milestones}),version:p.version},rid,'Delivery template');}
 async templateApply(org:string,rid:string,payload:unknown){await this.context(org,'projects:write');const p=z.object({projectId:id,version:z.number().int().positive(),start:z.string().date(),owners:z.record(z.string().max(80),id.nullable())}).strict().parse(payload);await this.project(org,p.projectId);const row=await this.one<{name:string;data:string}>('SELECT name,data FROM delivery_templates WHERE org_id=? AND id=?',org,rid);if(!row)throw new HttpError(404,'Template not found.');const t=templateInput.parse({name:row.name,...JSON.parse(row.data)});for(const member of Object.values(p.owners))await this.member(org,member);const at=new Date().toISOString(),marker=crypto.randomUUID(),ids=t.tasks.map(()=>crypto.randomUUID()),guard='EXISTS(SELECT 1 FROM audit_events WHERE id=?)',due=(n:number)=>new Date(Date.parse(p.start+'T00:00:00Z')+n*86400000).toISOString().slice(0,10);const r=await this.db.batch([this.stmt('INSERT INTO audit_events(id,org_id,entity_id,action,author_id,at) SELECT ?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM projects WHERE org_id=? AND id=? AND version=?)',marker,org,'project:'+p.projectId,'Delivery template applied: '+row.name,this.user.id,at,org,p.projectId,p.version),...t.tasks.map((task,i)=>this.stmt(`INSERT INTO project_tasks(org_id,id,project_id,title,member_id,due) SELECT ?,?,?,?,?,? WHERE ${guard}`,org,ids[i],p.projectId,task.title,p.owners[task.role]??null,due(task.days),marker)),...t.tasks.flatMap((task,i)=>task.dependsOn===null?[]:[this.stmt(`INSERT INTO task_dependencies(org_id,task_id,dependency_id) SELECT ?,?,? WHERE ${guard}`,org,ids[i],ids[task.dependsOn],marker)]),...t.milestones.map(m=>this.stmt(`INSERT INTO milestones(org_id,id,project_id,title,due) SELECT ?,?,?,?,? WHERE ${guard}`,org,crypto.randomUUID(),p.projectId,m.title,due(m.days),marker)),this.stmt(`UPDATE projects SET version=version+1 WHERE org_id=? AND id=? AND ${guard}`,org,p.projectId,marker)]);if(!r[0].meta.changes)throw new HttpError(409,'Project changed. Reload before applying the template.');return {tasks:t.tasks.length,milestones:t.milestones.length};}
 async scanNotifications(org:string){await this.context(org,'automation:write');const at=new Date().toISOString(),soon=new Date(Date.now()+3600000).toISOString(),old=new Date(Date.now()-7*86400000).toISOString();const tickets=await this.rows<{id:number;assignee_id:string;kind:string;event_key:string}>(`WITH candidates AS (SELECT id,assignee_id,CASE WHEN resolution_due<? THEN 'SLA overdue' WHEN resolution_due<? THEN 'SLA approaching' ELSE 'Ticket inactive' END kind,CASE WHEN resolution_due<? THEN resolution_due ELSE updated END stamp,updated FROM tickets WHERE org_id=? AND closed=0 AND assignee_id IS NOT NULL AND (resolution_due<? OR updated<?)) SELECT *,kind||':'||id||':'||stamp event_key FROM candidates WHERE NOT EXISTS(SELECT 1 FROM automation_events WHERE org_id=? AND key=kind||':'||candidates.id||':'||stamp) ORDER BY updated LIMIT 100`,at,soon,soon,org,soon,old,org);let created=0;for(const t of tickets){const r=await this.db.batch([this.stmt('INSERT INTO automation_events(org_id,key,at) VALUES(?,?,?) ON CONFLICT DO NOTHING',org,t.event_key,at),this.stmt('INSERT INTO notifications(id,org_id,user_id,ticket_id,title,at) SELECT ?,?,?,?,?,? WHERE changes()>0',crypto.randomUUID(),org,t.assignee_id,t.id,t.kind+': #'+t.id,at)]);created+=Number(r[1].meta.changes>0);}return {created,checked:tickets.length};}
}
