import {env} from 'cloudflare:workers';
import {headers} from 'next/headers';
import {ZodError} from 'zod';
import {HttpError} from './service';
import {Completion} from './completion';
import {mutationGuard} from './files';
import {accountIdentity} from '../auth/server';
export async function service(){
  const user=await accountIdentity();
  if(!user)throw new HttpError(401,'Sign in to continue.');
  if(!env.DB)throw new HttpError(503,'Shared storage is not available yet. Please try again shortly.');
  return new Completion(env.DB,user);
}
export async function body(request:Request,limit=32768){mutationGuard(request);if(!request.headers.get('content-type')?.includes('application/json'))throw new HttpError(415,'Expected JSON.');const reader=request.body?.getReader();if(!reader)throw new HttpError(400,'A request body is required.');const chunks:Uint8Array[]=[];let size=0;while(true){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>limit){await reader.cancel();throw new HttpError(413,'The submitted form is too large.');}chunks.push(value)}const all=new Uint8Array(size);let offset=0;for(const chunk of chunks){all.set(chunk,offset);offset+=chunk.length}try{return JSON.parse(new TextDecoder().decode(all))}catch{throw new HttpError(400,'Invalid JSON.');}}
export async function respond(action:()=>Promise<unknown>){try{const result=await action();return result instanceof Response?result:Response.json(result,{headers:{'Cache-Control':'private, no-store'}})}catch(e){let status=500,message='The request could not be completed. Please try again.';if(e instanceof HttpError){status=e.status;message=e.message}else if(e instanceof ZodError){status=400;message=e.issues.map(i=>`${i.path.join('.')||'Form'}: ${i.message}`).join('; ')}else if(e instanceof Error&&/contact_location|plan_currency|contact_asset|document_company|invoice_/.test(e.message)){status=409;message='The linked company, project currency, or invoice amount conflicts with another record. Reload before saving.'}else if(e instanceof Error&&/dependency_|relation_/.test(e.message)){status=409;message=/cycle/.test(e.message)?'This dependency would create a cycle.':/completed/.test(e.message)?'Reopen dependent tasks first.':/incomplete/.test(e.message)?'Complete prerequisite tasks first.':'Related records must belong to the same project or company.'}else if(e instanceof Error&&/schedule_overlap/.test(e.message)){status=409;message='This member already has scheduled work at that time. Choose another time or member.'}else if(e instanceof Error&&/time_overlap/.test(e.message)){status=409;message='This time overlaps an existing entry. Correct the time range before saving.'}else if(e instanceof Error&&/running_timers/.test(e.message)){status=409;message='A timer is already running. Stop it before starting another.'}else if(e instanceof Error&&/UNIQUE constraint failed/.test(e.message)){status=409;message='A record with that name already exists in this organization.'}else if(e instanceof Error&&/FOREIGN KEY constraint failed/.test(e.message)){status=409;message='A related record changed. Refresh and try again.'}return Response.json({error:message},{status,headers:{'Cache-Control':'private, no-store'}})}}
