import {z} from 'zod';
import {planAutomation,slaDeadlines,automationEffects} from './automation';
import {seedTickets,companies as sampleCompanies} from '../tickets';
import {can,defaultStatuses,priorities,roles,type Identity,type Role,type Capability,type Board,type TicketRow,type Organization} from '../domain';
export class HttpError extends Error {status:number; constructor(status:number,message:string){super(message);this.status=status;}}
const id=z.string().min(1).max(150),name=z.string().trim().min(1).max(120),email=z.union([z.literal(''),z.string().trim().email().max(254)]).default('');
const companyInput=z.object({name,email,phone:z.string().trim().max(60).default(''),address:z.string().trim().max(1000).default(''),notes:z.string().trim().max(10000).default(''),version:z.number().int().positive().optional()}).strict();
const contactInput=z.object({name,companyId:id,email,phone:z.string().trim().max(60).default(''),title:z.string().trim().max(120).default(''),version:z.number().int().positive().optional()}).strict();
const boardInput=z.object({name,description:z.string().trim().max(1000).default(''),statuses:z.array(z.object({name:z.string().trim().min(1).max(60),closed:z.boolean()}).strict()).min(2).max(30).refine(s=>new Set(s.map(x=>x.name.toLowerCase())).size===s.length,'Status names must be unique').refine(s=>s.some(x=>!x.closed)&&s.some(x=>x.closed),'Include at least one open and one closed status'),version:z.number().int().positive().optional()}).strict();
const ticketInput=z.object({parentId:z.number().int().positive().optional(),title:z.string().trim().min(1).max(180),description:z.string().trim().max(10000).default(''),companyId:id,contactId:id.nullable().default(null),boardId:id,assigneeId:id.nullable().default(null),priority:z.enum(priorities).default('Normal'),status:z.string().trim().min(1).max(60).optional()}).strict();
const ticketUpdate=ticketInput.omit({parentId:true}).partial().extend({version:z.number().int().positive()}).strict();
const TICKET_SQL=`SELECT (SELECT target_id FROM ticket_relations r WHERE r.org_id=t.org_id AND r.ticket_id=t.id AND r.kind='merge') mergedInto,t.id,t.title,t.description,t.company_id companyId,t.contact_id contactId,t.board_id boardId,t.assignee_id assigneeId,t.status,t.closed,t.priority,t.created,t.updated,t.version,t.response_due responseDue,t.resolution_due resolutionDue,t.responded,t.resolved,c.name company,b.name board,co.name contact,COALESCE(u.name,'Unassigned') assignee FROM tickets t JOIN companies c ON c.org_id=t.org_id AND c.id=t.company_id JOIN boards b ON b.org_id=t.org_id AND b.id=t.board_id LEFT JOIN contacts co ON co.org_id=t.org_id AND co.id=t.contact_id LEFT JOIN users u ON u.id=t.assignee_id`;
export class Service {
 db:D1Database;user:Identity;
 constructor(db:D1Database,user:Identity|null){if(!user?.id||!user.email)throw new HttpError(401,'Sign in to continue.');this.db=db;this.user={...user,email:user.email.toLowerCase()};}
 stmt(sql:string,...args:unknown[]){return this.db.prepare(sql).bind(...args)}
 async rows<T=Record<string,unknown>>(sql:string,...args:unknown[]):Promise<T[]>{return (await this.stmt(sql,...args).all<T>()).results;}
 async one<T=Record<string,unknown>>(sql:string,...args:unknown[]){return this.stmt(sql,...args).first<T>();}
 async register(){await this.stmt('INSERT INTO users(id,email,name) VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET email=excluded.email,name=excluded.name',this.user.id,this.user.email,this.user.name).run();}
 async context(org:string,cap?:Capability){id.parse(org);const row=await this.one<Organization>('SELECT o.id,o.name,m.role FROM organizations o JOIN memberships m ON m.org_id=o.id WHERE o.id=? AND m.user_id=?',org,this.user.id);if(!row)throw new HttpError(403,'You do not have access to this organization.');if(!['Owner','Administrator'].includes(row.role)){const custom=await this.one<{name:string;capabilities:string}>('SELECT r.name,r.capabilities FROM custom_roles r JOIN role_assignments a ON a.org_id=r.org_id AND a.role_id=r.id WHERE a.org_id=? AND a.user_id=?',org,this.user.id);if(custom){row.roleName=custom.name;row.capabilities=JSON.parse(custom.capabilities)}}if(cap&&!can(row,cap))throw new HttpError(403,'Your role does not allow this action.');return row;}

 log(org:string,entity:string,action:string,before:unknown=null,after:unknown=null,conditional=false,logId=crypto.randomUUID()){return this.stmt(`INSERT INTO audit_events(id,org_id,entity_id,action,author_id,before,after,at) SELECT ?,?,?,?,?,?,?,? ${conditional?'WHERE changes() > 0':''}`,logId,org,entity,action,this.user.id,before===null?null:JSON.stringify(before),after===null?null:JSON.stringify(after),new Date().toISOString());}
 async account(){await this.register();return {user:this.user,organizations:await this.rows('SELECT o.id,o.name,m.role FROM organizations o JOIN memberships m ON m.org_id=o.id WHERE m.user_id=? ORDER BY o.created',this.user.id),invitations:await this.rows('SELECT i.id,i.email,i.role,i.expires,o.name FROM invitations i JOIN organizations o ON o.id=i.org_id WHERE i.email=? AND i.expires>?',this.user.email,new Date().toISOString())};}
 async createOrganization(payload:unknown){const p=z.object({name,sample:z.boolean().default(false)}).strict().parse(payload);await this.register();const org=crypto.randomUUID(),at=new Date().toISOString();await this.db.batch([this.stmt('INSERT INTO organizations(id,name,created) VALUES(?,?,?)',org,p.name,at),this.stmt('INSERT INTO memberships(org_id,user_id,role) VALUES(?,?,?)',org,this.user.id,'Owner'),...['Help Desk','Network Engineering'].map(n=>this.stmt('INSERT INTO boards(id,org_id,name,description,statuses) VALUES(?,?,?,?,?)',crypto.randomUUID(),org,n,'',JSON.stringify(defaultStatuses))),this.log(org,org,'Organization created',null,p)]);if(p.sample)await this.seed(org);return {id:org};}
 async seed(org:string){await this.context(org,'organization:write');const companies=sampleCompanies.map(name=>({id:crypto.randomUUID(),name})),boards=await this.rows<{id:string;name:string}>('SELECT id,name FROM boards WHERE org_id=?',org);const at=new Date().toISOString();await this.db.batch([...companies.map(c=>this.stmt('INSERT INTO companies(id,org_id,name,notes) VALUES(?,?,?,?)',c.id,org,c.name,'Fictional sample company.')), ...Array.from({length:25},(_,i)=>this.stmt('INSERT INTO contacts(id,org_id,company_id,name,email,title) VALUES(?,?,?,?,?,?)',crypto.randomUUID(),org,companies[i%companies.length].id,['Avery','Blake','Charlie','Dakota','Emery'][i%5]+' '+['Bennett','Reese','Hayes','Quinn','Lane'][Math.floor(i/5)],'contact'+(i+1)+'@example.com','IT contact')), ...seedTickets().map((t,i)=>this.stmt('INSERT INTO tickets(org_id,id,title,description,company_id,board_id,assignee_id,status,closed,priority,created,updated) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',org,t.id,t.title,t.description,companies.find(c=>c.name===t.company)!.id,boards[i%boards.length].id,i%3===0?null:this.user.id,t.status,Number(['Resolved','Closed'].includes(t.status)),t.priority,t.created,t.updated)),this.log(org,org,'Sample records added',null,{companies:10,contacts:25,tickets:54,at})]);}
 async acceptInvitation(payload:unknown){const {invitationId}=z.object({invitationId:id}).strict().parse(payload);await this.register();const invitation=await this.one<{org_id:string;role:Role}>('SELECT org_id,role FROM invitations WHERE id=? AND email=? AND expires>?',invitationId,this.user.email,new Date().toISOString());if(!invitation)throw new HttpError(404,'This invitation is unavailable or expired.');const result=await this.db.batch([this.stmt('INSERT INTO memberships(org_id,user_id,role) SELECT org_id,?,role FROM invitations WHERE id=? AND email=? AND expires>? ON CONFLICT(org_id,user_id) DO NOTHING',this.user.id,invitationId,this.user.email,new Date().toISOString()),this.log(invitation.org_id,this.user.id,'Invitation accepted',null,{role:invitation.role},true),this.stmt('DELETE FROM invitations WHERE id=? AND email=?',invitationId,this.user.email)]);if(!result[0].meta.changes&&!await this.one('SELECT user_id FROM memberships WHERE org_id=? AND user_id=?',invitation.org_id,this.user.id))throw new HttpError(404,'This invitation is unavailable or expired.');return {id:invitation.org_id};}
 async workspace(org:string){const organization=await this.context(org);const [companies,contacts,boards,members]=await Promise.all([this.rows('SELECT c.id,c.name,c.email,c.phone,c.address,c.notes,c.version,(SELECT COUNT(*) FROM tickets t WHERE t.org_id=c.org_id AND t.company_id=c.id) ticketCount FROM companies c WHERE c.org_id=? ORDER BY c.name',org),this.rows('SELECT c.id,c.company_id companyId,c.name,c.email,c.phone,c.title,c.version,p.name company FROM contacts c JOIN companies p ON p.org_id=c.org_id AND p.id=c.company_id WHERE c.org_id=? ORDER BY c.name',org),this.rows<Board & {statuses:string}>('SELECT id,name,description,statuses,version FROM boards WHERE org_id=? ORDER BY name',org),this.rows('SELECT u.id,u.name,u.email,m.role FROM memberships m JOIN users u ON u.id=m.user_id WHERE m.org_id=? ORDER BY u.name',org)]);const settings=await this.rows<{boardId:string;labels:string}>('SELECT board_id boardId,labels FROM board_settings WHERE org_id=?',org);return {organization,companies,contacts,boards:boards.map(b=>({...b,statuses:JSON.parse(b.statuses),priorityLabels:JSON.parse(settings.find(s=>s.boardId===b.id)?.labels??'{}')})),members};}
 async listTickets(org:string,url:URL){await this.context(org);const page=z.coerce.number().int().min(0).max(100000).parse(url.searchParams.get('page')??0),q=(url.searchParams.get('q')??'').trim().slice(0,200),view=url.searchParams.get('view')??'open',board=url.searchParams.get('board'),company=url.searchParams.get('company'),priority=url.searchParams.get('priority');const where=['t.org_id=?'];const args:unknown[]=[org];if(view!=='all'&&view!=='waiting')where.push('t.closed=0');if(view==='mine'){where.push('t.assignee_id=?');args.push(this.user.id)}if(view==='unassigned')where.push('t.assignee_id IS NULL');if(view==='critical')where.push("t.priority='Critical'");if(view==='waiting')where.push("t.closed=0 AND t.status IN ('Waiting on Customer','Waiting on Vendor')");if(board){where.push('t.board_id=?');args.push(board)}if(company){where.push('t.company_id=?');args.push(company)}if(priority){where.push('t.priority=?');args.push(z.enum(priorities).parse(priority))}if(q){where.push(`(instr(lower(CAST(t.id AS TEXT)||' '||t.title||' '||t.description||' '||c.name||' '||COALESCE(u.name,'')),lower(?))>0 OR EXISTS(SELECT 1 FROM ticket_notes n WHERE n.org_id=t.org_id AND n.ticket_id=t.id AND instr(lower(n.body),lower(?))>0))`);args.push(q,q)}const base=TICKET_SQL+' WHERE '+where.join(' AND ');const order=url.searchParams.get('sort')==='priority'?"CASE t.priority WHEN 'Critical' THEN 0 WHEN 'High' THEN 1 WHEN 'Normal' THEN 2 ELSE 3 END,t.id DESC":'t.id DESC';const [total,tickets,summary]=await Promise.all([this.one<{total:number}>(`SELECT COUNT(*) total FROM (${base})`,...args),this.rows(base+' ORDER BY '+order+' LIMIT 12 OFFSET ?',...args,page*12),this.one(`SELECT COALESCE(SUM(closed=0),0) open,COALESCE(SUM(closed=0 AND assignee_id IS NULL),0) unassigned,COALESCE(SUM(closed=0 AND priority='Critical'),0) critical,COALESCE(SUM(closed=0 AND status IN ('Waiting on Customer','Waiting on Vendor')),0) waiting,COALESCE(SUM(closed=0 AND assignee_id=?),0) mine FROM tickets WHERE org_id=?`,this.user.id,org)]);return {tickets,total:total?.total??0,page,pageSize:12,summary};}
 async ticket(org:string,ticketId:string|number){await this.context(org);const n=z.coerce.number().int().positive().parse(ticketId),ticket=await this.one<TicketRow>(TICKET_SQL+' WHERE t.org_id=? AND t.id=?',org,n);if(!ticket)throw new HttpError(404,'Ticket not found.');const [notes,activity]=await Promise.all([this.rows('SELECT n.id,n.body,n.at,u.name author FROM ticket_notes n JOIN users u ON u.id=n.author_id WHERE n.org_id=? AND n.ticket_id=? ORDER BY n.at',org,n),this.rows('SELECT a.id,a.entity_id entityId,a.action,a.before,a.after,a.at,u.name author FROM audit_events a JOIN users u ON u.id=a.author_id WHERE a.org_id=? AND a.entity_id=? ORDER BY a.at DESC',org,'ticket:'+n)]);return {...ticket,notes,activity};}
 async references(org:string,p:{companyId:string;contactId:string|null;boardId:string;assigneeId:string|null;status?:string}){if(!await this.one('SELECT id FROM companies WHERE org_id=? AND id=?',org,p.companyId))throw new HttpError(400,'Choose a company in this organization.');if(p.contactId&&!await this.one('SELECT id FROM contacts WHERE org_id=? AND id=? AND company_id=?',org,p.contactId,p.companyId))throw new HttpError(400,'The contact must belong to the selected company.');if(p.assigneeId&&!await this.one('SELECT user_id FROM memberships WHERE org_id=? AND user_id=?',org,p.assigneeId))throw new HttpError(400,'Choose an organization member.');const b=await this.one<{statuses:string}>('SELECT statuses FROM boards WHERE org_id=? AND id=?',org,p.boardId);if(!b)throw new HttpError(400,'Choose a board in this organization.');const statuses:Board['statuses']=JSON.parse(b.statuses),status=statuses.find(s=>s.name===(p.status??statuses.find(s=>!s.closed)?.name));if(!status)throw new HttpError(400,'Choose a status from the selected board.');return status;}
 async writableTicket(org:string,n:number){const merged=await this.one<{target_id:number}>("SELECT target_id FROM ticket_relations WHERE org_id=? AND ticket_id=? AND kind='merge'",org,n);if(merged)throw new HttpError(409,'This ticket was merged into #'+merged.target_id+'. Open that ticket to continue.');}
 async notify(org:string,userId:string|null,title:string,ticketId:number|null){if(userId)await this.stmt('INSERT INTO notifications(id,org_id,user_id,ticket_id,title,at) VALUES(?,?,?,?,?,?)',crypto.randomUUID(),org,userId,ticketId,title,new Date().toISOString()).run();}
 async createTicket(org:string,payload:unknown){await this.context(org,'tickets:write');const id=await this.createTicketRecord(org,payload);return this.ticket(org,id);}
 protected async createTicketRecord(org:string,payload:unknown){
  const input=ticketInput.parse(payload);if(payload&&typeof payload==='object'&&!Object.hasOwn(payload,'assigneeId')){const defaults=await this.one<{default_member_id:string|null}>('SELECT default_member_id FROM board_settings WHERE org_id=? AND board_id=?',org,input.boardId);input.assigneeId=defaults?.default_member_id??null;}const initial=await this.references(org,input);if(input.parentId){const parent=await this.ticket(org,input.parentId);if(parent.companyId!==input.companyId)throw new HttpError(400,'Child tickets must share their parent company.');if(await this.one("SELECT ticket_id FROM ticket_relations WHERE org_id=? AND ticket_id=? AND kind='merge'",org,parent.id))throw new HttpError(409,'Choose an unmerged parent.');}
  const plan=await planAutomation(this,org,['Ticket created'],{...input,status:initial.name}),p=ticketInput.parse(plan.values),status=await this.references(org,p),at=new Date().toISOString(),marker=crypto.randomUUID(),sla=await slaDeadlines(this,org,p.priority,at,p.boardId);
  const stmts=[this.stmt('INSERT INTO tickets(org_id,id,title,description,company_id,contact_id,board_id,assignee_id,status,closed,priority,created,updated,response_due,resolution_due,resolved) SELECT ?,COALESCE(MAX(id),1000)+1,?,?,?,?,?,?,?,?,?,?,?,?,?,? FROM tickets WHERE org_id=? RETURNING id',org,p.title,p.description,p.companyId,p.contactId,p.boardId,p.assigneeId,status.name,Number(status.closed),p.priority,at,at,sla.responseDue,sla.resolutionDue,status.closed?at:null,org),this.stmt("INSERT INTO audit_events(id,org_id,entity_id,action,author_id,at) SELECT ?,?,'ticket:'||MAX(id),'Ticket created',?,? FROM tickets WHERE org_id=?",marker,org,this.user.id,at,org)];
  if(input.parentId)stmts.push(this.stmt("INSERT INTO ticket_relations(org_id,ticket_id,target_id,kind) SELECT ?,MAX(id),?,'parent' FROM tickets WHERE org_id=?",org,input.parentId,org));
  if(plan.rule)stmts.push(this.stmt("INSERT INTO audit_events(id,org_id,entity_id,action,author_id,at) SELECT ?,?,'ticket:'||MAX(id),?,?,? FROM tickets WHERE org_id=?",crypto.randomUUID(),org,'Automation: '+plan.rule.name,this.user.id,at,org));
  if(plan.note)stmts.push(this.stmt('INSERT INTO ticket_notes(id,org_id,ticket_id,author_id,body,at) SELECT ?,?,MAX(id),?,?,? FROM tickets WHERE org_id=?',crypto.randomUUID(),org,this.user.id,plan.note,at,org));
  if(p.assigneeId)stmts.push(this.stmt('INSERT INTO notifications(id,org_id,user_id,ticket_id,title,at) SELECT ?,?,?,MAX(id),?,? FROM tickets WHERE org_id=?',crypto.randomUUID(),org,p.assigneeId,'Ticket assigned: '+p.title,at,org));
  stmts.push(...await automationEffects(this,org,'new',plan.effects,marker,p));const result=await this.db.batch(stmts);return (result[0].results[0] as {id:number}).id;
 }
 async updateTicket(org:string,ticketId:string,payload:unknown,timed?:{event:string;key:string}){
  await this.context(org,'tickets:write');const patch=ticketUpdate.parse(payload),before=await this.ticket(org,ticketId);if(await this.one("SELECT ticket_id FROM ticket_relations WHERE org_id=? AND ticket_id=? AND kind='merge'",org,before.id))throw new HttpError(409,'This ticket was merged. Update the destination ticket.');
  if(before.version!==patch.version)throw new HttpError(409,'This ticket changed. Reload it before saving.');
  const events=['Ticket updated'];if(patch.status&&patch.status!==before.status)events.push('Status changed');if(patch.priority&&patch.priority!==before.priority)events.push('Priority changed');
  if(patch.status&&(await this.references(org,{...before,...patch})).closed&&!before.closed)events.push('Ticket closed');const plan=await planAutomation(this,org,timed?[timed.event]:events,{...before,...patch}),p=plan.values as typeof before,status=await this.references(org,p),at=new Date().toISOString(),marker=crypto.randomUUID(),sla=(p.priority!==before.priority||p.boardId!==before.boardId)?await slaDeadlines(this,org,p.priority,before.created,p.boardId):{responseDue:before.responseDue,resolutionDue:before.resolutionDue};
  if(p.companyId!==before.companyId&&await this.one('SELECT ticket_id FROM ticket_relations WHERE org_id=? AND (ticket_id=? OR target_id=?)',org,before.id,before.id))throw new HttpError(409,'Remove ticket relationships before changing the company.');
  if(p.companyId!==before.companyId&&await this.one('SELECT ticket_id FROM ticket_links WHERE org_id=? AND ticket_id=? AND (asset_id IS NOT NULL OR project_id IS NOT NULL)',org,before.id))throw new HttpError(409,'Unlink projects and assets before changing the ticket company.');
  const stmts=[this.stmt(`UPDATE tickets SET title=?,description=?,company_id=?,contact_id=?,board_id=?,assignee_id=?,status=?,closed=?,priority=?,updated=?,response_due=?,resolution_due=?,resolved=?,version=version+1 WHERE org_id=? AND id=? AND version=? ${timed?'AND NOT EXISTS(SELECT 1 FROM automation_events WHERE org_id=? AND key=?)':''}`,p.title,p.description,p.companyId,p.contactId,p.boardId,p.assigneeId,status.name,Number(status.closed),p.priority,at,sla.responseDue,sla.resolutionDue,status.closed?(before.resolved??at):null,org,before.id,patch.version,...(timed?[org,timed.key]:[])),this.log(org,'ticket:'+before.id,'Ticket updated',Object.fromEntries(Object.keys(patch).filter(k=>k!=='version').map(k=>[k,before[k as keyof typeof before]])),patch,true,marker)];
  if(plan.rule)stmts.push(this.log(org,'ticket:'+before.id,'Automation: '+plan.rule.name,null,plan.rule,true));
  if(plan.note)stmts.push(this.stmt('INSERT INTO ticket_notes(id,org_id,ticket_id,author_id,body,at) SELECT ?,?,?,?,?,? WHERE changes()>0',crypto.randomUUID(),org,before.id,this.user.id,plan.note,at));
  if(p.assigneeId&&p.assigneeId!==before.assigneeId)stmts.push(this.stmt('INSERT INTO notifications(id,org_id,user_id,ticket_id,title,at) SELECT ?,?,?,?,?,? WHERE changes()>0',crypto.randomUUID(),org,p.assigneeId,before.id,'Ticket assigned: '+p.title,at));
  if(timed)stmts.push(this.stmt('INSERT INTO automation_events(org_id,key,at) SELECT ?,?,? WHERE EXISTS(SELECT 1 FROM audit_events WHERE id=?)',org,timed.key,at,marker));stmts.push(...await automationEffects(this,org,before.id,plan.effects,marker,p));const result=await this.db.batch(stmts);if(!result[0].meta.changes)throw new HttpError(409,'This ticket changed. Reload it before saving.');return this.ticket(org,ticketId);
 }
 async addNote(org:string,ticketId:string,payload:unknown){await this.context(org,'tickets:write');await this.writableTicket(org,Number(ticketId));const p=z.object({body:z.string().trim().min(1).max(10000),mentionIds:z.array(id).max(20).default([]),version:z.number().int().positive()}).strict().parse(payload),before=await this.ticket(org,ticketId);for(const member of p.mentionIds)if(!await this.one('SELECT user_id FROM memberships WHERE org_id=? AND user_id=?',org,member))throw new HttpError(400,'Mention an organization member.');const at=new Date().toISOString(),marker=crypto.randomUUID();const result=await this.db.batch([this.stmt('INSERT INTO ticket_notes(id,org_id,ticket_id,author_id,body,at) SELECT ?,org_id,id,?,?,? FROM tickets WHERE org_id=? AND id=? AND version=?',crypto.randomUUID(),this.user.id,p.body,at,org,before.id,p.version),this.stmt('UPDATE tickets SET updated=?,version=version+1 WHERE org_id=? AND id=? AND version=? AND changes()>0',at,org,before.id,p.version),this.log(org,'ticket:'+before.id,'Internal note added',null,null,true,marker),...[...new Set(p.mentionIds)].map(member=>this.stmt('INSERT INTO notifications(id,org_id,user_id,ticket_id,title,at) SELECT ?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM audit_events WHERE id=?)',crypto.randomUUID(),org,member,before.id,'Mentioned in ticket #'+before.id,at,marker))]);if(!result[0].meta.changes)throw new HttpError(409,'This ticket changed. Reload it before adding your note.');return this.ticket(org,ticketId);}
 async directory(org:string,resource:string,payload:unknown,recordId?:string){const kind=resource as 'companies'|'contacts'|'boards';if(!['companies','contacts','boards'].includes(kind))throw new HttpError(404,'Not found.');await this.context(org,kind==='boards'?'boards:write':'directory:write');const p=(kind==='companies'?companyInput:kind==='contacts'?contactInput:boardInput).parse(payload);if(kind==='contacts'){const c=p as z.infer<typeof contactInput>;if(!await this.one('SELECT id FROM companies WHERE org_id=? AND id=?',org,c.companyId))throw new HttpError(400,'Choose a company in this organization.');if(recordId&&await this.one('SELECT id FROM tickets WHERE org_id=? AND contact_id=? AND company_id<>? LIMIT 1',org,recordId,c.companyId))throw new HttpError(409,'This contact is used by tickets at another company. Keep its company or update those tickets first.');}if(kind==='boards'&&recordId){const rules=await this.rows<{actions:string;board_id:string}>('SELECT actions,board_id FROM automations WHERE org_id=?',org);for(const rule of rules){const action=JSON.parse(rule.actions);if((action.boardId||rule.board_id)===recordId&&action.status&&!(p as z.infer<typeof boardInput>).statuses.some(x=>x.name===action.status))throw new HttpError(409,'This status is used by an automation. Update that rule first.');}const used=await this.rows<{status:string;closed:number}>('SELECT DISTINCT status,closed FROM tickets WHERE org_id=? AND board_id=?',org,recordId);for(const s of used){const next=(p as z.infer<typeof boardInput>).statuses.find(x=>x.name===s.status);if(!next||Number(next.closed)!==s.closed)throw new HttpError(409,'A status used by existing tickets cannot be removed or change its open/closed meaning.');}}
 const map:Record<string,string>={companyId:'company_id'},entries=Object.entries(p).filter(([k])=>k!=='version').map(([k,v])=>[map[k]??k,k==='statuses'?JSON.stringify(v):v] as [string,unknown]),rid=recordId??crypto.randomUUID();if(recordId){if(!p.version)throw new HttpError(400,'A record version is required.');const before=await this.one(`SELECT * FROM ${kind} WHERE org_id=? AND id=?`,org,rid);if(!before)throw new HttpError(404,'Record not found.');const result=await this.db.batch([this.stmt(`UPDATE ${kind} SET ${entries.map(([k])=>k+'=?').join(',')},version=version+1 WHERE org_id=? AND id=? AND version=?`,...entries.map(([,v])=>v),org,rid,p.version),this.log(org,kind+':'+rid,'Updated '+kind,before,p,true)]);if(!result[0].meta.changes)throw new HttpError(409,'This record changed. Reload it before saving.');}else{await this.db.batch([this.stmt(`INSERT INTO ${kind}(id,org_id,${entries.map(([k])=>k).join(',')}) VALUES(${Array(entries.length+2).fill('?').join(',')})`,rid,org,...entries.map(([,v])=>v)),this.log(org,kind+':'+rid,'Created '+kind,null,p)]);}return {id:rid};}
 async team(org:string){await this.context(org,'team:write');return {invitations:await this.rows("SELECT i.id,i.email,i.role,i.expires,COALESCE(d.status,'pending') deliveryStatus,COALESCE(d.error,'') deliveryError FROM invitations i LEFT JOIN invitation_deliveries d ON d.invitation_id=i.id WHERE i.org_id=? ORDER BY i.email",org)};}
 async invite(org:string,payload:unknown){const actor=await this.context(org,'team:write');const p=z.object({email:z.string().trim().email().max(254).transform(e=>e.toLowerCase()),role:z.enum(['Administrator','Manager','Engineer','Viewer'])}).strict().parse(payload);if(actor.role!=='Owner'&&p.role==='Administrator')throw new HttpError(403,'Only the owner can appoint administrators.');if(await this.one('SELECT u.id FROM users u JOIN memberships m ON m.user_id=u.id WHERE m.org_id=? AND u.email=?',org,p.email))throw new HttpError(409,'This person is already a member.');const rid=crypto.randomUUID(),expires=new Date(Date.now()+7*86400000).toISOString();await this.db.batch([this.stmt('INSERT INTO invitations(id,org_id,email,role,expires) VALUES(?,?,?,?,?) ON CONFLICT(org_id,email) DO UPDATE SET id=excluded.id,role=excluded.role,expires=excluded.expires',rid,org,p.email,p.role,expires),this.log(org,'team','Invitation prepared',null,p)]);return {ok:true,id:rid};}
 async revokeInvite(org:string,invitationId:string){await this.context(org,'team:write');await this.db.batch([this.stmt('DELETE FROM invitations WHERE org_id=? AND id=?',org,invitationId),this.log(org,'team','Invitation revoked',null,{invitationId},true)]);return {ok:true};}
 async role(org:string,userId:string,payload:unknown){const actor=await this.context(org,'team:write'),p=z.object({role:z.enum(['Administrator','Manager','Engineer','Viewer'])}).strict().parse(payload);const target=await this.one<{role:Role}>('SELECT role FROM memberships WHERE org_id=? AND user_id=?',org,userId);if(!target)throw new HttpError(404,'Member not found.');if(target.role==='Owner'||userId===this.user.id)throw new HttpError(403,'You cannot change this membership.');if(actor.role!=='Owner'&&(target.role==='Administrator'||p.role==='Administrator'))throw new HttpError(403,'Only the owner can manage administrators.');await this.db.batch([this.stmt('UPDATE memberships SET role=? WHERE org_id=? AND user_id=?',p.role,org,userId),this.stmt('DELETE FROM role_assignments WHERE org_id=? AND user_id=?',org,userId),this.log(org,'member:'+userId,'Member role changed',target,p)]);return {ok:true};}
 async organization(org:string,payload:unknown){await this.context(org,'organization:write');const p=z.object({name}).strict().parse(payload);await this.db.batch([this.stmt('UPDATE organizations SET name=? WHERE id=?',p.name,org),this.log(org,org,'Organization renamed',null,p)]);return {ok:true};}
 async audit(org:string,url:URL){await this.context(org,'team:write');const page=z.coerce.number().int().min(0).max(100000).parse(url.searchParams.get('page')??0);return {events:await this.rows('SELECT a.id,a.entity_id entityId,a.action,a.before,a.after,a.at,u.name author FROM audit_events a JOIN users u ON u.id=a.author_id WHERE a.org_id=? ORDER BY a.at DESC LIMIT 30 OFFSET ?',org,page*30),total:(await this.one<{total:number}>('SELECT COUNT(*) total FROM audit_events WHERE org_id=?',org))?.total??0};}
}
