import {z} from 'zod';
import {env} from 'cloudflare:workers';
import {Completion} from './completion';
import {HttpError} from './service';

const runtime=()=>env as unknown as {RESEND_API_KEY?:string;QUEVIAN_EMAIL_FROM?:string;QUEVIAN_INBOUND_DOMAIN?:string;RESEND_WEBHOOK_SECRET?:string;DB:D1Database};
const now=()=>new Date().toISOString();
const address=(v:string)=>{const match=v.trim().match(/^(?:[^<>]*<)?([^<>\s]+@[^<>\s]+)>?$/);return z.string().email().max(254).parse(match?.[1]??'').toLowerCase()};
const domain=()=>{const d=runtime().QUEVIAN_INBOUND_DOMAIN?.trim().toLowerCase();if(!d||!/^([a-z0-9-]+\.)+[a-z]{2,}$/.test(d))throw new HttpError(503,'An incoming email domain needs to be configured.');return d};
const randomAddress=()=>crypto.randomUUID().replaceAll('-','')+'@'+domain();
async function provider(path:string,init:RequestInit={}){const key=runtime().RESEND_API_KEY;if(!key)throw new HttpError(503,'Email delivery is not configured.');const r=await fetch('https://api.resend.com'+path,{...init,redirect:'error',signal:AbortSignal.timeout(12000),headers:{Authorization:'Bearer '+key,'Content-Type':'application/json',...init.headers}});if(!r.ok)throw new HttpError(502,'The email provider could not complete this request.');return r.json();}
type Thread={address:string;org_id:string;ticket_id:number;company_id:string;requester:string;message_id:string};
type Outbox={id:string;org_id:string;ticket_id:number;company_id:string;status:string;created:string;updated:string;payload:string;provider_id:string|null};
const finalStates=['delivered','bounced','complained','failed'];
export class TicketMail extends Completion {
 async mailSettings(org:string){await this.context(org,'team:write');return {sendingConfigured:!!(runtime().RESEND_API_KEY&&runtime().QUEVIAN_EMAIL_FROM),receivingConfigured:!!(runtime().QUEVIAN_INBOUND_DOMAIN&&runtime().RESEND_WEBHOOK_SECRET),domain:runtime().QUEVIAN_INBOUND_DOMAIN??'',routes:await this.rows('SELECT address,company_id companyId,board_id boardId,enabled FROM mail_routes WHERE org_id=?',org),deliveries:await this.rows('SELECT id,ticket_id ticketId,recipient,status,error,updated FROM mail_outbox WHERE org_id=? ORDER BY created DESC LIMIT 50',org)}}
 async mailRouteSave(org:string,payload:unknown){await this.context(org,'team:write');const p=z.object({companyId:z.string(),boardId:z.string()}).strict().parse(payload);await this.company(org,p.companyId);if(!await this.one('SELECT id FROM boards WHERE org_id=? AND id=?',org,p.boardId))throw new HttpError(400,'Choose a board in this organization.');const inbox=randomAddress();await this.db.batch([this.stmt('INSERT INTO mail_routes(address,org_id,company_id,board_id) VALUES(?,?,?,?)',inbox,org,p.companyId,p.boardId),this.log(org,'mail','Support inbox created',null,{address:inbox,companyId:p.companyId,boardId:p.boardId})]);return {address:inbox};}
 async mailRouteToggle(org:string,payload:unknown){await this.context(org,'team:write');const p=z.object({address:z.string().email(),enabled:z.boolean()}).strict().parse(payload);await this.db.batch([this.stmt('UPDATE mail_routes SET enabled=? WHERE org_id=? AND address=?',Number(p.enabled),org,p.address),this.log(org,'mail','Support inbox updated',null,p)]);return {ok:true};}
 async mailHistory(org:string,id:number){await this.ticket(org,id);const t=await this.one<Thread>('SELECT * FROM mail_threads WHERE org_id=? AND ticket_id=?',org,id);const ticket=await this.ticket(org,id);return {recipient:t&&t.company_id===ticket.companyId?t.requester:ticket.contactId?(await this.one<{email:string}>('SELECT email FROM contacts WHERE org_id=? AND company_id=? AND id=?',org,ticket.companyId,ticket.contactId))?.email??'':'',deliveries:await this.rows('SELECT id,status,error,updated FROM mail_outbox WHERE org_id=? AND ticket_id=? ORDER BY created',org,id)}}
 async emailReply(org:string,id:number,payload:unknown){await this.context(org,'tickets:write');const p=z.object({body:z.string().trim().min(1).max(10000),requestId:z.string().uuid()}).strict().parse(payload);const previous=await this.one<Outbox>('SELECT * FROM mail_outbox WHERE id=?',p.requestId);if(previous){if(previous.org_id!==org||previous.ticket_id!==id)throw new HttpError(409,'This reply request is already in use.');if(JSON.parse(previous.payload).text!==p.body)throw new HttpError(409,'This request belongs to a different reply. Reload before continuing.');await this.dispatchMail(org,p.requestId);return {ok:true,...await this.mailHistory(org,id)}}
 if(!runtime().RESEND_API_KEY||!runtime().QUEVIAN_EMAIL_FROM||!runtime().RESEND_WEBHOOK_SECRET)throw new HttpError(503,'Support email setup is incomplete. Use Post to portal until it is connected.');domain();const ticket=await this.ticket(org,id);let thread=await this.one<Thread>('SELECT * FROM mail_threads WHERE org_id=? AND ticket_id=?',org,id);if(thread&&thread.company_id!==ticket.companyId)throw new HttpError(409,'The ticket company changed. Its original email thread cannot be used.');
 let newThread=false;if(!thread){const contact=ticket.contactId?await this.one<{email:string}>('SELECT email FROM contacts WHERE org_id=? AND company_id=? AND id=?',org,ticket.companyId,ticket.contactId):null;if(!contact?.email)throw new HttpError(400,'Select a ticket contact with an email address first.');thread={address:randomAddress(),org_id:org,ticket_id:id,company_id:ticket.companyId,requester:address(contact.email),message_id:''};newThread=true;}
 const t=thread,at=now(),data={from:runtime().QUEVIAN_EMAIL_FROM,to:[t.requester],reply_to:t.address,subject:('Re: [Quevian #'+id+'] '+ticket.title).replace(/[\r\n]/g,' '),text:p.body,...(t.message_id?{headers:{'In-Reply-To':t.message_id,'References':t.message_id}}:{})};
 await this.reply(org,id,{body:p.body},undefined,{companyId:t.company_id,messageId:p.requestId,statements:marker=>[...(newThread?[this.stmt('INSERT INTO mail_threads(address,org_id,ticket_id,company_id,requester,message_id) SELECT ?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM audit_events WHERE id=?)',t.address,org,id,t.company_id,t.requester,t.message_id,marker)]:[]),this.stmt("INSERT INTO mail_outbox(id,org_id,ticket_id,company_id,recipient,payload,status,created,updated) SELECT ?,?,?,?,?,?,'pending',?,? WHERE EXISTS(SELECT 1 FROM audit_events WHERE id=?)",p.requestId,org,id,t.company_id,t.requester,JSON.stringify(data),at,at,marker)]});await this.dispatchMail(org,p.requestId);return {ok:true,...await this.mailHistory(org,id)};
 }
 async dispatchMail(org:string,id:string){await this.context(org,'tickets:write');const row=await this.one<Outbox>('SELECT * FROM mail_outbox WHERE org_id=? AND id=?',org,id);if(!row)throw new HttpError(404,'Delivery not found.');const ticket=await this.ticket(org,row.ticket_id);if(ticket.companyId!==row.company_id)throw new HttpError(409,'The ticket company changed. Delivery is blocked.');if(['accepted',...finalStates].includes(row.status))return {status:row.status};if(Date.now()-Date.parse(row.created)>23*3600000){await this.stmt("UPDATE mail_outbox SET status='review',error='Delivery is uncertain and the safe retry window has expired. Check Resend before sending a new reply.' WHERE org_id=? AND id=?",org,id).run();return {status:'review'}}
 const at=now(),claim=await this.one("UPDATE mail_outbox SET status='sending',attempts=attempts+1,updated=? WHERE org_id=? AND id=? AND (status IN ('pending','retry') OR (status='sending' AND updated<?)) RETURNING id",at,org,id,new Date(Date.now()-60000).toISOString());if(!claim)return {status:row.status};
 try{const result=await provider('/emails',{method:'POST',headers:{'Idempotency-Key':'quevian-ticket/'+id},body:row.payload}) as {id?:string};if(!result.id)throw new Error('No provider ID');await this.stmt("UPDATE mail_outbox SET provider_id=?,status='accepted',error='',updated=? WHERE org_id=? AND id=?",result.id,now(),org,id).run();await this.reconcileDelivery(result.id);return {status:'accepted'};}catch{await this.stmt("UPDATE mail_outbox SET status='retry',error='Delivery was not confirmed. Retry this saved message; do not post it again.',updated=? WHERE org_id=? AND id=?",now(),org,id).run();return {status:'retry'}}
 }
 async reconcileDelivery(providerId:string){const event=await this.one<{status:string;at:string}>("SELECT status,at FROM mail_events WHERE provider_id=? ORDER BY CASE status WHEN 'complained' THEN 5 WHEN 'bounced' THEN 4 WHEN 'failed' THEN 3 WHEN 'delivered' THEN 2 ELSE 1 END DESC,at DESC LIMIT 1",providerId);if(event)await this.stmt('UPDATE mail_outbox SET status=?,updated=?,error=? WHERE provider_id=?',event.status,event.at,['bounced','complained','failed'].includes(event.status)?'The email provider reported '+event.status+'.':'',providerId).run();}
 async receiveMail(providerId:string){if(await this.one('SELECT provider_id FROM mail_inbound WHERE provider_id=?',providerId))return {duplicate:true};const raw=await provider('/emails/receiving/'+encodeURIComponent(z.string().uuid().parse(providerId))) as {from:string;to:string[];subject:string;text:string|null;html:string|null;message_id:string;headers:Record<string,string>;attachments?:unknown[]};const sender=address(raw.from),recipients=raw.to.map(address);if(recipients.length>50)throw new HttpError(400,'Too many recipients.');const hs=Object.fromEntries(Object.entries(raw.headers??{}).map(([k,v])=>[k.toLowerCase(),v]));if((hs['auto-submitted']&&hs['auto-submitted']!=='no')||hs['x-auto-response-suppress']||/^mailer-daemon@|^postmaster@/i.test(sender))return {ignored:'automatic-message'};
 const threads:Thread[]=[];const routes:{address:string;org_id:string;company_id:string;board_id:string}[]=[];for(const recipient of recipients){const t=await this.one<Thread>('SELECT * FROM mail_threads WHERE address=?',recipient);if(t)threads.push(t);const r=await this.one<{address:string;org_id:string;company_id:string;board_id:string}>('SELECT * FROM mail_routes WHERE address=? AND enabled=1',recipient);if(r)routes.push(r)}if(threads.length+routes.length!==1)return {ignored:'unknown-or-ambiguous-recipient'};
 const text=raw.text?.trim()||raw.html?.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,'').replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').trim()||'(Email contained no text)';const body=(text.slice(0,9000)+(text.length>9000?'\n[Email text truncated; original retained in Resend.]':'')+(raw.attachments?.length?'\n[This email included attachments. Files are retained in Resend and have not been imported into Quevian.]':''));const at=now();
 const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(sender)))).map(b=>b.toString(16).padStart(2,'0')).join('');const actor=new TicketMail(this.db,{id:'mail:'+hash,email:sender,name:sender+' (email)'});await actor.register();
 try{if(threads.length){const t=threads[0];if(sender!==t.requester)return {ignored:'sender-does-not-match-thread'};const ticket=await this.one<{company_id:string}>('SELECT company_id FROM tickets WHERE org_id=? AND id=?',t.org_id,t.ticket_id);if(ticket?.company_id!==t.company_id)return {ignored:'ticket-company-changed'};await actor.reply(t.org_id,t.ticket_id,{body},undefined,{incoming:true,companyId:t.company_id,messageId:crypto.randomUUID(),statements:marker=>[actor.stmt('INSERT INTO mail_inbound(provider_id,org_id,ticket_id,at) SELECT ?,?,?,? WHERE EXISTS(SELECT 1 FROM audit_events WHERE id=?)',providerId,t.org_id,t.ticket_id,at,marker),actor.stmt('UPDATE mail_threads SET message_id=? WHERE address=? AND EXISTS(SELECT 1 FROM audit_events WHERE id=?)',cleanMessageId(raw.message_id),t.address,marker)]});return {ticketId:t.ticket_id};}
 const r=routes[0],contacts=await actor.rows<{id:string}>('SELECT id FROM contacts WHERE org_id=? AND company_id=? AND lower(email)=? LIMIT 2',r.org_id,r.company_id,sender);const ticketId=await actor.createTicketRecord(r.org_id,{title:(raw.subject?.trim()||'Email support request').slice(0,180),description:body,companyId:r.company_id,boardId:r.board_id,contactId:contacts.length===1?contacts[0].id:null},{providerId,address:randomAddress(),requester:sender,messageId:cleanMessageId(raw.message_id)});return {ticketId};
 }catch(e){if(await this.one('SELECT provider_id FROM mail_inbound WHERE provider_id=?',providerId))return {duplicate:true};throw e;}
 }
}
function cleanMessageId(value:string){return typeof value==='string'&&value.length<=500&&!/[\r\n]/.test(value)?value:''}
export async function verifiedWebhook(request:Request){const secret=runtime().RESEND_WEBHOOK_SECRET;if(!secret)throw new HttpError(503,'Email webhooks are not configured.');const reader=request.body?.getReader();if(!reader)throw new HttpError(400,'Missing webhook body.');const chunks:Uint8Array[]=[];let size=0;while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>262144){await reader.cancel();throw new HttpError(413,'Webhook too large.')}chunks.push(value)}const bytes=new Uint8Array(size);let offset=0;for(const c of chunks){bytes.set(c,offset);offset+=c.length}const raw=new TextDecoder().decode(bytes),id=request.headers.get('svix-id'),ts=request.headers.get('svix-timestamp'),sig=request.headers.get('svix-signature');if(!id||!ts||!sig||!/^\d+$/.test(ts)||Math.abs(Date.now()/1000-Number(ts))>300)throw new HttpError(401,'Invalid webhook signature.');let valid=false;try{const key=await crypto.subtle.importKey('raw',Uint8Array.from(atob(secret.replace(/^whsec_/,'')),c=>c.charCodeAt(0)),{name:'HMAC',hash:'SHA-256'},false,['verify']);for(const v of sig.split(' ')){if(!v.startsWith('v1,'))continue;if(await crypto.subtle.verify('HMAC',key,Uint8Array.from(atob(v.slice(3)),c=>c.charCodeAt(0)),new TextEncoder().encode(id+'.'+ts+'.'+raw)))valid=true}}catch{valid=false}if(!valid)throw new HttpError(401,'Invalid webhook signature.');return {id,event:z.object({type:z.string(),created_at:z.string().datetime(),data:z.object({email_id:z.string().uuid()}).passthrough()}).parse(JSON.parse(raw))};}
export async function handleMailWebhook(request:Request){const {id,event}=await verifiedWebhook(request);const s=new TicketMail(runtime().DB,{id:'mail-service',email:'mail-service@quevian.invalid',name:'Email service'});if(event.type==='email.received')return s.receiveMail(event.data.email_id);const states:Record<string,string>={'email.delivered':'delivered','email.bounced':'bounced','email.complained':'complained','email.failed':'failed','email.delivery_delayed':'delayed'};const status=states[event.type];if(status){await s.stmt('INSERT INTO mail_events(id,provider_id,status,at) VALUES(?,?,?,?) ON CONFLICT(id) DO NOTHING',id,event.data.email_id,status,event.created_at).run();await s.reconcileDelivery(event.data.email_id)}return {ok:true};}
