import test from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
const state={env:{},headers:new Headers(),user:null,calls:[]};globalThis.__emailAuthTest=state;
const fake={getUser:async()=>({data:{user:state.user},error:null}),signUp:async p=>{state.calls.push(['signup',p]);return {data:{user:state.user},error:null}},signInWithPassword:async p=>{state.calls.push(['login',p]);return {data:{user:state.user},error:state.loginError??null}},resetPasswordForEmail:async()=>({error:null}),resend:async()=>({error:null}),verifyOtp:async p=>{state.calls.push(['verify',p]);return {error:state.verifyError??null}},updateUser:async p=>{state.calls.push(['update',p]);return {error:null}},signOut:async()=>({error:null})};state.fake=fake;
const compiled=await build({stdin:{contents:"export * as route from './app/api/auth/[action]/route.ts';export * as auth from './lib/auth/server.ts';export {Service} from './lib/server/service.ts';export {sendInvitation} from './lib/server/invitation-mail.ts';export {mutationGuard} from './lib/server/files.ts';",resolveDir:process.cwd(),sourcefile:'test.ts'},bundle:true,format:'esm',platform:'node',write:false,plugins:[{name:'runtime',setup(b){b.onResolve({filter:/^(cloudflare:workers|next\/headers|next\/navigation|@supabase\/ssr)$/},a=>({path:a.path,namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},a=>({loader:'js',contents:a.path==='cloudflare:workers'?'export const env=globalThis.__emailAuthTest.env':a.path==='next/headers'?'export async function headers(){return globalThis.__emailAuthTest.headers};export async function cookies(){return {getAll:()=>[],set(){}}}':a.path==='next/navigation'?'export function redirect(path){throw new Error("redirect:"+path)}':'export function createServerClient(){return {auth:globalThis.__emailAuthTest.fake}}'}))}}]});
const {route,auth,Service,sendInvitation,mutationGuard}=await import('data:text/javascript;base64,'+Buffer.from(compiled.outputFiles[0].text).toString('base64'));
class D1{constructor(){this.sql=new DatabaseSync(':memory:');this.sql.exec('PRAGMA foreign_keys=ON');for(const file of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())this.sql.exec(readFileSync('drizzle/'+file,'utf8'))}prepare(sql){const db=this;return {sql,args:[],bind(...a){this.args=a;return this},async first(){return db.sql.prepare(sql).get(...this.args)??null},async all(){return {results:db.sql.prepare(sql).all(...this.args),meta:{changes:Number(db.sql.prepare('SELECT changes() n').get().n)}}},async run(){const r=db.sql.prepare(sql).run(...this.args);return {meta:{changes:Number(r.changes)}}}}}async batch(list){this.sql.exec('BEGIN');try{const r=[];for(const s of list)r.push(/RETURNING/i.test(s.sql)?await s.all():await s.run());this.sql.exec('COMMIT');return r}catch(e){this.sql.exec('ROLLBACK');throw e}}}
function setup(){const db=new D1();Object.assign(state.env,{DB:db,SUPABASE_URL:'https://project.supabase.co',SUPABASE_PUBLISHABLE_KEY:'test-key',QUEVIAN_SITE_URL:'https://quevian.test',QUEVIAN_EMAIL_AUTH_ENABLED:'true',RESEND_API_KEY:undefined,QUEVIAN_EMAIL_FROM:undefined});state.headers=new Headers();state.user=null;state.calls=[];state.loginError=null;state.verifyError=null;return db}
const verified={id:'verified-subject',email:'person@example.com',email_confirmed_at:'2026-09-08T00:00:00Z',is_anonymous:false,user_metadata:{full_name:'Person'}};
const post=(action,data,headers={})=>route.POST(new Request('https://quevian.test/api/auth/'+action,{method:'POST',headers:{'Content-Type':'application/json','X-QueuePilot-Request':'1',Origin:'https://quevian.test',...headers},body:JSON.stringify(data)}),{params:Promise.resolve({action})});
test('auth actions fail closed when disabled and reject cross-site mutations',async()=>{const db=setup();try{state.env.QUEVIAN_EMAIL_AUTH_ENABLED='false';assert.equal((await post('signup',{email:'person@example.com'})).status,503);state.env.QUEVIAN_EMAIL_AUTH_ENABLED='true';assert.equal((await post('login',{email:'person@example.com',password:'whatever'},{Origin:'https://attacker.test'})).status,403);assert.equal(state.calls.length,0)}finally{db.sql.close()}});
test('signup validates passwords before contacting the provider and preserves safe destinations',async()=>{const db=setup();try{assert.equal((await post('signup',{email:'person@example.com',password:'short',name:'Person'})).status,400);assert.equal(state.calls.length,0);assert.equal((await post('signup',{email:'person@example.com',password:'a-long-unique-password',name:'Person',next:'https://attacker.test'})).status,200);assert.equal(state.calls[0][1].options.emailRedirectTo,'https://quevian.test/auth/confirm?next=%2Fapp')}finally{db.sql.close()}});
test('login rejects unverified and anonymous identities and sanitizes redirects',async()=>{const db=setup();try{state.user={...verified,email_confirmed_at:null};assert.equal((await post('login',{email:verified.email,password:'test'})).status,403);state.user={...verified,is_anonymous:true};assert.equal((await post('login',{email:verified.email,password:'test'})).status,403);state.user=verified;assert.equal((await (await post('login',{email:verified.email,password:'test',next:'//attacker.test'})).json()).next,'/app')}finally{db.sql.close()}});
test('password reset requires verified provider identity; invalid confirmation is rejected',async()=>{const db=setup();try{assert.equal((await post('reset',{password:'my-new-long-password'})).status,401);state.user=verified;assert.equal((await post('reset',{password:'my-new-long-password'})).status,200);state.verifyError={code:'otp_expired'};assert.equal((await post('confirm',{token_hash:'a'.repeat(30),type:'recovery'})).status,400);assert.equal((await post('confirm',{token_hash:'a'.repeat(30),type:'admin'})).status,400)}finally{db.sql.close()}});
test('recovery replies are generic and email-specific throttles are enforced',async()=>{const db=setup();try{for(let i=0;i<5;i++){const r=await post('forgot',{email:'person@example.com'});assert.equal(r.status,200);assert.match((await r.json()).message,/If an account exists/)}assert.equal((await post('forgot',{email:'person@example.com'})).status,429)}finally{db.sql.close()}});
test('matching email alone cannot take over an existing workspace; explicit dual-account linking preserves its identity',async()=>{const db=setup();try{const legacy={id:'legacy-owner',email:verified.email,name:'Original owner'};const s=new Service(db,legacy);const org=await s.createOrganization({name:'Existing company'});state.user=verified;assert.equal((await auth.accountIdentity()).id,'supabase:'+verified.id);assert.equal((await post('link',{})).status,403);state.headers=new Headers({'oai-authenticated-user-id':legacy.id,'oai-authenticated-user-email':'different@example.com'});assert.equal((await post('link',{})).status,403);state.headers.set('oai-authenticated-user-email',legacy.email);assert.equal((await post('link',{})).status,200);assert.equal((await auth.accountIdentity()).id,legacy.id);assert.equal((await new Service(db,await auth.accountIdentity()).context(org.id)).role,'Owner');assert.equal((await post('link',{})).status,200)}finally{db.sql.close()}});
test('safe return paths permit invitations but block external URLs and reserved auth routes',()=>{assert.equal(auth.safeNext('/invite/abc-123'),'/invite/abc-123');for(const path of ['https://attacker.test','//attacker.test','/\\attacker.test','/signin-with-chatgpt','/api/account','/logout'])assert.equal(auth.safeNext(path),'/app')});
test('reissued invitations invalidate old links and delivery fails honestly without a sender',async()=>{const db=setup();try{const owner=new Service(db,{id:'owner',email:'owner@example.com',name:'Owner'}),org=(await owner.createOrganization({name:'Team'})).id;const old=await owner.invite(org,{email:verified.email,role:'Engineer'});const current=await owner.invite(org,{email:verified.email,role:'Viewer'});assert.notEqual(old.id,current.id);const member=new Service(db,{id:'member',email:verified.email,name:'Member'});await assert.rejects(member.acceptInvitation({invitationId:old.id}),e=>e.status===404);assert.equal((await sendInvitation(owner,org,current.id)).status,'not_configured');await member.acceptInvitation({invitationId:current.id});assert.equal((await member.context(org)).role,'Viewer');await assert.rejects(sendInvitation(owner,org,current.id),e=>e.status===404)}finally{db.sql.close()}});
test('mail retries are throttled and provider acceptance is not sent twice',async()=>{const db=setup(),originalFetch=globalThis.fetch;let sends=0;try{state.env.RESEND_API_KEY='test-only';state.env.QUEVIAN_EMAIL_FROM='Quevian <no-reply@example.com>';const owner=new Service(db,{id:'owner',email:'owner@example.com',name:'Owner'}),org=(await owner.createOrganization({name:'Team'})).id;const invitation=await owner.invite(org,{email:verified.email,role:'Engineer'});globalThis.fetch=async(_url,opts)=>{sends++;assert.equal(opts.headers['Idempotency-Key'],'quevian-invite/'+invitation.id);return Response.json({error:'temporary'},{status:503})};assert.equal((await sendInvitation(owner,org,invitation.id)).status,'failed');await assert.rejects(sendInvitation(owner,org,invitation.id),e=>e.status===429);db.sql.prepare("UPDATE invitation_deliveries SET updated='2020-01-01'").run();globalThis.fetch=async()=>{sends++;return Response.json({id:'email-id'})};assert.equal((await sendInvitation(owner,org,invitation.id)).status,'sent');assert.equal((await sendInvitation(owner,org,invitation.id)).status,'sent');assert.equal(sends,2);const outsider=new Service(db,{id:'outsider',email:'outsider@example.com',name:'Outsider'});await assert.rejects(sendInvitation(outsider,org,invitation.id),e=>e.status===403)}finally{globalThis.fetch=originalFetch;db.sql.close()}});

test('current and legacy request headers pass while cross-site and unmarked requests fail',()=>{
 const req=h=>new Request('https://quevian.test/api/workspace/demo/invitations',{method:'POST',headers:h});
 for(const key of ['X-Quevian-Request','X-QueuePilot-Request']){
  assert.doesNotThrow(()=>mutationGuard(req({[key]:'1',Origin:'https://quevian.test','Sec-Fetch-Site':'same-origin'})));
  assert.throws(()=>mutationGuard(req({[key]:'1',Origin:'https://attacker.test'})),e=>e.status===403);
  assert.throws(()=>mutationGuard(req({[key]:'1','Sec-Fetch-Site':'cross-site'})),e=>e.status===403);
 }
 assert.throws(()=>mutationGuard(req({Origin:'https://quevian.test'})),e=>e.status===403);
 assert.throws(()=>mutationGuard(req({'X-Quevian-Request':'0'})),e=>e.status===403);
});

test('new verified signup proceeds through login, organization setup, a board, a ticket and accepted staff invitation',async()=>{
 const db=setup();try{
 const signup=await post('signup',{email:verified.email,password:'a-unique-long-password',name:'New owner'});assert.equal(signup.status,200);
 assert.equal(await auth.verifiedUser(),null);
 assert.equal((await post('confirm',{token_hash:'valid-confirmation-token-hash',type:'signup',next:'/app'})).status,200);
 state.user=verified;assert.equal((await post('login',{email:verified.email,password:'a-unique-long-password'})).status,200);
 const owner=new Service(db,await auth.accountIdentity()),org=(await owner.createOrganization({name:'Signup journey'})).id;
 const company=(await owner.directory(org,'companies',{name:'First customer'})).id;
 const board=(await owner.directory(org,'boards',{name:'New board',statuses:[{name:'Queued',closed:false},{name:'Done',closed:true}]})).id;
 const ticket=await owner.createTicket(org,{title:'First real workflow',companyId:company,boardId:board});assert.equal(ticket.status,'Queued');
 const i=await owner.invite(org,{email:'staff@example.com',role:'Engineer'});
 const staff=new Service(db,{id:'supabase:staff',email:'staff@example.com',name:'Staff'});await staff.account();await assert.rejects(staff.ticket(org,ticket.id),e=>e.status===403);
 await staff.acceptInvitation({invitationId:i.id});assert.equal((await staff.ticket(org,ticket.id)).title,'First real workflow');
 }finally{db.sql.close()}
});
