import test,{after} from 'node:test';
import {pathToFileURL} from 'node:url';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {createHmac} from 'node:crypto';
import {mkdtempSync,writeFileSync,rmSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {D1} from './support/database.mjs';
import {restoreBackup} from '../scripts/restore-backup.mjs';
const state={env:{},calls:[],objects:new Map(),incoming:null,subscription:null};globalThis.__launchCompletion=state;
const compiled=await build({stdin:{contents:"export * from './lib/server/ticket-mail';export * from './lib/server/email-files';export * from './lib/server/subscriptions';export * from './lib/server/recovery';export * from './lib/server/jobs';export * from './lib/server/member-access';export * from './lib/server/privacy';",resolveDir:process.cwd()},bundle:true,format:'esm',platform:'node',write:false,plugins:[{name:'runtime',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'runtime',namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},()=>({contents:'export const env=globalThis.__launchCompletion.env;'}))}}]});
const bundleDir=mkdtempSync(join(tmpdir(),'quevian-launch-suite-'));const bundleFile=join(bundleDir,'app.mjs');writeFileSync(bundleFile,compiled.outputFiles[0].text);const app=await import(pathToFileURL(bundleFile).href);after(()=>rmSync(bundleDir,{recursive:true,force:true}));
function bucket(){return {async put(key,value){state.objects.set(key,typeof value==='string'?new TextEncoder().encode(value):new Uint8Array(value))},async get(key){const bytes=state.objects.get(key);return bytes?{size:bytes.length,body:bytes,async arrayBuffer(){return bytes.slice().buffer},async text(){return new TextDecoder().decode(bytes)}}:null},async delete(key){state.objects.delete(key)}}}
const owner={id:'launch-owner',name:'Owner',email:'owner@example.com'},outsider={id:'launch-other',name:'Other',email:'other@example.com'};
async function setup(){state.calls=[];state.objects.clear();for(const key of Object.keys(state.env))delete state.env[key];Object.assign(state.env,{DB:undefined,BUCKET:bucket(),RESEND_API_KEY:'send-test',RESEND_RECEIVING_API_KEY:'receive-test',RESEND_WEBHOOK_SECRET:'whsec_test',QUEVIAN_SUPPORT_EMAIL_FROM:'Support <support@example.com>',QUEVIAN_INBOUND_DOMAIN:'inbound.example.com',STRIPE_SECRET_KEY:'sk_test_fake',STRIPE_WEBHOOK_SECRET:'stripe-signing-test',STRIPE_MONTHLY_PRICE_ID:'price_monthly',STRIPE_ANNUAL_PRICE_ID:'price_annual',STRIPE_PORTAL_CONFIGURATION_ID:'bpc_fixture',QUEVIAN_BILLING_ENABLED:'true',QUEVIAN_LEGAL_APPROVED:'true',QUEVIAN_SITE_URL:'https://quevian.example',QUEVIAN_JOB_TOKEN:'a'.repeat(48)});
 const db=new D1();state.env.DB=db;const a=new app.TicketMail(db,owner),b=new app.TicketMail(db,outsider),org=(await a.createOrganization({name:'Alpha'})).id,foreign=(await b.createOrganization({name:'Beta'})).id,company=(await a.directory(org,'companies',{name:'Customer'})).id,board=(await a.workspace(org)).boards[0].id,contact=(await a.directory(org,'contacts',{name:'Requester',companyId:company,email:'requester@example.com'})).id,ticket=await a.createTicket(org,{title:'Attachment test',companyId:company,boardId:board,contactId:contact});
 state.subscription={id:'sub_fixture',customer:'cus_fixture',status:'active',metadata:{quevian_org:org},cancel_at_period_end:false,items:{data:[{id:'si_fixture',quantity:1,current_period_end:Math.floor(Date.now()/1000)+86400,price:{id:'price_monthly'}}]}};
 globalThis.fetch=async(url,init={})=>{url=String(url);state.calls.push({url,init});if(url.startsWith('https://files.resend.com/'))return new Response('hello');if(url.includes('/attachments/'))return Response.json({download_url:'https://files.resend.com/attachment',size:5});if(url.includes('/emails/receiving/'))return Response.json(state.incoming);if(url==='https://api.resend.com/emails')return Response.json({id:crypto.randomUUID()});if(url.includes('/prices/'))return Response.json({active:true,currency:'usd',unit_amount:url.endsWith('annual')?18000:1900,recurring:{interval:url.endsWith('annual')?'year':'month',interval_count:1}});if(url.endsWith('/customers'))return Response.json({id:'cus_fixture'});if(url.endsWith('/checkout/sessions'))return Response.json({id:'cs_fixture',url:'https://checkout.stripe.com/c/pay/fixture',expires_at:Math.floor(Date.now()/1000)+1800});if(url.includes('/checkout/sessions/'))return Response.json({id:'cs_fixture',status:'open',url:'https://checkout.stripe.com/c/pay/fixture'});if(url.includes('/billing_portal/sessions'))return Response.json({url:'https://billing.stripe.com/p/session/fixture'});if(url.includes('/subscriptions/'))return Response.json(state.subscription);throw new Error('Unexpected request '+url)};
 return {db,a,b,org,foreign,company,board,contact,ticket};
}
const status=n=>e=>e.status===n;
async function attachment(x,{visibility='Customer',org=x.org,ticketId=x.ticket.id,name='report.txt',content='hello'}={}){const id=crypto.randomUUID(),key=org+'/'+ticketId+'/'+id;await state.env.BUCKET.put(key,content);await x.a.stmt('INSERT INTO attachments(id,org_id,ticket_id,name,size,object_key,at,visibility,author_id) VALUES(?,?,?,?,?,?,?,?,?)',id,org,ticketId,name,content.length,key,new Date().toISOString(),visibility,owner.id).run();return id}
async function activeSubscription(x,seats=1){await x.a.stmt("INSERT INTO workspace_subscriptions(org_id,customer_id,subscription_id,status,seats,price_id,updated) VALUES(?,?,?,'active',?,?,?)",x.org,'cus_fixture','sub_fixture',seats,'price_monthly',new Date().toISOString()).run()}
test('checkout requires owner, consent, server prices and enough seats',async()=>{const x=await setup();try{await assert.rejects(app.startCheckout(x.b,x.org,{interval:'monthly',seats:1,acceptedTerms:true}),status(403));await assert.rejects(app.startCheckout(x.a,x.org,{interval:'monthly',seats:1,acceptedTerms:false}));const r=await app.startCheckout(x.a,x.org,{interval:'monthly',seats:2,acceptedTerms:true});assert.match(r.url,/checkout.stripe.com/);const call=state.calls.find(x=>x.url.endsWith('/checkout/sessions'));const p=call.init.body;assert.equal(p.get('line_items[0][price]'),'price_monthly');assert.equal(p.get('line_items[0][quantity]'),'2');assert.equal(p.get('consent_collection[terms_of_service]'),'required');assert.match(p.get('success_url'),/org=/);assert.equal((await app.subscriptionStatus(x.a,x.org)).status,'pending')}finally{x.db.close()}});
test('repeating checkout reuses the open session and prevents multiple subscriptions',async()=>{const x=await setup();try{const p={interval:'monthly',seats:1,acceptedTerms:true};await app.startCheckout(x.a,x.org,p);await app.startCheckout(x.a,x.org,p);assert.equal(state.calls.filter(x=>x.url.endsWith('/checkout/sessions')).length,1);await assert.rejects(app.startCheckout(x.a,x.org,{...p,seats:2}),status(409));await x.a.stmt("UPDATE workspace_subscriptions SET status='active',subscription_id='sub_fixture'").run();await assert.rejects(app.startCheckout(x.a,x.org,p),status(409))}finally{x.db.close()}});
test('billing remains disabled until legal and account setup are approved',async()=>{const x=await setup();try{state.env.QUEVIAN_LEGAL_APPROVED='false';assert.equal(app.billingReady(),false);await assert.rejects(app.startCheckout(x.a,x.org,{interval:'monthly',seats:1,acceptedTerms:true}),status(503));assert.equal(state.calls.length,0)}finally{x.db.close()}});
test('mismatched provider price cannot be charged',async()=>{const x=await setup();try{globalThis.fetch=async()=>Response.json({active:true,currency:'usd',unit_amount:99900,recurring:{interval:'month',interval_count:1}});await assert.rejects(app.startCheckout(x.a,x.org,{interval:'monthly',seats:1,acceptedTerms:true}),status(503));assert.equal(await x.a.one('SELECT org_id FROM workspace_subscriptions'),null)}finally{x.db.close()}});
function billingEvent(object,overrides={}){const event={id:overrides.id??'evt_fixture',type:'customer.subscription.updated',created:Math.floor(Date.now()/1000),data:{object}},body=JSON.stringify(event),t=overrides.t??String(Math.floor(Date.now()/1000)),sig=createHmac('sha256','stripe-signing-test').update(t+'.'+body).digest('hex');return new Request('https://quevian.example/api/webhooks/stripe',{method:'POST',headers:{'stripe-signature':'t='+t+',v1='+(overrides.sig??sig)},body})}
test('signed billing events use canonical state and deduplicate',async()=>{const x=await setup();try{await x.a.stmt("INSERT INTO workspace_subscriptions(org_id,customer_id,status,updated) VALUES(?,?,'pending',?)",x.org,'cus_fixture',new Date().toISOString()).run();assert.equal((await app.billingWebhook(billingEvent({id:'sub_fixture',status:'unpaid'}),x.db)).ok,true);assert.equal((await app.subscriptionStatus(x.a,x.org)).status,'active');assert.equal((await app.billingWebhook(billingEvent({id:'sub_fixture'}),x.db)).duplicate,true);await assert.rejects(app.billingWebhook(billingEvent({id:'sub_fixture'},{sig:'0'.repeat(64)}),x.db),status(401));await assert.rejects(app.billingWebhook(billingEvent({id:'sub_fixture'},{t:'1'}),x.db),status(401))}finally{x.db.close()}});
test('billing state cannot cross organizations or roll back to an older event',async()=>{const x=await setup();try{await activeSubscription(x);await x.a.stmt('UPDATE workspace_subscriptions SET event_created=200 WHERE org_id=?',x.org).run();await app.syncSubscription(x.a,{...state.subscription,status:'unpaid'},100);assert.equal((await app.subscriptionStatus(x.a,x.org)).status,'active');await assert.rejects(app.syncSubscription(x.a,{...state.subscription,metadata:{quevian_org:x.foreign}},201),status(409));assert.equal((await app.subscriptionStatus(x.b,x.foreign)).hasSubscription,false)}finally{x.db.close()}});
test('paid access can be required without hiding existing records',async()=>{const x=await setup();try{state.env.QUEVIAN_BILLING_REQUIRED='true';await assert.rejects(app.requirePaidWorkspace(x.a,x.org),status(402));assert.equal((await x.a.ticket(x.org,x.ticket.id)).title,'Attachment test');await activeSubscription(x);await app.requirePaidWorkspace(x.a,x.org)}finally{x.db.close()}});
test('seat capacity is enforced atomically when inviting and restoring staff',async()=>{const x=await setup();try{await activeSubscription(x);await assert.rejects(x.a.invite(x.org,{email:'new@example.com',role:'Engineer'}),/subscription_seat_capacity/);await x.a.stmt('UPDATE workspace_subscriptions SET seats=2 WHERE org_id=?',x.org).run();await x.a.stmt("INSERT INTO memberships VALUES(?,?,'Engineer')",x.org,outsider.id).run();await app.setMemberAccess(x.a,x.org,outsider.id,{suspended:true});await x.a.stmt('UPDATE workspace_subscriptions SET seats=1 WHERE org_id=?',x.org).run();await assert.rejects(app.setMemberAccess(x.a,x.org,outsider.id,{suspended:false}),status(409));assert.equal((await app.subscriptionStatus(x.a,x.org)).usedSeats,1)}finally{x.db.close()}});
test('suspension revokes existing-session access while preserving history',async()=>{const x=await setup();try{await x.a.stmt("INSERT INTO memberships VALUES(?,?,'Engineer')",x.org,outsider.id).run();await x.b.context(x.org);await app.setMemberAccess(x.a,x.org,outsider.id,{suspended:true});await assert.rejects(x.b.context(x.org),status(403));await assert.rejects(x.b.ticket(x.org,x.ticket.id),status(403));assert.equal((await x.b.account()).organizations.some(o=>o.id===x.org),false);await assert.rejects(app.setMemberAccess(x.a,x.org,owner.id,{suspended:true}),status(403));await app.setMemberAccess(x.a,x.org,outsider.id,{suspended:false});await x.b.context(x.org)}finally{x.db.close()}});
test('outgoing attachments are explicit, immutable and customer-visible only',async()=>{const x=await setup();try{const visible=await attachment(x),internal=await attachment(x,{visibility:'Internal',content:'SECRET'});await assert.rejects(x.a.emailReply(x.org,x.ticket.id,{body:'Reply',requestId:crypto.randomUUID(),attachmentIds:[internal]}),status(400));await x.a.emailReply(x.org,x.ticket.id,{body:'Reply',requestId:crypto.randomUUID(),attachmentIds:[visible]});const sent=JSON.parse(state.calls.find(c=>c.url==='https://api.resend.com/emails').init.body);assert.deepEqual(sent.attachments,[{filename:'report.txt',content:Buffer.from('hello').toString('base64')}]);assert.equal(sent._files,undefined);assert.doesNotMatch(JSON.stringify(sent),/SECRET/)}finally{x.db.close()}});
test('a saved reply cannot silently change its attachment selection',async()=>{const x=await setup();try{const id=await attachment(x),requestId=crypto.randomUUID();await x.a.emailReply(x.org,x.ticket.id,{body:'Reply',requestId,attachmentIds:[id]});await assert.rejects(x.a.emailReply(x.org,x.ticket.id,{body:'Reply',requestId,attachmentIds:[]}),status(409))}finally{x.db.close()}});
test('incoming attachment imports are deduplicated and retain company boundaries',async()=>{const x=await setup();try{const route=await x.a.mailRouteSave(x.org,{companyId:x.company,boardId:x.board}),providerId=crypto.randomUUID();state.incoming={from:'requester@example.com',to:[route.address],subject:'Incoming',text:'See attachment',message_id:'<test@example.com>',headers:{},attachments:[{id:crypto.randomUUID(),filename:'hello.txt',size:5}]};const received=await x.a.receiveMail(providerId);await x.a.receiveMail(providerId);const files=await x.a.rows('SELECT * FROM attachments WHERE ticket_id=? AND org_id=?',received.ticketId,x.org);assert.equal(files.length,1);assert.equal(files[0].visibility,'Customer');assert.equal((await x.a.one('SELECT status FROM mail_attachment_imports')).status,'imported');assert.equal((await state.env.BUCKET.get(files[0].object_key)).size,5);assert.equal((await x.b.listTickets(x.foreign,new URL('https://test/?view=all'))).total,0)}finally{x.db.close()}});
test('attachment downloads reject private hosts, redirects and oversized bodies',async()=>{const x=await setup();try{await x.a.stmt('INSERT INTO mail_inbound VALUES(?,?,?,?)','email-id',x.org,x.ticket.id,new Date().toISOString()).run();for(const host of ['http://127.0.0.1/private','https://127.0.0.1/private','https://files.resend.com.evil.example/private']){const id=crypto.randomUUID();await app.queueEmailFiles(x.a,'email-id',[{id,filename:'test.txt',size:5}],owner.id);await app.importEmailFiles(x.a,async()=>({download_url:host}),'email-id');}assert.equal((await x.a.rows('SELECT * FROM attachments')).length,0);assert.equal(state.calls.length,0)}finally{x.db.close()}});
test('attachment transfers stop on redirects and declared-size overflow',async()=>{const x=await setup();try{await x.a.stmt('INSERT INTO mail_inbound VALUES(?,?,?,?)','email-transfer',x.org,x.ticket.id,new Date().toISOString()).run();for(const response of [()=>new Response(null,{status:302,headers:{location:'https://evil.example'}}),()=>new Response('too many bytes')]){await app.queueEmailFiles(x.a,'email-transfer',[{id:crypto.randomUUID(),filename:'test.txt',size:5}],owner.id);globalThis.fetch=async(url,init)=>{assert.equal(init.redirect,'manual');return response()};await app.importEmailFiles(x.a,async()=>({download_url:'https://files.resend.com/file'}),'email-transfer')}assert.equal((await x.a.rows('SELECT * FROM attachments')).length,0);assert.equal(state.objects.size,0)}finally{x.db.close()}});
test('incoming attachments follow existing merges and stop if a merge races the download',async()=>{const x=await setup();try{await x.a.stmt('INSERT INTO mail_inbound VALUES(?,?,?,?)','email-merge',x.org,x.ticket.id,new Date().toISOString()).run();const dest=await x.a.createTicket(x.org,{title:'Destination',companyId:x.company,boardId:x.board});await x.a.stmt("INSERT INTO ticket_relations VALUES(?,?,?,'merge')",x.org,x.ticket.id,dest.id).run();await app.queueEmailFiles(x.a,'email-merge',[{id:crypto.randomUUID(),filename:'test.txt',size:5}],owner.id);await app.importEmailFiles(x.a,async()=>({download_url:'https://files.resend.com/file'}),'email-merge');assert.equal((await x.a.one('SELECT ticket_id FROM attachments')).ticket_id,dest.id);assert.equal((await x.a.one('SELECT ticket_id FROM mail_attachment_imports')).ticket_id,dest.id);const final=await x.a.createTicket(x.org,{title:'Final',companyId:x.company,boardId:x.board});await app.queueEmailFiles(x.a,'email-merge',[{id:crypto.randomUUID(),filename:'second.txt',size:5}],owner.id);globalThis.fetch=async()=>{await x.a.stmt("INSERT INTO ticket_relations VALUES(?,?,?,'merge')",x.org,dest.id,final.id).run();return new Response('hello')};await app.importEmailFiles(x.a,async()=>({download_url:'https://files.resend.com/file'}),'email-merge');assert.equal((await x.a.rows('SELECT * FROM attachments')).length,1);assert.equal((await x.a.one("SELECT status FROM mail_attachment_imports WHERE name='second.txt'")).status,'review')}finally{x.db.close()}});
test('backup restores the real schema, records and file bytes in a separate directory',async()=>{const x=await setup(),dir=mkdtempSync(join(tmpdir(),'quevian-restore-'));try{await attachment(x);const info=await app.createBackup(x.db);assert.equal((await app.verifyBackup()).verified,true);const snapshot=JSON.parse(await (await state.env.BUCKET.get('_backups/'+info.id+'/manifest.json')).text());for(const file of snapshot.objects)writeFileSync(join(dir,file.sha256),new Uint8Array(await (await state.env.BUCKET.get(file.backupKey)).arrayBuffer()));const destination=join(dir,'restored.sqlite'),result=restoreBackup(snapshot,destination,dir);assert.equal(result.integrity,'ok');assert.equal(result.files,1);const restored=new DatabaseSync(destination);assert.equal(restored.prepare('SELECT title FROM tickets WHERE org_id=? AND id=?').get(x.org,x.ticket.id).title,'Attachment test');assert.equal(restored.prepare('PRAGMA foreign_key_check').all().length,0);restored.close();assert.equal(JSON.parse(readFileSync(destination+'.files/index.json','utf8')).length,1);await assert.rejects(async()=>restoreBackup(snapshot,destination,dir),/must not exist/)}finally{x.db.close();rmSync(dir,{recursive:true,force:true})}});
test('backup corruption is detected before declaring recovery verified',async()=>{const x=await setup();try{await attachment(x);const info=await app.createBackup(x.db);const manifest=JSON.parse(await (await state.env.BUCKET.get('_backups/'+info.id+'/manifest.json')).text());await state.env.BUCKET.put(manifest.objects[0].backupKey,'wrong');await assert.rejects(app.verifyBackup(),/checksum/)}finally{x.db.close()}});
test('owner exports exclude credentials, other companies and other organizations',async()=>{const x=await setup();try{await assert.rejects(app.organizationExport(x.b,x.org),status(403));const result=await (await app.organizationExport(x.a,x.org)).json();assert.equal(result.organization,x.org);assert.equal(result.tables.tickets.length,1);assert.equal(result.tables.auth_links,undefined);assert.equal(result.tables.mail_threads,undefined);assert.equal(result.tables.api_keys,undefined);assert.doesNotMatch(JSON.stringify(result),new RegExp(x.foreign))}finally{x.db.close()}});
test('deletion requires exact workspace confirmation and remains a reviewed request',async()=>{const x=await setup();try{await assert.rejects(app.requestDeletion(x.a,x.org,{confirmName:'Wrong'}),status(400));await app.requestDeletion(x.a,x.org,{confirmName:'Alpha'});await app.requestDeletion(x.a,x.org,{confirmName:'Alpha'});assert.equal((await app.privacyStatus(x.a,x.org)).requests.length,1);assert.ok(await x.a.ticket(x.org,x.ticket.id))}finally{x.db.close()}});
test('job authentication rejects missing, partial and incorrect credentials',async()=>{const x=await setup();try{for(const authorization of ['', 'Bearer '+ 'b'.repeat(48),'Bearer a'])await assert.rejects(app.authorizeJob(new Request('https://test',{headers:{authorization}})),status(401));await app.authorizeJob(new Request('https://test',{headers:{authorization:'Bearer '+'a'.repeat(48)}}))}finally{x.db.close()}});
test('maintenance records a durable result and respects an active lease',async()=>{const x=await setup();try{state.env.QUEVIAN_BILLING_ENABLED='false';const result=await app.runJob(x.db,'maintenance');assert.equal(result.ok,true);const row=await x.a.one("SELECT * FROM job_runs WHERE name='maintenance'");assert.equal(row.status,'ok');assert.ok(row.last_completed);await x.a.stmt("UPDATE job_runs SET lease_until=? WHERE name='maintenance'",Date.now()+60000).run();assert.equal((await app.runJob(x.db,'maintenance')).busy,true)}finally{x.db.close()}});

test('representative 10000-ticket searches stay scoped and paginate under concurrent reads',async()=>{const x=await setup();try{const insert=x.db.sql.prepare("INSERT INTO tickets(org_id,id,title,description,company_id,board_id,status,closed,priority,created,updated) VALUES(?,?,?,?,?,?,'New',0,'Normal',?,?)"),at=new Date().toISOString();x.db.sql.exec('BEGIN');for(let i=0;i<10000;i++)insert.run(x.org,2000+i,'Capacity request '+i,'Representative support ticket '+(i%100),x.company,x.board,at,at);x.db.sql.exec('COMMIT');const start=performance.now();const results=await Promise.all(Array.from({length:12},(_,i)=>x.a.listTickets(x.org,new URL('https://test/?view=all&q=Capacity&page='+i))));const elapsed=Math.round(performance.now()-start);assert.ok(results.every(r=>r.total===10000&&r.tickets.length<=r.pageSize));assert.equal((await x.b.listTickets(x.foreign,new URL('https://test/?view=all'))).total,0);console.log(JSON.stringify({benchmark:'local-sqlite',tickets:10000,concurrentReads:12,totalMs:elapsed}));}finally{x.db.close()}});
