import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {build} from 'esbuild';
const compiled=await build({stdin:{contents:"export * from './lib/server/request-limits';export * from './lib/server/ai-budget';",resolveDir:process.cwd()},bundle:true,format:'esm',platform:'node',write:false});
const {limitAccountRequest,reserveAiBudget,aiBudgetPlan}=await import('data:text/javascript;base64,'+Buffer.from(compiled.outputFiles[0].text).toString('base64'));
function database(){const sql=new DatabaseSync(':memory:');sql.exec('CREATE TABLE auth_limits(key TEXT PRIMARY KEY,window INTEGER NOT NULL,count INTEGER NOT NULL)');return {sql,prepare(query){return {args:[],bind(...args){this.args=args;return this},async first(){return sql.prepare(query).get(...this.args)??null}}}}}
const status=code=>error=>error.status===code;
test('file limits are account-scoped, atomic and bounded across concurrent calls',async()=>{const db=database();try{const results=await Promise.allSettled(Array.from({length:35},()=>limitAccountRequest(db,'account-one','upload',1000000)));assert.equal(results.filter(r=>r.status==='fulfilled').length,30);assert.equal(results.filter(r=>r.status==='rejected'&&r.reason.status===429).length,5);await limitAccountRequest(db,'account-two','upload',1000000);await limitAccountRequest(db,'account-one','upload',2000000);assert.equal(db.sql.prepare('SELECT COUNT(*) n FROM auth_limits').get().n,2);}finally{db.sql.close()}});
test('request-limit identifiers are hashed rather than interpolated into SQL',async()=>{const db=database();try{await limitAccountRequest(db,"x'); DROP TABLE auth_limits;--",'api',1000000);const row=db.sql.prepare('SELECT key FROM auth_limits').get();assert.match(row.key,/^[a-f0-9]{64}$/);}finally{db.sql.close()}});
test('AI defaults to no approved spending allowance',async()=>{assert.equal(aiBudgetPlan({}).ready,false);assert.equal(aiBudgetPlan({QUEVIAN_AI_MONTHLY_BUDGET_CENTS:'100',QUEVIAN_AI_REQUEST_RESERVATION_CENTS:'0'}).ready,false);await assert.rejects(reserveAiBudget({},{}),status(503));});
test('monthly reservations cannot overshoot through concurrent requests',async()=>{const db=database(),env={QUEVIAN_AI_MONTHLY_BUDGET_CENTS:'10',QUEVIAN_AI_REQUEST_RESERVATION_CENTS:'2'};try{const now=new Date('2026-09-22T12:00:00Z');const results=await Promise.allSettled(Array.from({length:20},()=>reserveAiBudget(db,env,now)));assert.equal(results.filter(r=>r.status==='fulfilled').length,5);assert.equal(db.sql.prepare('SELECT count FROM auth_limits ORDER BY window DESC LIMIT 1').get().count,10);await assert.rejects(reserveAiBudget(db,env,now),status(429));await reserveAiBudget(db,env,new Date('2026-10-01T00:00:00Z'));assert.equal(db.sql.prepare('SELECT count FROM auth_limits ORDER BY window DESC LIMIT 1').get().count,2);}finally{db.sql.close()}});
test('auth counter cleanup cannot erase the current monthly budget',async()=>{const db=database(),now=new Date('2026-09-22T12:00:00Z'),env={QUEVIAN_AI_MONTHLY_BUDGET_CENTS:'10',QUEVIAN_AI_REQUEST_RESERVATION_CENTS:'2'};try{await reserveAiBudget(db,env,now);db.sql.prepare('DELETE FROM auth_limits WHERE window<?').run(Math.floor(now.getTime()/900000)-4);assert.equal(db.sql.prepare('SELECT count FROM auth_limits ORDER BY window DESC LIMIT 1').get().count,2);}finally{db.sql.close()}});
test('reducing a budget below reserved usage blocks further calls',async()=>{const db=database(),now=new Date('2026-09-22T12:00:00Z');try{await reserveAiBudget(db,{QUEVIAN_AI_MONTHLY_BUDGET_CENTS:'10',QUEVIAN_AI_REQUEST_RESERVATION_CENTS:'8'},now);await assert.rejects(reserveAiBudget(db,{QUEVIAN_AI_MONTHLY_BUDGET_CENTS:'5',QUEVIAN_AI_REQUEST_RESERVATION_CENTS:'1'},now),status(429));assert.equal(db.sql.prepare('SELECT count FROM auth_limits ORDER BY window DESC LIMIT 1').get().count,8);}finally{db.sql.close()}});
