import test from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {D1} from './support/database.mjs';

globalThis.__auditEnv={};
const compiled=await build({stdin:{contents:"export {Advanced} from './lib/server/advanced'; export {fileRequest} from './lib/server/files';",resolveDir:process.cwd()},bundle:true,format:'esm',platform:'node',write:false,plugins:[{name:'runtime',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'env',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},()=>({contents:'export const env=globalThis.__auditEnv;',loader:'js'}))}}]});
const {Advanced:Service,fileRequest}=await import('data:text/javascript;base64,'+Buffer.from(compiled.outputFiles[0].text+'\n//# sourceURL=quevian-audit-services.mjs').toString('base64'));
const status=n=>e=>e.status===n;
async function setup(t){const db=new D1();t.after(()=>db.close());const owner=new Service(db,{id:'owner',email:'owner@example.test',name:'Owner'}),org=(await owner.createOrganization({name:'Audit organization'})).id;
 const a=(await owner.directory(org,'companies',{name:'Customer A'})).id,b=(await owner.directory(org,'companies',{name:'Customer B'})).id,board=(await owner.workspace(org)).boards[0].id;
 const ticket=await owner.createTicket(org,{title:'Private customer issue',companyId:a,boardId:board});
 const customer=new Service(db,{id:'customer',email:'customer@example.test',name:'Customer'});await owner.grantSave(org,{email:customer.user.email,companyId:a});await customer.portalAccount();
 const objects=new Map();globalThis.__auditEnv.BUCKET={put:async(key,bytes)=>objects.set(key,bytes),delete:async key=>objects.delete(key),get:async key=>objects.has(key)?{body:objects.get(key)}:null};
 return {db,owner,customer,org,a,b,board,ticket,objects};}
const upload=()=>{const form=new FormData();form.set('file',new File(['private attachment'],'customer.txt'));form.set('visibility','Customer');return new Request('https://quevian.test/api/files',{method:'POST',headers:{'X-Quevian-Request':'1'},body:form})};
test('saved views retain status and accept older views without a status',async t=>{const x=await setup(t),view={name:'Waiting',query:'',priority:'all',sort:'newest',view:'all',board:x.board,company:'all',layout:'kanban'};await x.owner.configSave(x.org,'saved-view',{...view,status:'Waiting on Customer'});await x.owner.configSave(x.org,'saved-view',{...view,name:'Legacy'});const {records}=await x.owner.configs(x.org,'saved-view');assert.equal(records.find(r=>r.name==='Waiting').status,'Waiting on Customer');assert.equal(records.find(r=>r.name==='Legacy').status,'')});
test('customer conversation cannot be transferred into another company portal',async t=>{const x=await setup(t);await x.customer.reply(x.org,x.ticket.id,{body:'Confidential reply'},x.a);const current=await x.owner.ticket(x.org,x.ticket.id);await assert.rejects(x.owner.updateTicket(x.org,String(current.id),{companyId:x.b,version:current.version}),status(409));assert.equal((await x.owner.ticket(x.org,current.id)).companyId,x.a)});
test('customer-visible attachments prevent company reassignment',async t=>{const x=await setup(t);await fileRequest(x.owner,upload(),x.org,x.ticket.id);const current=await x.owner.ticket(x.org,x.ticket.id);await assert.rejects(x.owner.updateTicket(x.org,String(current.id),{companyId:x.b,version:current.version}),status(409))});
test('unused tickets can still be assigned to the correct company',async t=>{const x=await setup(t);assert.equal((await x.owner.updateTicket(x.org,String(x.ticket.id),{companyId:x.b,version:1})).companyId,x.b)});
test('portal reply cannot follow a company change during authorization',async t=>{const x=await setup(t),original=x.customer.portalTicket.bind(x.customer);x.customer.portalTicket=async(...args)=>{const value=await original(...args);await x.owner.updateTicket(x.org,String(x.ticket.id),{companyId:x.b,version:1});return value};await assert.rejects(x.customer.reply(x.org,x.ticket.id,{body:'Must not reach B'},x.a),status(409));assert.equal((await x.owner.messages(x.org,x.ticket.id)).messages.length,0)});
test('portal reply checks grant at commit, including revocation during validation',async t=>{const x=await setup(t),original=x.customer.references.bind(x.customer);x.customer.references=async(...args)=>{const value=await original(...args);x.db.sql.prepare('DELETE FROM customer_grants WHERE org_id=?').run(x.org);return value};await assert.rejects(x.customer.reply(x.org,x.ticket.id,{body:'Revoked reply'},x.a),status(409));assert.equal((await x.owner.messages(x.org,x.ticket.id)).messages.length,0)});
test('successful file upload updates ticket version and history',async t=>{const x=await setup(t);await fileRequest(x.customer,upload(),x.org,x.ticket.id,undefined,x.a);assert.equal((await x.owner.ticket(x.org,x.ticket.id)).version,2);assert.equal(x.objects.size,1)});
test('upload is rolled back if its ticket changes company during object storage',async t=>{const x=await setup(t),put=globalThis.__auditEnv.BUCKET.put;globalThis.__auditEnv.BUCKET.put=async(...args)=>{await put(...args);await x.owner.updateTicket(x.org,String(x.ticket.id),{companyId:x.b,version:1})};await assert.rejects(fileRequest(x.customer,upload(),x.org,x.ticket.id,undefined,x.a),status(409));assert.equal(x.objects.size,0);assert.equal((await x.owner.rows('SELECT * FROM attachments')).length,0);assert.equal((await x.owner.rows("SELECT * FROM audit_events WHERE action='File uploaded'")).length,0)});
test('upload is rolled back if portal access is revoked during object storage',async t=>{const x=await setup(t),put=globalThis.__auditEnv.BUCKET.put;globalThis.__auditEnv.BUCKET.put=async(...args)=>{await put(...args);x.db.sql.prepare('DELETE FROM customer_grants WHERE org_id=?').run(x.org)};await assert.rejects(fileRequest(x.customer,upload(),x.org,x.ticket.id,undefined,x.a),status(409));assert.equal(x.objects.size,0)});
test('portal download checks access again after object storage returns',async t=>{const x=await setup(t),f=await fileRequest(x.owner,upload(),x.org,x.ticket.id),get=globalThis.__auditEnv.BUCKET.get;globalThis.__auditEnv.BUCKET.get=async(...args)=>{const value=await get(...args);x.db.sql.prepare('DELETE FROM customer_grants WHERE org_id=?').run(x.org);return value};await assert.rejects(fileRequest(x.customer,new Request('https://quevian.test/file'),x.org,x.ticket.id,f.id,x.a),status(403))});
test('portal sees the destination of merged tickets without internal notes',async t=>{const x=await setup(t),target=await x.owner.createTicket(x.org,{title:'Destination',companyId:x.a,boardId:x.board});await x.owner.relationSave(x.org,x.ticket.id,{kind:'merge',targetId:target.id,version:1,targetVersion:1});const result=await x.customer.portalTicket(x.org,x.a,x.ticket.id);assert.equal(result.mergedInto,target.id);assert.equal(result.notes,undefined)});
test('merged tickets cannot receive new project or equipment links',async t=>{const x=await setup(t),target=await x.owner.createTicket(x.org,{title:'Destination',companyId:x.a,boardId:x.board});await x.owner.relationSave(x.org,x.ticket.id,{kind:'merge',targetId:target.id,version:1,targetVersion:1});await assert.rejects(x.owner.linksSave(x.org,x.ticket.id,{projectId:null,assetId:null}),status(409))});
test('related-record writes reject a concurrent company transfer',async t=>{const x=await setup(t),batch=x.db.batch.bind(x.db);x.db.batch=async statements=>{x.db.batch=batch;x.db.sql.prepare('UPDATE tickets SET company_id=?,version=version+1 WHERE org_id=? AND id=?').run(x.b,x.org,x.ticket.id);return batch(statements)};await assert.rejects(x.owner.linksSave(x.org,x.ticket.id,{projectId:null,assetId:null}),status(409));assert.equal((await x.owner.rows('SELECT * FROM ticket_links')).length,0)});
