import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {join} from 'node:path';
import {createHmac} from 'node:crypto';
import {build} from 'esbuild';
const state={env:{},sent:[],incoming:{},fail:false};globalThis.__ticketMail=state;
const compiled=await build({entryPoints:['lib/server/ticket-mail.ts'],bundle:true,format:'esm',platform:'node',write:false,plugins:[{name:'runtime',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'env',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},()=>({contents:'export const env=globalThis.__ticketMail.env;',loader:'js'}))}}]});
const {TicketMail,verifiedWebhook,handleMailWebhook}=await import('data:text/javascript;base64,'+Buffer.from(compiled.outputFiles[0].text).toString('base64'));
const providerId='11111111-1111-4111-8111-111111111111';
globalThis.fetch=async(url,init={})=>{if(String(url).includes('/receiving/'))return Response.json(state.incoming);state.sent.push({url,init,payload:JSON.parse(init.body)});if(state.fail)throw new Error('Timeout');return Response.json({id:providerId})};
class D1 {
 constructor(path=':memory:'){this.sql=new DatabaseSync(path);this.sql.exec('PRAGMA foreign_keys=ON');}
 prepare(sql){const db=this;return {args:[],bind(...args){this.args=args;return this},async all(){const stmt=db.sql.prepare(sql);const results=stmt.all(...this.args);return {results,success:true,meta:{changes:Number(db.sql.prepare('SELECT changes() n').get().n)}}},async first(){return db.sql.prepare(sql).get(...this.args)??null},async run(){const r=db.sql.prepare(sql).run(...this.args);return {results:[],success:true,meta:{changes:Number(r.changes)}}},_sql:sql};}
 async batch(stmts){this.sql.exec('BEGIN');try{const results=[];for(const s of stmts){if(/\bRETURNING\b/i.test(s._sql))results.push(await s.all());else results.push(await s.run());}this.sql.exec('COMMIT');return results}catch(e){this.sql.exec('ROLLBACK');throw e}}
 migrate(){for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())this.sql.exec(readFileSync(join('drizzle',f),'utf8'));}
 close(){this.sql.close()}
}

const owner={id:'owner',name:'Owner',email:'owner@example.com'},other={id:'other',name:'Other',email:'other@example.com'};
async function setup(){state.sent=[];state.fail=false;state.incoming={from:'Customer <person@example.com>',to:[],subject:'Need help',text:'My printer stopped',message_id:'<incoming@example.com>',headers:{},attachments:[]};Object.assign(state.env,{RESEND_API_KEY:'test-only',QUEVIAN_EMAIL_FROM:'Quevian <support@example.com>',QUEVIAN_INBOUND_DOMAIN:'inbound.example.com',RESEND_WEBHOOK_SECRET:'whsec_'+Buffer.from('test-signing-secret').toString('base64')});const db=new D1();db.migrate();state.env.DB=db;const a=new TicketMail(db,owner),b=new TicketMail(db,other),org=(await a.createOrganization({name:'Alpha'})).id,foreign=(await b.createOrganization({name:'Beta'})).id,company=(await a.directory(org,'companies',{name:'Customer'})).id,board=(await a.workspace(org)).boards[0].id,contact=(await a.directory(org,'contacts',{name:'Person',companyId:company,email:'person@example.com'})).id;const inbox=await a.mailRouteSave(org,{companyId:company,boardId:board});state.incoming.to=[inbox.address];return {db,a,b,org,foreign,company,board,contact,inbox}}
const inboundId=()=>crypto.randomUUID();
async function makeTicket(x){return x.a.createTicket(x.org,{title:'Help',companyId:x.company,boardId:x.board,contactId:x.contact})}
function signed(type='email.received',eid=providerId,overrides={}){const body=JSON.stringify({type,created_at:new Date().toISOString(),data:{email_id:eid}}),id=overrides.id??'evt_'+crypto.randomUUID(),ts=overrides.ts??String(Math.floor(Date.now()/1000)),signature=createHmac('sha256',Buffer.from('test-signing-secret')).update(id+'.'+ts+'.'+body).digest('base64');return new Request('https://quevian.test/api/webhooks/resend',{method:'POST',headers:{'svix-id':id,'svix-timestamp':ts,'svix-signature':overrides.sig??'v1,'+signature},body:overrides.body??body})}
const status=n=>e=>e.status===n;
test('signed incoming email creates a ticket on the configured company and board',async()=>{const x=await setup();const r=await handleMailWebhook(signed());const t=await x.a.ticket(x.org,r.ticketId);assert.equal(t.companyId,x.company);assert.equal(t.boardId,x.board);assert.equal(t.contactId,x.contact);assert.equal(t.description,'My printer stopped');assert.equal((await x.b.listTickets(x.foreign,new URL('https://test/?view=all'))).total,0)});
test('duplicate incoming emails create one ticket',async()=>{const x=await setup();await x.a.receiveMail(providerId);assert.equal((await x.a.receiveMail(providerId)).duplicate,true);assert.equal((await x.a.listTickets(x.org,new URL('https://test/?view=all'))).total,1)});
test('reply address appends to the existing ticket without trusting subject ticket numbers',async()=>{const x=await setup();await x.a.receiveMail(providerId);const t=await x.a.one('SELECT * FROM mail_threads');state.incoming.to=[t.address];state.incoming.subject='Re: #999999';state.incoming.text='More information';await x.a.receiveMail(inboundId());const m=await x.a.messages(x.org,t.ticket_id);assert.equal(m.messages.length,1);assert.equal(m.messages[0].kind,'Customer');assert.equal(m.messages[0].body,'More information');assert.equal((await x.a.ticket(x.org,t.ticket_id)).responded,null)});
test('sender mismatch cannot append to an existing ticket',async()=>{const x=await setup();await x.a.receiveMail(providerId);const t=await x.a.one('SELECT * FROM mail_threads');state.incoming.to=[t.address];state.incoming.from='intruder@example.com';assert.equal((await x.a.receiveMail(inboundId())).ignored,'sender-does-not-match-thread');assert.equal((await x.a.messages(x.org,t.ticket_id)).messages.length,0)});
test('unknown inboxes create no ticket',async()=>{const x=await setup();state.incoming.to=['unknown@inbound.example.com'];assert.equal((await x.a.receiveMail(providerId)).ignored,'unknown-or-ambiguous-recipient');assert.equal((await x.a.listTickets(x.org,new URL('https://test/?view=all'))).total,0)});
test('ambiguous multiple inbox recipients do not duplicate or cross-route mail',async()=>{const x=await setup();const next=await x.a.mailRouteSave(x.org,{companyId:x.company,boardId:x.board});state.incoming.to.push(next.address);assert.equal((await x.a.receiveMail(providerId)).ignored,'unknown-or-ambiguous-recipient')});
test('disabled inboxes stop new tickets',async()=>{const x=await setup();await x.a.mailRouteToggle(x.org,{address:x.inbox.address,enabled:false});assert.equal((await x.a.receiveMail(providerId)).ignored,'unknown-or-ambiguous-recipient')});
test('automatic replies do not loop into new tickets',async()=>{const x=await setup();state.incoming.headers={'Auto-Submitted':'auto-replied'};assert.equal((await x.a.receiveMail(providerId)).ignored,'automatic-message')});
test('inbound attachments are disclosed and never silently represented as imported',async()=>{const x=await setup();state.incoming.attachments=[{id:'file'}];const r=await x.a.receiveMail(providerId);assert.match((await x.a.ticket(x.org,r.ticketId)).description,/have not been imported/) });
test('other organizations cannot configure or inspect the inbox',async()=>{const x=await setup();await assert.rejects(x.b.mailSettings(x.org),status(403));await assert.rejects(x.b.mailRouteSave(x.org,{companyId:x.company,boardId:x.board}),status(403))});
test('cross-organization board and company references fail',async()=>{const x=await setup();const company=(await x.b.directory(x.foreign,'companies',{name:'Other customer'})).id;await assert.rejects(x.a.mailRouteSave(x.org,{companyId:company,boardId:x.board}),status(400));const board=(await x.b.workspace(x.foreign)).boards[0].id;await assert.rejects(x.a.mailRouteSave(x.org,{companyId:x.company,boardId:board}),status(400))});
test('sending stores one public reply and emails only its text to the ticket contact',async()=>{const x=await setup();const t=await makeTicket(x);await x.a.addNote(x.org,String(t.id),{body:'INTERNAL SECRET',version:t.version});await x.a.emailReply(x.org,t.id,{body:'Public update',requestId:crypto.randomUUID()});assert.equal(state.sent.length,1);assert.deepEqual(state.sent[0].payload.to,['person@example.com']);assert.equal(state.sent[0].payload.text,'Public update');assert.doesNotMatch(JSON.stringify(state.sent[0]),/INTERNAL SECRET/);assert.equal((await x.a.messages(x.org,t.id)).messages.length,1);assert.equal((await x.a.mailHistory(x.org,t.id)).deliveries[0].status,'accepted')});
test('same request ID prevents duplicate portal messages and sends',async()=>{const x=await setup();const t=await makeTicket(x),p={body:'Update',requestId:crypto.randomUUID()};await x.a.emailReply(x.org,t.id,p);await x.a.emailReply(x.org,t.id,p);assert.equal(state.sent.length,1);assert.equal((await x.a.messages(x.org,t.id)).messages.length,1)});
test('failed delivery can retry with the identical provider idempotency key',async()=>{const x=await setup();const t=await makeTicket(x),p={body:'Update',requestId:crypto.randomUUID()};state.fail=true;await x.a.emailReply(x.org,t.id,p);assert.equal((await x.a.mailHistory(x.org,t.id)).deliveries[0].status,'retry');state.fail=false;await x.a.dispatchMail(x.org,p.requestId);assert.equal(state.sent.length,2);assert.equal(state.sent[0].init.headers['Idempotency-Key'],state.sent[1].init.headers['Idempotency-Key']);assert.equal((await x.a.messages(x.org,t.id)).messages.length,1)});
test('email receipt uses original Message-ID for client threading',async()=>{const x=await setup();const t=await x.a.receiveMail(providerId);await x.a.emailReply(x.org,t.ticketId,{body:'We can help',requestId:crypto.randomUUID()});assert.equal(state.sent[0].payload.headers['In-Reply-To'],'<incoming@example.com>')});
test('delivery webhook advances accepted to delivered and ignores older delayed status',async()=>{const x=await setup();const t=await makeTicket(x);await x.a.emailReply(x.org,t.id,{body:'Update',requestId:crypto.randomUUID()});await handleMailWebhook(signed('email.delivered'));await handleMailWebhook(signed('email.delivery_delayed'));assert.equal((await x.a.mailHistory(x.org,t.id)).deliveries[0].status,'delivered')});
test('bounce and complaint states remain visible',async()=>{const x=await setup();const t=await makeTicket(x);await x.a.emailReply(x.org,t.id,{body:'Update',requestId:crypto.randomUUID()});await handleMailWebhook(signed('email.bounced'));assert.equal((await x.a.mailHistory(x.org,t.id)).deliveries[0].status,'bounced');await handleMailWebhook(signed('email.complained'));assert.equal((await x.a.mailHistory(x.org,t.id)).deliveries[0].status,'complained')});
test('delivery events arriving before provider ID is persisted are reconciled',async()=>{const x=await setup();await handleMailWebhook(signed('email.delivered'));const t=await makeTicket(x);await x.a.emailReply(x.org,t.id,{body:'Update',requestId:crypto.randomUUID()});assert.equal((await x.a.mailHistory(x.org,t.id)).deliveries[0].status,'delivered')});
test('other tenants cannot inspect email recipients or retry messages',async()=>{const x=await setup();const t=await makeTicket(x),requestId=crypto.randomUUID();await x.a.emailReply(x.org,t.id,{body:'Update',requestId});await assert.rejects(x.b.mailHistory(x.org,t.id),status(403));await assert.rejects(x.b.dispatchMail(x.org,requestId),status(403))});
test('missing contact email fails before posting a public message',async()=>{const x=await setup();const t=await x.a.createTicket(x.org,{title:'Help',companyId:x.company,boardId:x.board});await assert.rejects(x.a.emailReply(x.org,t.id,{body:'Update',requestId:crypto.randomUUID()}),status(400));assert.equal((await x.a.messages(x.org,t.id)).messages.length,0)});
test('missing receiving configuration fails safely',async()=>{const x=await setup();state.env.RESEND_WEBHOOK_SECRET='';const t=await makeTicket(x);await assert.rejects(x.a.emailReply(x.org,t.id,{body:'Update',requestId:crypto.randomUUID()}),status(503));assert.equal(state.sent.length,0)});
test('invalid signatures and modified payloads are rejected',async()=>{await setup();await assert.rejects(verifiedWebhook(signed('email.received',providerId,{sig:'v1,AAAA'})),status(401));await assert.rejects(verifiedWebhook(signed('email.received',providerId,{body:'{}'})),status(401))});
test('expired and future signed timestamps are rejected',async()=>{await setup();for(const delta of [-600,600])await assert.rejects(verifiedWebhook(signed('email.received',providerId,{ts:String(Math.floor(Date.now()/1000)+delta)})),status(401))});
test('uncertain deliveries are not retried beyond provider idempotency lifetime',async()=>{const x=await setup();const t=await makeTicket(x),requestId=crypto.randomUUID();state.fail=true;await x.a.emailReply(x.org,t.id,{body:'Update',requestId});await x.a.stmt('UPDATE mail_outbox SET created=? WHERE id=?',new Date(Date.now()-25*3600000).toISOString(),requestId).run();state.fail=false;assert.equal((await x.a.dispatchMail(x.org,requestId)).status,'review');assert.equal(state.sent.length,1)});
test('incoming duplicate replies roll back all extra messages and updates',async()=>{const x=await setup();await x.a.receiveMail(providerId);const t=await x.a.one('SELECT * FROM mail_threads');state.incoming.to=[t.address];const eid=inboundId();await x.a.receiveMail(eid);const before=await x.a.ticket(x.org,t.ticket_id);await x.a.receiveMail(eid);assert.equal((await x.a.messages(x.org,t.ticket_id)).messages.length,1);assert.equal((await x.a.ticket(x.org,t.ticket_id)).version,before.version)});
test('unknown senders create tickets without creating portal grants',async()=>{const x=await setup();state.incoming.from='unknown@example.com';const r=await x.a.receiveMail(providerId);assert.equal((await x.a.ticket(x.org,r.ticketId)).contactId,null);assert.equal((await x.a.rows('SELECT * FROM customer_grants')).length,0);assert.equal((await x.a.rows("SELECT * FROM memberships WHERE user_id LIKE 'mail:%'")).length,0)});
test('email thread is blocked after a ticket moves to another company',async()=>{const x=await setup();await x.a.receiveMail(providerId);const t=await x.a.one('SELECT * FROM mail_threads'),company=(await x.a.directory(x.org,'companies',{name:'Different customer'})).id;await x.a.stmt('UPDATE tickets SET company_id=?,contact_id=NULL WHERE org_id=? AND id=?',company,x.org,t.ticket_id).run();state.incoming.to=[t.address];assert.equal((await x.a.receiveMail(inboundId())).ignored,'ticket-company-changed');await assert.rejects(x.a.emailReply(x.org,t.ticket_id,{body:'Private update',requestId:crypto.randomUUID()}),status(409));assert.equal(state.sent.length,0)});
test('viewers cannot send emails',async()=>{const x=await setup();const viewer={id:'viewer',name:'Viewer',email:'viewer@example.com'},v=new TicketMail(x.db,viewer);await v.register();await x.a.stmt('INSERT INTO memberships(org_id,user_id,role) VALUES(?,?,?)',x.org,viewer.id,'Viewer').run();const t=await makeTicket(x);await assert.rejects(v.emailReply(x.org,t.id,{body:'No',requestId:crypto.randomUUID()}),status(403));assert.equal(state.sent.length,0)});
test('reused outbound request with altered text is rejected',async()=>{const x=await setup();const t=await makeTicket(x),requestId=crypto.randomUUID();await x.a.emailReply(x.org,t.id,{body:'Original',requestId});await assert.rejects(x.a.emailReply(x.org,t.id,{body:'Changed',requestId}),status(409));assert.equal(state.sent.length,1)});
