import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync,mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {build} from 'esbuild';
const compiled=await build({entryPoints:['lib/server/service.ts'],bundle:true,format:'esm',platform:'node',write:false});
const {Service}=await import('data:text/javascript;base64,'+Buffer.from(compiled.outputFiles[0].text).toString('base64'));
class D1 {
 constructor(path=':memory:'){this.sql=new DatabaseSync(path);this.sql.exec('PRAGMA foreign_keys=ON');}
 prepare(sql){const db=this;return {args:[],bind(...args){this.args=args;return this},async all(){const stmt=db.sql.prepare(sql);const results=stmt.all(...this.args);return {results,success:true,meta:{changes:Number(db.sql.prepare('SELECT changes() n').get().n)}}},async first(){return db.sql.prepare(sql).get(...this.args)??null},async run(){const r=db.sql.prepare(sql).run(...this.args);return {results:[],success:true,meta:{changes:Number(r.changes)}}},_sql:sql};}
 async batch(stmts){this.sql.exec('BEGIN');try{const results=[];for(const s of stmts){if(/\bRETURNING\b/i.test(s._sql))results.push(await s.all());else results.push(await s.run());}this.sql.exec('COMMIT');return results}catch(e){this.sql.exec('ROLLBACK');throw e}}
 migrate(){for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())this.sql.exec(readFileSync(join('drizzle',f),'utf8'));}
 close(){this.sql.close()}
}
const alice={id:'alice',name:'Alice Owner',email:'alice@example.com'},bob={id:'bob',name:'Bob Owner',email:'bob@example.com'},eve={id:'eve',name:'Eve Viewer',email:'eve@example.com'};
async function setup(){const db=new D1();db.migrate();const a=new Service(db,alice),b=new Service(db,bob);const oa=(await a.createOrganization({name:'Alpha'})).id,ob=(await b.createOrganization({name:'Beta'})).id;const ca=(await a.directory(oa,'companies',{name:'Alpha customer'})).id,cb=(await b.directory(ob,'companies',{name:'Beta customer'})).id;const ba=(await a.workspace(oa)).boards[0].id,bb=(await b.workspace(ob)).boards[0].id;return {db,a,b,oa,ob,ca,cb,ba,bb}}
const failStatus=status=>e=>e.status===status;
test('missing stable identity cannot create a service',()=>{assert.throws(()=>new Service({},null),failStatus(401));assert.throws(()=>new Service({},{email:'a@x.com',name:'a'}),failStatus(401))});
test('organization membership gates all resource entrypoints',async()=>{const {db,a,b,oa,ob,cb,bb}=await setup();try{await assert.rejects(a.workspace(ob),failStatus(403));await assert.rejects(a.listTickets(ob,new URL('https://test/tickets')),failStatus(403));await assert.rejects(a.ticket(ob,1001),failStatus(403));await assert.rejects(a.createTicket(ob,{title:'Intrusion',companyId:cb,boardId:bb}),failStatus(403));await assert.rejects(a.directory(ob,'companies',{name:'Intrusion'}),failStatus(403));await assert.rejects(a.team(ob),failStatus(403));await assert.rejects(a.audit(ob,new URL('https://test')),failStatus(403));await assert.rejects(a.organization(ob,{name:'Changed'}),failStatus(403));await assert.rejects(a.invite(ob,{email:'x@example.com',role:'Viewer'}),failStatus(403));assert.equal((await b.workspace(ob)).organization.name,'Beta')}finally{db.close()}});
test('company, contact, board, and assignee references must share a tenant',async()=>{const {db,a,oa,ob,ca,cb,ba,bb,b}=await setup();try{const foreignContact=(await b.directory(ob,'contacts',{name:'Private person',companyId:cb})).id;for(const extra of [{companyId:cb},{boardId:bb},{contactId:foreignContact},{assigneeId:bob.id}])await assert.rejects(a.createTicket(oa,{title:'Test',companyId:ca,boardId:ba,...extra}),failStatus(400));assert.equal((await a.listTickets(oa,new URL('https://test/?view=all'))).total,0);assert.throws(()=>db.sql.prepare('INSERT INTO contacts(id,org_id,company_id,name) VALUES(?,?,?,?)').run('bypass',oa,cb,'Nope'),/FOREIGN KEY/)}finally{db.close()}});
test('ticket lifecycle persists assignments, notes, and actor-attributed audit',async()=>{const {db,a,oa,ca,ba}=await setup();try{const contact=(await a.directory(oa,'contacts',{name:'Pat',companyId:ca,email:'pat@example.com'})).id;let t=await a.createTicket(oa,{title:'VPN fails',description:'Remote staff affected',companyId:ca,contactId:contact,boardId:ba});assert.equal(t.id,1001);assert.equal(t.contact,'Pat');t=await a.updateTicket(oa,String(t.id),{status:'In Progress',assigneeId:alice.id,priority:'Critical',version:t.version});assert.equal(t.assignee,'Alice Owner');t=await a.addNote(oa,String(t.id),{body:'Checked gateway logs.',version:t.version});assert.equal(t.notes[0].author,'Alice Owner');assert.equal(t.activity[0].author,'Alice Owner');assert.equal(t.version,3);t=await a.updateTicket(oa,String(t.id),{status:'Resolved',version:t.version});assert.equal(t.closed,1);const list=await a.listTickets(oa,new URL('https://test/?view=open'));assert.equal(list.total,0);assert.equal(list.summary.open,0);assert.equal((await a.listTickets(oa,new URL('https://test/?view=all&q=gateway'))).total,1)}finally{db.close()}});
test('stale writes and notes do not overwrite records or append audit',async()=>{const {db,a,oa,ca,ba}=await setup();try{const t=await a.createTicket(oa,{title:'Issue',companyId:ca,boardId:ba});await a.updateTicket(oa,String(t.id),{priority:'High',version:1});const before=await a.ticket(oa,t.id);await assert.rejects(a.updateTicket(oa,String(t.id),{priority:'Low',version:1}),failStatus(409));await assert.rejects(a.addNote(oa,String(t.id),{body:'Stale note',version:1}),failStatus(409));const after=await a.ticket(oa,t.id);assert.equal(after.priority,'High');assert.equal(after.notes.length,0);assert.equal(after.activity.length,before.activity.length);assert.equal(after.version,2)}finally{db.close()}});
test('same ticket number in two organizations never shares notes or details',async()=>{const {db,a,b,oa,ob,ca,cb,ba,bb}=await setup();try{const ta=await a.createTicket(oa,{title:'Alpha secret',companyId:ca,boardId:ba}),tb=await b.createTicket(ob,{title:'Beta secret',companyId:cb,boardId:bb});assert.equal(ta.id,tb.id);await b.addNote(ob,String(tb.id),{body:'Beta confidential',version:tb.version});assert.equal((await a.ticket(oa,ta.id)).notes.length,0);assert.equal((await a.listTickets(oa,new URL('https://test/?view=all&q=Beta'))).total,0);await assert.rejects(a.addNote(ob,String(tb.id),{body:'No',version:2}),failStatus(403))}finally{db.close()}});
test('invitations require matching identity, acceptance, and enforce role limits',async()=>{const {db,a,oa,ca,ba}=await setup();try{const viewer=new Service(db,eve);await viewer.account();await a.invite(oa,{email:eve.email.toUpperCase(),role:'Viewer'});const invitation=(await viewer.account()).invitations[0];await assert.rejects(viewer.workspace(oa),failStatus(403));const stranger=new Service(db,{id:'stranger',email:'stranger@example.com',name:'Stranger'});await stranger.account();await assert.rejects(stranger.acceptInvitation({invitationId:invitation.id}),failStatus(404));await viewer.acceptInvitation({invitationId:invitation.id});assert.equal((await viewer.workspace(oa)).organization.role,'Viewer');await assert.rejects(viewer.createTicket(oa,{title:'Not allowed',companyId:ca,boardId:ba}),failStatus(403));await assert.rejects(viewer.directory(oa,'companies',{name:'No'}),failStatus(403));await assert.rejects(viewer.team(oa),failStatus(403));await a.role(oa,eve.id,{role:'Engineer'});assert.equal((await viewer.createTicket(oa,{title:'Allowed now',companyId:ca,boardId:ba})).title,'Allowed now');await assert.rejects(viewer.directory(oa,'boards',{name:'No',statuses:[]}),failStatus(403));await assert.rejects(a.role(oa,alice.id,{role:'Viewer'}),failStatus(403))}finally{db.close()}});
test('revoked and expired invitations do not grant membership',async()=>{const {db,a,oa}=await setup();try{const v=new Service(db,eve);await v.account();await a.invite(oa,{email:eve.email,role:'Engineer'});let i=(await v.account()).invitations[0];await a.revokeInvite(oa,i.id);await assert.rejects(v.acceptInvitation({invitationId:i.id}),failStatus(404));await a.invite(oa,{email:eve.email,role:'Engineer'});i=(await v.account()).invitations[0];db.sql.prepare('UPDATE invitations SET expires=? WHERE id=?').run('2000-01-01T00:00:00.000Z',i.id);await assert.rejects(v.acceptInvitation({invitationId:i.id}),failStatus(404));await assert.rejects(v.workspace(oa),failStatus(403))}finally{db.close()}});
test('used board statuses retain their meaning; directory writes use versions',async()=>{const {db,a,oa,ca,ba}=await setup();try{await a.createTicket(oa,{title:'Status test',companyId:ca,boardId:ba});const w=await a.workspace(oa),board=w.boards.find(b=>b.id===ba);await assert.rejects(a.directory(oa,'boards',{name:board.name,description:'',statuses:board.statuses.filter(s=>s.name!=='New'),version:board.version},ba),failStatus(409));await a.directory(oa,'boards',{name:board.name,description:'Custom',statuses:[...board.statuses,{name:'Pending approval',closed:false}],version:board.version},ba);const c=w.companies[0];await a.directory(oa,'companies',{name:'Renamed',version:c.version},c.id);await assert.rejects(a.directory(oa,'companies',{name:'Stale',version:c.version},c.id),failStatus(409));assert.equal((await a.listTickets(oa,new URL('https://test/?view=all'))).tickets[0].company,'Renamed')}finally{db.close()}});
test('sample option seeds 54 tickets, directory records, pagination, and filters',async()=>{const db=new D1();db.migrate();try{const a=new Service(db,alice),org=(await a.createOrganization({name:'Sample',sample:true})).id,w=await a.workspace(org);assert.equal(w.companies.length,10);assert.equal(w.contacts.length,25);let p=await a.listTickets(org,new URL('https://test/?view=all'));assert.equal(p.total,54);assert.equal(p.tickets.length,12);const p2=await a.listTickets(org,new URL('https://test/?view=all&page=1'));assert.ok(!p2.tickets.some(t=>p.tickets.some(x=>x.id===t.id)));p=await a.listTickets(org,new URL('https://test/?view=all&q=1048'));assert.equal(p.total,1);p=await a.listTickets(org,new URL('https://test/?view=mine'));assert.ok(p.tickets.every(t=>t.assigneeId===alice.id&&!t.closed));p=await a.listTickets(org,new URL('https://test/?view=all&priority=Critical&sort=priority'));assert.ok(p.tickets.every(t=>t.priority==='Critical'));const w2=(await a.createOrganization({name:'Empty'})).id;assert.equal((await a.listTickets(w2,new URL('https://test/?view=all'))).total,0)}finally{db.close()}});
test('unknown fields, oversized text, and invalid status are rejected',async()=>{const {db,a,oa,ca,ba}=await setup();try{await assert.rejects(a.createTicket(oa,{title:'No',companyId:ca,boardId:ba,orgId:'foreign'}));await assert.rejects(a.createTicket(oa,{title:'x'.repeat(181),companyId:ca,boardId:ba}));await assert.rejects(a.createTicket(oa,{title:'No',companyId:ca,boardId:ba,status:'Made up'}),failStatus(400));await assert.rejects(a.listTickets(oa,new URL('https://test/?page=-1')))}finally{db.close()}});
test('database state survives process-style database reconnection',async()=>{const dir=mkdtempSync(join(tmpdir(),'queuepilot-test-')),path=join(dir,'db.sqlite');let db=new D1(path);try{db.migrate();let a=new Service(db,alice);const org=(await a.createOrganization({name:'Persistent'})).id;const c=(await a.directory(org,'companies',{name:'Saved customer'})).id,b=(await a.workspace(org)).boards[0].id;await a.createTicket(org,{title:'Saved ticket',companyId:c,boardId:b});db.close();db=new D1(path);a=new Service(db,alice);assert.equal((await a.listTickets(org,new URL('https://test/?view=all'))).tickets[0].title,'Saved ticket')}finally{db.close();rmSync(dir,{recursive:true,force:true})}});
const httpBundle=await build({stdin:{contents:"export * as account from './app/api/account/route.ts'; export * as workspace from './app/api/workspace/[...path]/route.ts';",resolveDir:process.cwd(),sourcefile:'http-test-entry.ts'},bundle:true,format:'esm',platform:'node',write:false,plugins:[{name:'test-runtime',setup(b){b.onResolve({filter:/^(cloudflare:workers|next\/headers)$/},args=>({path:args.path,namespace:'test-runtime'}));b.onLoad({filter:/.*/,namespace:'test-runtime'},args=>({contents:args.path==='cloudflare:workers'?'export const env=globalThis.__qpTestEnv;':'export async function headers(){return globalThis.__qpTestHeaders};export async function cookies(){return {getAll:()=>[],set(){}}}',loader:'js'}));}}]});
globalThis.__qpTestEnv={};globalThis.__qpTestHeaders=new Headers();
const http=await import('data:text/javascript;base64,'+Buffer.from(httpBundle.outputFiles[0].text).toString('base64'));
test('HTTP routes reject anonymous identity, cross-site mutations and untrusted tenant fields',async()=>{const {db,a,oa,ob,ca,ba}=await setup();try{globalThis.__qpTestEnv.DB=db;globalThis.__qpTestHeaders=new Headers();let r=await http.account.GET();assert.equal(r.status,401);globalThis.__qpTestHeaders=new Headers({'oai-authenticated-user-email':alice.email});r=await http.account.GET();assert.equal(r.status,200);const fallbackAccount=await r.json();assert.match(fallbackAccount.user.id,/^sites-email:[a-f0-9]{64}$/);assert.equal(fallbackAccount.organizations.length,0);globalThis.__qpTestHeaders.set('oai-authenticated-user-id',alice.id);r=await http.account.GET();assert.equal(r.status,200);assert.equal(r.headers.get('cache-control'),'private, no-store');const ctx={params:Promise.resolve({path:[oa,'tickets']})},data={title:'HTTP ticket',companyId:ca,boardId:ba};const request=(extra={},payload=data)=>new Request('https://queuepilot.test/api/workspace/'+oa+'/tickets',{method:'POST',headers:{'Content-Type':'application/json',...extra},body:JSON.stringify(payload)});r=await http.workspace.POST(request(),ctx);assert.equal(r.status,403);r=await http.workspace.POST(request({'X-QueuePilot-Request':'1',Origin:'https://attacker.test'}),ctx);assert.equal(r.status,403);r=await http.workspace.POST(request({'X-QueuePilot-Request':'1','Sec-Fetch-Site':'cross-site'}),ctx);assert.equal(r.status,403);r=await http.workspace.POST(request({'X-QueuePilot-Request':'1'}, {...data,orgId:ob}),ctx);assert.equal(r.status,400);r=await http.workspace.POST(request({'X-QueuePilot-Request':'1'}, {...data,description:'x'.repeat(40000)}),ctx);assert.equal(r.status,413);r=await http.workspace.POST(request({'X-QueuePilot-Request':'1',Origin:'https://queuepilot.test'}),ctx);assert.equal(r.status,200);assert.equal((await r.json()).title,'HTTP ticket');r=await http.workspace.GET(new Request('https://queuepilot.test/api/workspace/'+ob),{params:Promise.resolve({path:[ob]})});assert.equal(r.status,403);assert.ok(!(await r.text()).includes('Beta customer'));}finally{db.close();globalThis.__qpTestEnv.DB=undefined;globalThis.__qpTestHeaders=new Headers()}});

test('email-only dispatcher identity can onboard, reload and access only its own workspace',async()=>{
 const db=new D1();db.migrate();
 try{
  globalThis.__qpTestEnv.DB=db;
  globalThis.__qpTestHeaders=new Headers({'oai-authenticated-user-email':' Legacy@Example.com ','oai-authenticated-user-full-name':'Legacy%20Owner','oai-authenticated-user-full-name-encoding':'percent-encoded-utf-8'});
  let response=await http.account.GET();assert.equal(response.status,200);const first=await response.json();assert.equal(first.user.name,'Legacy Owner');assert.equal(first.user.email,'legacy@example.com');
  response=await http.account.POST(new Request('https://queuepilot.test/api/account',{method:'POST',headers:{'Content-Type':'application/json','X-QueuePilot-Request':'1',Origin:'https://queuepilot.test'},body:JSON.stringify({action:'create',name:'Legacy workspace',sample:false})}));assert.equal(response.status,200);const org=(await response.json()).id;
  globalThis.__qpTestHeaders=new Headers({'oai-authenticated-user-email':'legacy@example.com'});
  response=await http.account.GET();assert.equal(response.status,200);const again=await response.json();assert.equal(again.user.id,first.user.id);assert.equal(again.organizations[0].id,org);
  response=await http.workspace.GET(new Request('https://queuepilot.test/api/workspace/'+org),{params:Promise.resolve({path:[org]})});assert.equal(response.status,200);
  globalThis.__qpTestHeaders=new Headers({'oai-authenticated-user-email':'other@example.com'});response=await http.account.GET();assert.equal(response.status,200);assert.notEqual((await response.json()).user.id,first.user.id);
  response=await http.workspace.GET(new Request('https://queuepilot.test/api/workspace/'+org),{params:Promise.resolve({path:[org]})});assert.equal(response.status,403);
  globalThis.__qpTestHeaders=new Headers({'oai-authenticated-user-id':'an-id-without-email'});assert.equal((await http.account.GET()).status,401);
 }finally{db.close();globalThis.__qpTestEnv.DB=undefined;globalThis.__qpTestHeaders=new Headers()}
});
const opsBundle=await build({entryPoints:['lib/server/operations.ts'],bundle:true,format:'esm',platform:'node',write:false});
const {Operations}=await import('data:text/javascript;base64,'+Buffer.from(opsBundle.outputFiles[0].text).toString('base64'));
const ops=(db,user=alice)=>new Operations(db,user);
test('calendar atomically rejects overlaps, accepts adjacent work, and supports cancellation',async()=>{const {db,oa,ob}=await setup();try{const o=ops(db),base={memberId:alice.id,ticketId:null,title:'Install switch',starts:'2026-09-08T09:00:00Z',ends:'2026-09-08T10:00:00Z',kind:'Ticket work',notes:'',cancelled:false};const saved=await o.scheduleSave(oa,base);await assert.rejects(o.scheduleSave(oa,{...base,title:'Overlap',starts:'2026-09-08T09:30:00Z',ends:'2026-09-08T10:30:00Z'}),/schedule_overlap/);await o.scheduleSave(oa,{...base,title:'Adjacent',starts:'2026-09-08T10:00:00Z',ends:'2026-09-08T11:00:00Z'});await o.scheduleSave(oa,{...base,cancelled:true,version:1},saved.id);await o.scheduleSave(oa,base);const events=(await o.schedule(oa,new URL('https://test/?from=2026-09-08T00:00:00Z&to=2026-09-09T00:00:00Z'))).events;assert.equal(events.length,2);await assert.rejects(o.schedule(ob,new URL('https://test/?from=2026-09-08T00:00:00Z&to=2026-09-09T00:00:00Z')),failStatus(403));await assert.rejects(o.scheduleSave(oa,{...base,memberId:bob.id}),failStatus(400))}finally{db.close()}});
test('time entries reject overlaps and enforce ownership; a stopped timer saves only once',async()=>{const {db,a,oa,ca,ba}=await setup();try{const o=ops(db),t=await o.createTicket(oa,{title:'Timed ticket',companyId:ca,boardId:ba}),base={ticketId:t.id,starts:'2026-01-01T09:00:00Z',ends:'2026-01-01T10:00:00Z',description:'Setup',billable:true};const saved=await o.timeSave(oa,base);await assert.rejects(o.timeSave(oa,{...base,starts:'2026-01-01T09:30:00Z'}),/time_overlap/);assert.equal((await o.time(oa,new URL('https://test'))).entries[0].minutes,60);await o.timer(oa,{action:'start',ticketId:t.id});await assert.rejects(o.timer(oa,{action:'start',ticketId:t.id}),/UNIQUE/);await o.timer(oa,{action:'stop',description:'Test timer',billable:false});await assert.rejects(o.timer(oa,{action:'stop',description:'Double stop',billable:false}),failStatus(409));assert.equal((await o.time(oa,new URL('https://test'))).entries.length,2);await a.invite(oa,{email:eve.email,role:'Engineer'});const engineer=ops(db,eve);await engineer.account();await engineer.acceptInvitation({invitationId:(await engineer.account()).invitations[0].id});await assert.rejects(engineer.timeSave(oa,{...base,version:1},saved.id),failStatus(403));await assert.rejects(engineer.scheduleSave(oa,{}),failStatus(403))}finally{db.close()}});
test('SLA snapshots require a public staff response and record resolution time',async()=>{const {db,oa,ca,ba}=await setup();try{const o=ops(db);await o.policySave(oa,{priority:'Critical',responseMinutes:15,resolutionMinutes:240,enabled:true,version:0});let t=await o.createTicket(oa,{title:'SLA ticket',companyId:ca,boardId:ba,priority:'Critical'});assert.equal(Date.parse(t.responseDue)-Date.parse(t.created),15*60000);assert.equal(Date.parse(t.resolutionDue)-Date.parse(t.created),240*60000);await o.addNote(oa,String(t.id),{body:'Internal investigation',version:t.version});t=await o.ticket(oa,t.id);assert.equal(t.responded,null);await o.reply(oa,t.id,{body:'We are investigating.'});t=await o.ticket(oa,t.id);assert.ok(t.responded);t=await o.updateTicket(oa,String(t.id),{status:'Resolved',version:t.version});assert.ok(t.resolved);await o.policySave(oa,{priority:'Critical',responseMinutes:30,resolutionMinutes:480,enabled:true,version:1});assert.equal((await o.ticket(oa,t.id)).responseDue,t.responseDue);await assert.rejects(o.policySave(oa,{priority:'Critical',responseMinutes:30,resolutionMinutes:480,enabled:true,version:1}),failStatus(409))}finally{db.close()}});
test('projects, tasks, and assets link only to the ticket company and preserve versions',async()=>{const {db,oa,ca,cb,ba}=await setup();try{const o=ops(db),t=await o.createTicket(oa,{title:'Related records',companyId:ca,boardId:ba});const project={name:'Core replacement',companyId:ca,description:'Replace switches',ownerId:alice.id,status:'Active',due:'2026-12-01',estimatedHours:20,visible:false};const p=await o.projectSave(oa,project);const task=await o.taskSave(oa,{projectId:p.id,title:'Stage switches',memberId:alice.id,due:'2026-11-01',done:false});await o.taskSave(oa,{projectId:p.id,title:'Stage switches',memberId:alice.id,due:'2026-11-01',done:true,version:1},task.id);assert.equal((await o.projects(oa)).projects[0].completedCount,1);const asset=await o.assetSave(oa,{companyId:ca,name:'Core 01',kind:'Switch',status:'Active',visible:false});await o.linksSave(oa,t.id,{projectId:p.id,assetId:asset.id});assert.equal((await o.links(oa,t.id)).links.assetId,asset.id);await assert.rejects(o.assetSave(oa,{companyId:cb,name:'Foreign',kind:'Switch',status:'Active',visible:false}),failStatus(400));const second=(await o.directory(oa,'companies',{name:'Other Alpha company'})).id;const p2=await o.projectSave(oa,{...project,name:'Other project',companyId:second});await assert.rejects(o.linksSave(oa,t.id,{projectId:p2.id,assetId:null}),failStatus(400));await assert.rejects(o.projectSave(oa,{...project,companyId:second,version:1},p.id),failStatus(409));await assert.rejects(o.updateTicket(oa,String(t.id),{companyId:second,version:t.version}),failStatus(409))}finally{db.close()}});
test('customer portal never returns internal notes, private equipment, audit or another company',async()=>{const {db,oa,ob,ca,ba}=await setup();try{const staff=ops(db),customer=ops(db,{id:'customer',name:'Customer',email:'customer@example.com'});const ticket=await staff.createTicket(oa,{title:'Visible request',description:'Public issue',companyId:ca,boardId:ba});await staff.addNote(oa,String(ticket.id),{body:'INTERNAL_SECRET',version:ticket.version});await staff.assetSave(oa,{name:'Private asset',companyId:ca,kind:'Server',status:'Active',visible:false});await staff.assetSave(oa,{name:'Shared asset',companyId:ca,kind:'Computer',status:'Active',visible:true,ip:'PRIVATE_IP',notes:'PRIVATE_NOTES'});await staff.projectSave(oa,{name:'Private project',companyId:ca,description:'PRIVATE_PROJECT',ownerId:null,status:'Planning',due:'',estimatedHours:0,visible:false});await assert.rejects(customer.portalData(oa,ca,new URL('https://test')),failStatus(403));await staff.grantSave(oa,{companyId:ca,email:'customer@example.com'});await customer.portalAccount();const publicData=JSON.stringify(await customer.portalData(oa,ca,new URL('https://test')));assert.ok(publicData.includes('Shared asset'));assert.ok(!/Private asset|PRIVATE_IP|PRIVATE_NOTES|PRIVATE_PROJECT/.test(publicData));const detail=JSON.stringify(await customer.portalTicket(oa,ca,ticket.id));assert.ok(!/INTERNAL_SECRET|activity|notes/.test(detail));await customer.reply(oa,ticket.id,{body:'Customer update'},ca);assert.equal((await staff.messages(oa,ticket.id)).messages[0].kind,'Customer');const created=await customer.portalCreate(oa,ca,{title:'Portal request',description:'Help please'});assert.ok(created.id);await assert.rejects(customer.workspace(oa),failStatus(403));await assert.rejects(customer.portalData(ob,ca,new URL('https://test')),failStatus(403));const grant=(await staff.grants(oa)).grants[0];await staff.grantRevoke(oa,grant.id);await assert.rejects(customer.portalTicket(oa,ca,ticket.id),failStatus(403))}finally{db.close()}});
test('event rules execute once, use first match, support dry runs, and notify assignees',async()=>{const {db,oa,ca,ba}=await setup();try{const o=ops(db),rule={name:'Critical triage',trigger:'Ticket created',priority:'Critical',boardId:ba,status:'',enabled:true,actions:{assigneeId:alice.id,note:'Review immediately'}};const r=await o.ruleSave(oa,rule);await o.ruleSave(oa,{...rule,name:'Second rule',actions:{note:'SHOULD_NOT_RUN'}});const t=await o.createTicket(oa,{title:'Urgent issue',companyId:ca,boardId:ba,priority:'Critical'});assert.equal(t.assigneeId,alice.id);assert.equal(t.notes.length,1);assert.equal(t.notes[0].body,'Review immediately');assert.ok(t.activity.some(a=>a.action==='Automation: Critical triage'));const before=t.version;assert.equal((await o.ruleTest(oa,r.id,{ticketId:t.id})).matches,true);assert.equal((await o.ticket(oa,t.id)).version,before);const notices=await o.notifications(oa);assert.ok(notices.notifications.some(n=>n.ticketId===t.id));await o.readNotification(oa,{id:notices.notifications[0].id});assert.equal((await o.notifications(oa)).unread,0);await o.updateTicket(oa,String(t.id),{description:'Updated details',version:t.version});assert.equal((await o.ticket(oa,t.id)).notes.length,1);await assert.rejects(o.ruleSave(oa,{...rule,actions:{assigneeId:bob.id}}),failStatus(400))}finally{db.close()}});
test('reports aggregate actual ticket and time data and isolate company filters',async()=>{const {db,oa,ca,ba}=await setup();try{const o=ops(db),t=await o.createTicket(oa,{title:'Report work',companyId:ca,boardId:ba});await o.timeSave(oa,{ticketId:t.id,starts:'2026-01-01T09:00:00Z',ends:'2026-01-01T10:30:00Z',description:'Install',billable:true});const date=new Date().toISOString().slice(0,10);let report=await o.reports(oa,new URL('https://test/?from=2026-01-01&to='+date));assert.equal(report.summary.created,1);assert.equal(report.time.minutes,90);assert.equal(report.byTechnician[0].minutes,90);report=await o.reports(oa,new URL('https://test/?from=2026-01-01&to='+date+'&company=other-company'));assert.equal(report.summary.created,0);assert.equal(report.time.minutes,0);await assert.rejects(o.reports(oa,new URL('https://test/?from=2026-12-31&to=2026-01-01')),failStatus(400))}finally{db.close()}});
test('attachment uploads and downloads enforce customer visibility and tenant access',async()=>{const {db,oa,ca,ba}=await setup();const objects=new Map();try{globalThis.__qpTestEnv.DB=db;globalThis.__qpTestEnv.BUCKET={async put(key,buffer){objects.set(key,new Uint8Array(buffer))},async get(key){const value=objects.get(key);return value?{body:new Blob([value]).stream()}:null},async delete(key){objects.delete(key)}};const staff=ops(db),t=await staff.createTicket(oa,{title:'File test',companyId:ca,boardId:ba});globalThis.__qpTestHeaders=new Headers({'oai-authenticated-user-id':alice.id,'oai-authenticated-user-email':alice.email});const ctx={params:Promise.resolve({path:[oa,'tickets',String(t.id),'files']})};const upload=async visibility=>{const form=new FormData();form.set('file',new File(['Safe attachment body'],'report.txt',{type:'text/plain'}));form.set('visibility',visibility);return http.workspace.POST(new Request('https://queuepilot.test/api/workspace/'+oa+'/tickets/'+t.id+'/files',{method:'POST',headers:{'X-QueuePilot-Request':'1'},body:form}),ctx)};let r=await upload('Internal');assert.equal(r.status,200);const internal=(await r.json()).id;r=await upload('Customer');assert.equal(r.status,200);const shared=(await r.json()).id;assert.equal(objects.size,2);r=await http.workspace.GET(new Request('https://queuepilot.test/files'),{params:Promise.resolve({path:[oa,'tickets',String(t.id),'files',shared]})});assert.equal(r.status,200);assert.equal(r.headers.get('content-type'),'application/octet-stream');assert.match(r.headers.get('content-disposition'),/^attachment/);assert.equal(await r.text(),'Safe attachment body');await staff.grantSave(oa,{companyId:ca,email:'files-customer@example.com'});const customer=ops(db,{id:'files-customer',email:'files-customer@example.com',name:'Files customer'});await customer.portalAccount();const fileModule=await build({entryPoints:['lib/server/files.ts'],bundle:true,format:'esm',platform:'node',write:false,plugins:[{name:'r2-runtime',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'env',namespace:'r2'}));b.onLoad({filter:/.*/,namespace:'r2'},()=>({contents:'export const env=globalThis.__qpTestEnv',loader:'js'}));}}]});const {fileRequest}=await import('data:text/javascript;base64,'+Buffer.from(fileModule.outputFiles[0].text).toString('base64'));const list=await fileRequest(customer,new Request('https://test/files'),oa,t.id,undefined,ca);assert.deepEqual(list.files.map(f=>f.id),[shared]);await assert.rejects(fileRequest(customer,new Request('https://test/files'),oa,t.id,internal,ca),failStatus(404));assert.equal(await (await fileRequest(customer,new Request('https://test/files'),oa,t.id,shared,ca)).text(),'Safe attachment body');await assert.rejects(fileRequest(customer,new Request('https://test/files'),oa,t.id,shared,'another-company'),failStatus(403));}finally{db.close();globalThis.__qpTestEnv.DB=undefined;globalThis.__qpTestEnv.BUCKET=undefined;globalThis.__qpTestHeaders=new Headers()}});
const advancedBundle=await build({stdin:{contents:"export {Advanced,parseCSV} from './lib/server/advanced.ts';export {businessDeadline} from './lib/server/automation.ts'",resolveDir:process.cwd()},bundle:true,format:'esm',platform:'node',write:false});
const {Advanced,parseCSV,businessDeadline}=await import('data:text/javascript;base64,'+Buffer.from(advancedBundle.outputFiles[0].text).toString('base64'));
test('custom roles replace operational permissions and cannot elevate administration',async()=>{const {db,a,oa,ob,ca,ba}=await setup();try{const s=new Advanced(db,alice),v=new Advanced(db,eve);await v.account();await a.invite(oa,{email:eve.email,role:'Engineer'});await v.acceptInvitation({invitationId:(await v.account()).invitations[0].id});const role=await s.customRoleSave(oa,{name:'Asset specialist',capabilities:['assets:write']});await s.customRoleAssign(oa,{userId:eve.id,roleId:role.id});assert.equal((await v.context(oa)).roleName,'Asset specialist');await assert.rejects(v.createTicket(oa,{title:'Denied',companyId:ca,boardId:ba}),failStatus(403));await v.context(oa,'assets:write');await assert.rejects(s.customRoleSave(oa,{name:'Escalated',capabilities:['team:write']}),failStatus(400));await assert.rejects(v.customRoleSave(oa,{name:'No',capabilities:[]}),failStatus(403));await assert.rejects(s.customRoleAssign(oa,{userId:alice.id,roleId:role.id}),failStatus(403));await assert.rejects(s.customRoles(ob),failStatus(403));await a.role(oa,eve.id,{role:'Engineer'});await v.context(oa,'tickets:write');}finally{db.close()}});
test('CSV parser handles quoted commas and newlines; imports preview, reject errors, skip duplicates and isolate tenants',async()=>{const {db,oa,ob}=await setup();try{const s=new Advanced(db,alice);assert.deepEqual(parseCSV('name,notes\r\n"Acme, Inc","Line 1\nLine 2"'),[{name:'Acme, Inc',notes:'Line 1\nLine 2'}]);assert.throws(()=>parseCSV('name\n"unclosed'));let r=await s.importCSV(oa,{kind:'companies',csv:'name,email\nNew Corp,hello@example.com'});assert.equal(r.created,1);assert.equal((await s.workspace(oa)).companies.length,1);r=await s.importCSV(oa,{kind:'companies',csv:'name,email\nNew Corp,hello@example.com',apply:true});assert.equal(r.created,1);r=await s.importCSV(oa,{kind:'companies',csv:'name,email\nNew Corp,hello@example.com',apply:true});assert.equal(r.created,0);assert.equal(r.skipped,1);await assert.rejects(s.importCSV(oa,{kind:'contacts',csv:'name,company,email\nJane,Beta customer,jane@example.com',apply:true}),failStatus(400));await s.importCSV(oa,{kind:'contacts',csv:'name,company,email\nJane,New Corp,jane@example.com',apply:true});await s.importCSV(oa,{kind:'assets',csv:'name,company,serial\nLaptop,New Corp,ABC',apply:true});assert.equal((await s.assets(oa)).assets.length,1);await assert.rejects(s.importCSV(ob,{kind:'companies',csv:'name\nNo',apply:true}),failStatus(403));}finally{db.close()}});
test('child relations prevent cycles and tenant/company changes; merges preserve source audit and consolidate notes',async()=>{const {db,a,oa,ca,ba}=await setup();try{const s=new Advanced(db,alice),parent=await a.createTicket(oa,{title:'Parent',companyId:ca,boardId:ba}),child=await a.createTicket(oa,{title:'Child',companyId:ca,boardId:ba,parentId:parent.id});assert.equal((await s.relations(oa,parent.id)).relations.length,1);await assert.rejects(s.relationSave(oa,parent.id,{kind:'parent',targetId:child.id,version:parent.version}),failStatus(400));await s.relationSave(oa,child.id,{kind:'parent',targetId:null,version:child.version});const source=await s.addNote(oa,String(child.id),{body:'Keep this history',version:2});await s.relationSave(oa,child.id,{kind:'merge',targetId:parent.id,version:source.version,targetVersion:parent.version});const merged=await s.ticket(oa,parent.id);assert.ok(merged.notes.some(n=>n.body==='Keep this history'));assert.equal((await s.ticket(oa,child.id)).closed,1);assert.ok((await s.ticket(oa,child.id)).activity.some(a=>a.action==='Ticket merged'));await assert.rejects(s.updateTicket(oa,String(child.id),{status:'New',version:4}),failStatus(409));}finally{db.close()}});
test('recurring runs are idempotent, advance overdue schedules, and apply ticket automation',async()=>{const {db,oa,ca,ba}=await setup();try{const s=new Advanced(db,alice);await s.configSave(oa,'recurring',{name:'Weekly checks',title:'Check backups',description:'Verify restore',companyId:ca,boardId:ba,assigneeId:null,priority:'Normal',intervalDays:7,nextDue:'2020-01-01T09:00:00.000Z',enabled:true});assert.equal((await s.runRecurring(oa)).created,1);assert.equal((await s.runRecurring(oa)).created,0);assert.equal((await s.listTickets(oa,new URL('https://test/?view=all'))).total,1);}finally{db.close()}});
test('business SLA skips weekends and holidays while preserving exact working minutes',()=>{const cal={enabled:true,startHour:9,endHour:17,weekdays:[1,2,3,4,5],holidays:'2026-09-07'};assert.equal(businessDeadline('2026-09-04T16:30:00.000Z',60,cal),'2026-09-08T09:30:00.000Z');assert.equal(businessDeadline('2026-09-04T08:30:00.000Z',30,cal),'2026-09-04T09:30:00.000Z');});
test('project templates are transactional and reject stale application; metadata respects tenant membership',async()=>{const {db,oa,ob,ca,ba}=await setup();try{const s=new Advanced(db,alice),p=await s.projectSave(oa,{name:'Upgrade',companyId:ca,ownerId:null,status:'Planning',due:'',estimatedHours:5,visible:false}),t=await s.configSave(oa,'project-template',{name:'Network',tasks:'Discover\nInstall\nTest'});await s.applyProjectTemplate(oa,{projectId:p.id,templateId:t.id,version:1});await assert.rejects(s.applyProjectTemplate(oa,{projectId:p.id,templateId:t.id,version:1}),failStatus(409));assert.equal((await s.project(oa,p.id)).tasks.length,3);const ticket=await s.createTicket(oa,{title:'Details',companyId:ca,boardId:ba});await s.metadataSave(oa,ticket.id,{type:'Incident',tags:'network,urgent',customFields:{Rack:'A1'}});assert.equal((await s.metadata(oa,ticket.id)).customFields.Rack,'A1');await assert.rejects(s.metadata(ob,ticket.id),failStatus(403));}finally{db.close()}});
test('task dependencies block cycles and completion until prerequisites are done',async()=>{const {db,oa,ca}=await setup();try{const s=new Advanced(db,alice),project=await s.projectSave(oa,{name:'Dependency project',companyId:ca,ownerId:null,status:'Active',due:'',estimatedHours:1,visible:false}),first=await s.taskSave(oa,{projectId:project.id,title:'Discover',memberId:null,due:'',done:false}),second=await s.taskSave(oa,{projectId:project.id,title:'Deploy',memberId:null,due:'',done:false});await s.dependencySave(oa,{taskId:second.id,dependencyId:first.id});await assert.rejects(s.dependencySave(oa,{taskId:first.id,dependencyId:second.id}),/dependency_cycle/);await assert.rejects(s.taskSave(oa,{projectId:project.id,title:'Deploy',memberId:null,due:'',done:true,version:1},second.id),/dependency_incomplete/);await s.taskSave(oa,{projectId:project.id,title:'Discover',memberId:null,due:'',done:true,version:1},first.id);await s.taskSave(oa,{projectId:project.id,title:'Deploy',memberId:null,due:'',done:true,version:1},second.id);assert.equal((await s.project(oa,project.id)).tasks.filter(t=>t.done).length,2);}finally{db.close()}});
test('report filters and notification preferences are applied to persisted data',async()=>{const {db,oa,ca,ba}=await setup();try{const s=new Advanced(db,alice);await s.prefs(oa,{assignment:false});const t=await s.createTicket(oa,{title:'Quiet assignment',companyId:ca,boardId:ba,assigneeId:alice.id});assert.equal((await s.notifications(oa)).unread,0);const day=new Date().toISOString().slice(0,10);const r=await s.reports(oa,new URL(`https://test/?from=${day}&to=${day}&board=${ba}&technician=alice`));assert.equal(r.summary.created,1);assert.equal((await s.reports(oa,new URL(`https://test/?from=${day}&to=${day}&technician=unknown`))).summary.created,0);const search=await s.search(oa,new URL('https://test/?q=Quiet'));assert.ok(search.results.some(r=>r.id===t.id));}finally{db.close()}});
const deliveryBundle=await build({entryPoints:['lib/server/delivery.ts'],bundle:true,format:'esm',platform:'node',write:false});
const {Delivery}=await import('data:text/javascript;base64,'+Buffer.from(deliveryBundle.outputFiles[0].text).toString('base64'));
test('project financial plan uses cents, linked time and expense states; currency and versions cannot silently change',async()=>{const {db,oa,ob,ca,ba}=await setup();try{const s=new Delivery(db,alice),p=await s.projectSave(oa,{name:'Finance project',companyId:ca,ownerId:null,status:'Active',due:'',estimatedHours:10,visible:true}),plan={budget:1000,laborRate:60,currency:'USD',startDate:'2026-09-07',notes:'Internal margin assumptions',version:0};await s.planSave(oa,p.id,plan);const t=await s.createTicket(oa,{title:'Install',companyId:ca,boardId:ba});await s.linksSave(oa,t.id,{projectId:p.id,assetId:null});await s.timeSave(oa,{ticketId:t.id,starts:'2020-01-01T10:00:00.000Z',ends:'2020-01-01T11:30:00.000Z',description:'Install',billable:true});const expense={projectId:p.id,description:'Switch',vendor:'Vendor',category:'Hardware',amount:120.25,date:'2026-09-07',status:'Paid',currency:'USD'};const e=await s.expenseSave(oa,expense);await s.expenseSave(oa,{...expense,description:'Planned travel',amount:30,status:'Planned'});let f=await s.projectFinance(oa,p.id);assert.equal(f.totals.laborCost,90);assert.equal(f.totals.actualExpenses,120.25);assert.equal(f.totals.plannedExpenses,30);assert.equal(f.totals.remaining,789.75);assert.equal(f.totals.hours,1.5);await assert.rejects(s.planSave(oa,p.id,{...plan,currency:'EUR',version:1}),failStatus(409));await assert.rejects(s.planSave(oa,p.id,{...plan,version:9}),failStatus(409));await assert.rejects(s.expenseSave(oa,{...expense,amount:1.234}));await assert.rejects(s.expenseSave(oa,{...expense,currency:'CAD'}),failStatus(409));await s.expenseSave(oa,{...expense,status:'Voided',version:1},e.id);assert.equal((await s.projectFinance(oa,p.id)).totals.actualExpenses,0);await assert.rejects(s.expenseSave(oa,{...expense,version:1},e.id),failStatus(409));await assert.rejects(s.projectFinance(ob,p.id),failStatus(403));}finally{db.close()}});
test('milestones enforce project and owner tenant boundaries and prevent moving between projects',async()=>{const {db,oa,ob,ca}=await setup();try{const s=new Delivery(db,alice),p=await s.projectSave(oa,{name:'Milestones',companyId:ca,ownerId:null,status:'Active',due:'',estimatedHours:0,visible:false}),other=await s.projectSave(oa,{name:'Other project',companyId:ca,ownerId:null,status:'Active',due:'',estimatedHours:0,visible:false}),value={projectId:p.id,title:'Acceptance',due:'2026-12-01',memberId:alice.id,completed:false,notes:'Customer sign-off'};const m=await s.milestoneSave(oa,value);await s.milestoneSave(oa,{...value,completed:true,version:1},m.id);assert.equal((await s.milestones(oa,p.id)).milestones[0].completed,1);await assert.rejects(s.milestoneSave(oa,{...value,version:1},m.id),failStatus(409));await assert.rejects(s.milestoneSave(oa,{...value,projectId:other.id,version:2},m.id),failStatus(409));await assert.rejects(s.milestoneSave(oa,{...value,memberId:bob.id}),failStatus(400));await assert.rejects(s.milestones(ob,p.id),failStatus(403));}finally{db.close()}});
test('locations and contact profiles enforce same-company links, safe contact moves and directory permissions',async()=>{const {db,a,oa,ob,ca}=await setup();try{const s=new Delivery(db,alice),other=(await s.directory(oa,'companies',{name:'Other customer'})).id,contact=(await s.directory(oa,'contacts',{name:'Jane',companyId:ca})).id,location=await s.locationSave(oa,{companyId:ca,name:'Main campus',address:'123 Main St',phone:'555-0100',notes:'Internal access code',active:true}),foreign=await s.locationSave(oa,{companyId:other,name:'Other campus',address:'',phone:'',notes:'',active:true}),profile={mobile:'555-0101',preferred:'Mobile',locationId:location.id,notes:'Internal contact context',version:0};await s.contactProfileSave(oa,contact,profile);assert.equal((await s.contactProfile(oa,contact)).profile.mobile,'555-0101');await assert.rejects(s.contactProfileSave(oa,contact,{...profile,locationId:foreign.id,version:1}),failStatus(400));await assert.rejects(s.directory(oa,'contacts',{name:'Jane',companyId:other,version:1},contact),/contact_location/);await s.contactProfileSave(oa,contact,{...profile,locationId:null,version:1});await s.directory(oa,'contacts',{name:'Jane',companyId:other,version:1},contact);await assert.rejects(s.contactProfile(ob,contact),failStatus(403));const viewer=new Delivery(db,eve);await viewer.account();await a.invite(oa,{email:eve.email,role:'Viewer'});await viewer.acceptInvitation({invitationId:(await viewer.account()).invitations[0].id});await viewer.contactProfile(oa,contact);await assert.rejects(viewer.locationSave(oa,{companyId:ca,name:'No',address:'',phone:'',notes:'',active:true}),failStatus(403));await assert.rejects(viewer.projectFinance(oa,'no-project'),failStatus(403));}finally{db.close()}});
const enterpriseBundle=await build({entryPoints:['lib/server/enterprise.ts'],bundle:true,format:'esm',platform:'node',write:false});
const {Enterprise}=await import('data:text/javascript;base64,'+Buffer.from(enterpriseBundle.outputFiles[0].text).toString('base64'));
test('board defaults distinguish omitted assignment and snapshot board SLA overrides',async()=>{const {db,oa,ca,ba}=await setup();try{const s=new Enterprise(db,alice),settings={defaultMemberId:alice.id,email:'help@example.com',labels:{Critical:'Urgent',High:'High',Normal:'Standard',Low:'Low'},targets:{Normal:{response:15,resolution:90}},version:0};await s.boardSettingsSave(oa,ba,settings);const t=await s.createTicket(oa,{title:'Default routing',companyId:ca,boardId:ba});assert.equal(t.assigneeId,alice.id);assert.equal(Date.parse(t.resolutionDue)-Date.parse(t.created),90*60000);assert.equal((await s.workspace(oa)).boards[0].priorityLabels.Normal,'Standard');assert.equal((await s.createTicket(oa,{title:'Explicit unassigned',companyId:ca,boardId:ba,assigneeId:null})).assigneeId,null);await assert.rejects(s.boardSettingsSave(oa,ba,{...settings,version:9}),failStatus(409));await assert.rejects(s.boardSettingsSave(oa,ba,{...settings,defaultMemberId:bob.id,version:1}),failStatus(400));}finally{db.close()}});
test('purchases preserve exact totals, enforce lifecycle and freeze approved drafts',async()=>{const {db,oa,ob,ca}=await setup();try{const s=new Enterprise(db,alice),p=await s.projectSave(oa,{name:'Purchases',companyId:ca,ownerId:null,status:'Active',due:'',estimatedHours:0,visible:false}),value={projectId:p.id,vendor:'Supplier',reference:'PO-1',currency:'USD',items:[{description:'Cable',quantity:3,unitCost:10.15}],notes:''},r=await s.purchaseSave(oa,value);assert.equal((await s.purchasing(oa,p.id)).purchases[0].totalCents,3045);await assert.rejects(s.purchaseTransition(oa,r.id,{status:'Received',version:1}),failStatus(409));await s.purchaseTransition(oa,r.id,{status:'Approved',version:1});await assert.rejects(s.purchaseSave(oa,{...value,version:2},r.id),failStatus(409));await assert.rejects(s.purchaseTransition(oa,r.id,{status:'Ordered',version:1}),failStatus(409));await s.purchaseTransition(oa,r.id,{status:'Ordered',version:2});await s.purchaseTransition(oa,r.id,{status:'Received',version:3});assert.equal((await s.purchasing(oa,p.id)).purchases[0].status,'Received');assert.equal((await s.projectFinance(oa,p.id)).totals.actualExpenses,0);await assert.rejects(s.purchasing(ob,p.id),failStatus(403));}finally{db.close()}});
test('delivery templates atomically assign roles, dates, prerequisites and milestones',async()=>{const {db,oa,ca}=await setup();try{const s=new Enterprise(db,alice),p=await s.projectSave(oa,{name:'Rollout',companyId:ca,ownerId:null,status:'Active',due:'',estimatedHours:0,visible:false}),value={name:'Deployment',tasks:[{title:'Prepare',role:'Engineer',days:0,dependsOn:null},{title:'Deploy',role:'Engineer',days:2,dependsOn:0}],milestones:[{title:'Acceptance',days:3}]},t=await s.templateSave(oa,value);await s.templateApply(oa,t.id,{projectId:p.id,version:1,start:'2026-09-07',owners:{Engineer:alice.id}});const tasks=(await s.project(oa,p.id)).tasks;assert.equal(tasks.length,2);assert.equal(tasks.find(t=>t.title==='Deploy').due,'2026-09-09');assert.equal(tasks[0].memberId,alice.id);assert.equal((await s.milestones(oa,p.id)).milestones[0].due,'2026-09-10');await assert.rejects(s.templateApply(oa,t.id,{projectId:p.id,version:1,start:'2026-09-07',owners:{}}),failStatus(409));assert.equal((await s.project(oa,p.id)).tasks.length,2);await assert.rejects(s.templateSave(oa,{...value,tasks:[{...value.tasks[0],dependsOn:0}]}));}finally{db.close()}});
test('contact equipment links reject different companies and protect contact moves',async()=>{const {db,oa,ca}=await setup();try{const s=new Enterprise(db,alice),other=(await s.directory(oa,'companies',{name:'Other'})).id,c=(await s.directory(oa,'contacts',{name:'Jane',companyId:ca})).id,a=await s.assetSave(oa,{name:'Laptop',companyId:ca,kind:'Computer',status:'Active',visible:false}),b=await s.assetSave(oa,{name:'Other laptop',companyId:other,kind:'Computer',status:'Active',visible:false});await s.linkAsset(oa,c,{assetId:a.id,remove:false});assert.equal((await s.linkedAssets(oa,c)).links[0].assetId,a.id);await assert.rejects(s.linkAsset(oa,c,{assetId:b.id,remove:false}),failStatus(400));await assert.rejects(s.directory(oa,'contacts',{name:'Jane',companyId:other,version:1},c),/contact_asset/);await s.linkAsset(oa,c,{assetId:a.id,remove:true});await s.directory(oa,'contacts',{name:'Jane',companyId:other,version:1},c);}finally{db.close()}});
test('automation creates linked tasks once, mentions respect preferences and scans deduplicate',async()=>{const {db,oa,ca,ba}=await setup();try{const s=new Enterprise(db,alice),p=await s.projectSave(oa,{name:'Follow-up',companyId:ca,ownerId:null,status:'Active',due:'',estimatedHours:0,visible:false}),t=await s.createTicket(oa,{title:'Follow up',companyId:ca,boardId:ba,assigneeId:alice.id});await s.linksSave(oa,t.id,{projectId:p.id,assetId:null});await s.ruleSave(oa,{name:'Follow-up task',trigger:'Ticket updated',priority:'',boardId:'',status:'',enabled:true,actions:{taskTitle:'Review update',notifyUserId:alice.id}});await s.updateTicket(oa,String(t.id),{description:'Changed',version:t.version});assert.equal((await s.project(oa,p.id)).tasks.length,1);await assert.rejects(s.updateTicket(oa,String(t.id),{description:'Stale',version:t.version}),failStatus(409));assert.equal((await s.project(oa,p.id)).tasks.length,1);await s.prefs(oa,{mentions:false});await s.addNote(oa,String(t.id),{body:'Mention quiet',version:2,mentionIds:[alice.id]});assert.ok(!(await s.notifications(oa)).notifications.some(n=>n.title.startsWith('Mentioned')));await s.stmt("UPDATE tickets SET resolution_due='2020-01-01T00:00:00.000Z' WHERE org_id=? AND id=?",oa,t.id).run();assert.equal((await s.scanNotifications(oa)).created,1);assert.equal((await s.scanNotifications(oa)).checked,0);}finally{db.close()}});
test('company documents hide internal and private-project files from customers',async()=>{const {db,oa,ca}=await setup();const objects=new Map();try{globalThis.__qpTestEnv.BUCKET={async put(k,b){objects.set(k,new Uint8Array(b))},async get(k){return objects.has(k)?{body:new Blob([objects.get(k)]).stream()}:null},async delete(k){objects.delete(k)}};const bundle=await build({entryPoints:['lib/server/documents.ts'],bundle:true,format:'esm',platform:'node',write:false,plugins:[{name:'document-runtime',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'env',namespace:'r2'}));b.onLoad({filter:/.*/,namespace:'r2'},()=>({contents:'export const env=globalThis.__qpTestEnv',loader:'js'}));}}]});const {documentRequest}=await import('data:text/javascript;base64,'+Buffer.from(bundle.outputFiles[0].text).toString('base64')),s=new Enterprise(db,alice),customer=new Enterprise(db,{id:'doc-customer',email:'doc@example.com',name:'Doc customer'}),pv={name:'Private rollout',companyId:ca,ownerId:null,status:'Active',due:'',estimatedHours:0,visible:false},p=await s.projectSave(oa,pv);await s.grantSave(oa,{companyId:ca,email:'doc@example.com'});await customer.portalAccount();const upload=async(kind,rid,visibility)=>{const f=new FormData();f.set('file',new File(['Document body'],'guide.html'));f.set('visibility',visibility);return documentRequest(s,new Request('https://test/doc',{method:'POST',headers:{'X-QueuePilot-Request':'1'},body:f}),oa,kind,rid)};const internal=await upload('company',ca,'Internal'),shared=await upload('company',ca,'Customer'),project=await upload('project',p.id,'Customer'),get=()=>new Request('https://test/doc');assert.deepEqual((await documentRequest(customer,get(),oa,'company',ca,undefined,true)).files.map(f=>f.id),[shared.id]);await assert.rejects(documentRequest(customer,get(),oa,'company',ca,internal.id,true),failStatus(404));await assert.rejects(documentRequest(customer,get(),oa,'company',ca,project.id,true),failStatus(404));await s.projectSave(oa,{...pv,visible:true,version:1},p.id);assert.equal((await documentRequest(customer,get(),oa,'company',ca,undefined,true)).files.length,2);const download=await documentRequest(customer,get(),oa,'company',ca,shared.id,true);assert.equal(download.headers.get('Content-Type'),'application/octet-stream');assert.equal(await download.text(),'Document body');const other=(await s.directory(oa,'companies',{name:'Other doc company'})).id;await assert.rejects(s.projectSave(oa,{...pv,companyId:other,version:2},p.id),/document_company/);}finally{db.close();globalThis.__qpTestEnv.BUCKET=undefined}});
test('customer-response rules apply guarded ticket and project effects',async()=>{const {db,oa,ca,ba}=await setup();try{const s=new Enterprise(db,alice),c=new Enterprise(db,{id:'reply-customer',email:'reply@example.com',name:'Customer'}),t=await s.createTicket(oa,{title:'Awaiting reply',companyId:ca,boardId:ba}),p=await s.projectSave(oa,{name:'Replies',companyId:ca,ownerId:null,status:'Active',due:'',estimatedHours:0,visible:true});await s.linksSave(oa,t.id,{projectId:p.id,assetId:null});await s.grantSave(oa,{companyId:ca,email:'reply@example.com'});await c.portalAccount();await s.ruleSave(oa,{name:'Reply follow-up',trigger:'Customer responded',priority:'',boardId:'',status:'',enabled:true,actions:{priority:'High',taskTitle:'Review customer reply',note:'Customer replied',notifyUserId:alice.id}});await c.reply(oa,t.id,{body:'Ready to proceed'},ca);const updated=await s.ticket(oa,t.id);assert.equal(updated.priority,'High');assert.equal(updated.notes[0].body,'Customer replied');assert.equal((await s.project(oa,p.id)).tasks.length,1);assert.equal((await s.messages(oa,t.id)).messages[0].body,'Ready to proceed');}finally{db.close()}});
const completionBundle=await build({entryPoints:['lib/server/completion.ts'],bundle:true,format:'esm',platform:'node',write:false});
const {Completion}=await import('data:text/javascript;base64,'+Buffer.from(completionBundle.outputFiles[0].text).toString('base64'));
test('invoice ledger enforces issue locks, payment limits, currency and tenant isolation',async()=>{const {db,oa,ob,ca}=await setup();try{const s=new Completion(db,alice),pv={name:'Invoice project',companyId:ca,ownerId:null,status:'Active',due:'',estimatedHours:0,visible:false},p=await s.projectSave(oa,pv),plan={budget:1000,laborRate:60,currency:'USD',startDate:'',notes:'',version:0};await s.planSave(oa,p.id,plan);const value={companyId:ca,projectId:p.id,reference:'INV-001',description:'Installation',amount:100.25,currency:'USD',issued:'2026-09-07',due:'2026-09-30'},i=await s.invoiceSave(oa,value);await s.invoiceAction(oa,i.id,{action:'issue',version:1});await assert.rejects(s.invoiceSave(oa,{...value,version:2},i.id),failStatus(409));await s.invoiceAction(oa,i.id,{action:'payment',amount:50,date:'2026-09-07',reference:'Wire',version:2});await assert.rejects(s.invoiceAction(oa,i.id,{action:'payment',amount:50,date:'2026-09-07',version:2}),failStatus(409));await assert.rejects(s.invoiceAction(oa,i.id,{action:'payment',amount:51,date:'2026-09-07',version:3}),failStatus(409));await assert.rejects(s.invoiceAction(oa,i.id,{action:'void',version:3}),failStatus(409));assert.equal((await s.billing(oa)).invoices[0].paid_cents,5000);const profit=(await s.profitability(oa)).projects[0];assert.equal(profit.invoiced,100.25);assert.equal(profit.paid,50);await assert.rejects(s.planSave(oa,p.id,{...plan,currency:'EUR',version:1}),/invoice_/);const other=(await s.directory(oa,'companies',{name:'Another customer'})).id;await assert.rejects(s.projectSave(oa,{...pv,companyId:other,version:1},p.id),/invoice_/);await assert.rejects(s.billing(ob),failStatus(403));}finally{db.close()}});
test('teams replace membership atomically and reject foreign users and stale edits',async()=>{const {db,oa}=await setup();try{const s=new Completion(db,alice),v={name:'Engineering',description:'Network delivery',members:[alice.id]},t=await s.teamSave(oa,v);await assert.rejects(s.teamSave(oa,{...v,members:[bob.id],version:1},t.id),failStatus(400));await s.teamSave(oa,{...v,members:[],version:1},t.id);await assert.rejects(s.teamSave(oa,{...v,version:1},t.id),failStatus(409));assert.equal((await s.teams(oa)).members.length,0);}finally{db.close()}});
test('read-only API keys are hashed, scope-bound, identity-bound and revocable',async()=>{const {db,oa}=await setup();try{const s=new Completion(db,alice),key=await s.keyCreate(oa,{name:'Reporting',scope:'tickets:read',days:1});assert.ok(key.token.startsWith('qp_'));assert.ok(!JSON.stringify(await s.keys(oa)).includes(key.token));const raw=await s.one('SELECT hash FROM api_keys WHERE org_id=?',oa);assert.notEqual(raw.hash,key.token);await s.verifyKey(oa,key.token,'tickets:read');await assert.rejects(s.verifyKey(oa,key.token,'events:read'),failStatus(403));await s.keyRevoke(oa,key.id);await assert.rejects(s.verifyKey(oa,key.token,'tickets:read'),failStatus(403));const second=await s.keyCreate(oa,{name:'Expired',scope:'events:read',days:1});await s.stmt("UPDATE api_keys SET expires='2020-01-01' WHERE org_id=? AND id=?",oa,second.id).run();await assert.rejects(s.verifyKey(oa,second.token,'events:read'),failStatus(403));}finally{db.close()}});
test('report definitions validate tenant filters and analytics use filtered logged hours',async()=>{const {db,oa,ob,ca,ba}=await setup();try{const s=new Completion(db,alice),d={name:'Monthly engineering',days:30,capacityHours:8,companyId:ca,boardId:ba,technicianId:alice.id},r=await s.recordSave(oa,'report-definition',d);assert.equal((await s.records(oa,'report-definition')).records[0].days,30);await assert.rejects(s.recordSave(oa,'report-definition',{...d,companyId:'foreign'}),failStatus(400));await assert.rejects(s.recordSave(oa,'connection',{name:'Slack',account:'ops',notes:'',version:1},r.id),failStatus(404));const t=await s.createTicket(oa,{title:'Analytics',companyId:ca,boardId:ba});await s.timeSave(oa,{ticketId:t.id,starts:'2026-09-07T10:00:00Z',ends:'2026-09-07T12:00:00Z',description:'Work',billable:true});const data=await s.analytics(oa,new URL('https://test/?from=2026-09-07&to=2026-09-07&capacity=8'));assert.equal(data.utilization[0].percent,25);assert.equal((await s.analytics(oa,new URL('https://test/?from=2026-09-07&to=2026-09-07&company=unknown'))).utilization.length,0);await assert.rejects(s.records(ob,'report-definition'),failStatus(403));}finally{db.close()}});
test('timed rules apply once per deadline without recursively triggering update rules',async()=>{const {db,oa,ca,ba}=await setup();try{const s=new Completion(db,alice),t=await s.createTicket(oa,{title:'Overdue outage',companyId:ca,boardId:ba});await s.ruleSave(oa,{name:'Overdue escalation',trigger:'Ticket overdue',priority:'',boardId:ba,status:'',enabled:true,actions:{status:'Escalated',note:'Review missed deadline'}});await s.ruleSave(oa,{name:'No recursion',trigger:'Ticket updated',priority:'',boardId:'',status:'',enabled:true,actions:{note:'SHOULD_NOT_RUN'}});await s.stmt("UPDATE tickets SET resolution_due='2020-01-01T00:00:00.000Z' WHERE org_id=? AND id=?",oa,t.id).run();assert.equal((await s.runTimedRules(oa)).applied,1);assert.equal((await s.runTimedRules(oa)).applied,0);const updated=await s.ticket(oa,t.id);assert.equal(updated.status,'Escalated');assert.equal(updated.notes.length,1);assert.equal(updated.notes[0].body,'Review missed deadline');}finally{db.close()}});
test('ticket briefs and resolved-history matching never cross organization boundaries',async()=>{const {db,oa,ob,ca,cb,ba,bb}=await setup();try{const s=new Completion(db,alice),other=new Completion(db,bob);const foreign=await other.createTicket(ob,{title:'Firewall foreign secret',companyId:cb,boardId:bb});await other.updateTicket(ob,String(foreign.id),{status:'Resolved',version:1});const first=await s.createTicket(oa,{title:'Firewall VPN failure',companyId:ca,boardId:ba});await s.updateTicket(oa,String(first.id),{status:'Resolved',version:1});const t=await s.createTicket(oa,{title:'Firewall connection',companyId:ca,boardId:ba});const brief=await s.assistance(oa,t.id);assert.equal(brief.similar.length,1);assert.equal(brief.similar[0].title,'Firewall VPN failure');assert.ok(!JSON.stringify(brief).includes('foreign secret'));}finally{db.close()}});
test('AI is disabled without organization setup and returns review-only provider drafts',async()=>{const {db,oa,ob,ca,ba}=await setup();const originalFetch=globalThis.fetch;try{globalThis.__qpTestEnv.DB=db;globalThis.__qpTestHeaders=new Headers({'oai-authenticated-user-id':alice.id,'oai-authenticated-user-email':alice.email});const s=new Completion(db,alice),t=await s.createTicket(oa,{title:'Draft response',companyId:ca,boardId:ba});const ctx={params:Promise.resolve({path:[oa,'ai']})};let r=await http.workspace.GET(new Request('https://test/ai'),ctx);assert.equal((await r.json()).available,false);const req=()=>new Request('https://test/ai',{method:'POST',headers:{'Content-Type':'application/json','X-QueuePilot-Request':'1'},body:JSON.stringify({kind:'rewrite',id:String(t.id),text:'We are checking the switch.'})});r=await http.workspace.POST(req(),ctx);assert.equal(r.status,503);Object.assign(globalThis.__qpTestEnv,{QUEUEPILOT_OPENAI_KEY:'dummy-test-key',QUEUEPILOT_AI_MODEL:'test-model',QUEUEPILOT_AI_ORGANIZATIONS:oa});let calls=0;globalThis.fetch=async(url,opts)=>{calls++;assert.equal(url,'https://api.openai.com/v1/responses');const b=JSON.parse(opts.body);assert.equal(b.store,false);assert.equal(b.input,JSON.stringify({draft:'We are checking the switch.'}));return Response.json({output:[{content:[{type:'output_text',text:'We are reviewing the switch and will share our findings.'}]}]})};r=await http.workspace.POST(req(),ctx);const draft=await r.json();assert.equal(r.status,200);assert.equal(draft.reviewRequired,true);assert.equal(calls,1);assert.equal((await s.messages(oa,t.id)).messages.length,0);r=await http.workspace.POST(req(),ctx);assert.equal(r.status,429);assert.equal(calls,1);}finally{globalThis.fetch=originalFetch;for(const k of ['DB','QUEUEPILOT_OPENAI_KEY','QUEUEPILOT_AI_MODEL','QUEUEPILOT_AI_ORGANIZATIONS'])delete globalThis.__qpTestEnv[k];globalThis.__qpTestHeaders=new Headers();db.close()}});
test('follow-up automation creates one open ticket with fresh SLA and no creation-rule recursion',async()=>{const {db,oa,ca,ba}=await setup();try{const s=new Completion(db,alice);await s.boardSettingsSave(oa,ba,{defaultMemberId:null,email:'',labels:{Critical:'Critical',High:'High',Normal:'Normal',Low:'Low'},targets:{Normal:{response:15,resolution:60}},version:0});await s.ruleSave(oa,{name:'Follow-up on creation',trigger:'Ticket created',priority:'',boardId:'',status:'',enabled:true,actions:{followupTitle:'Validate original request'}});const t=await s.createTicket(oa,{title:'New firewall',companyId:ca,boardId:ba});let page=await s.listTickets(oa,new URL('https://test/?view=all'));assert.equal(page.total,2);const follow=page.tickets.find(t=>t.title==='Validate original request');assert.equal(follow.closed,0);assert.equal(Date.parse(follow.resolutionDue)-Date.parse(follow.created),3600000);await s.ruleSave(oa,{name:'Closure check',trigger:'Ticket closed',priority:'',boardId:'',status:'',enabled:true,actions:{followupTitle:'Confirm acceptance'}});await s.updateTicket(oa,String(t.id),{status:'Closed',version:1});page=await s.listTickets(oa,new URL('https://test/?view=all'));assert.equal(page.total,3);assert.equal(page.tickets.find(t=>t.title==='Confirm acceptance').status,'New');await assert.rejects(s.updateTicket(oa,String(t.id),{status:'Closed',version:1}),failStatus(409));assert.equal((await s.listTickets(oa,new URL('https://test/?view=all'))).total,3);}finally{db.close()}});

test('ticket search handles formatted IDs, unordered words, contacts and combined filters without leaking tenants',async()=>{
 const {db,a,b,oa,ob,ca,cb,ba,bb}=await setup();try{
 const contact=(await a.directory(oa,'contacts',{name:'Jordan Reed',companyId:ca,email:'jordan@example.com'})).id;
 const t=await a.createTicket(oa,{title:'Wireless access point failure',description:'North campus',companyId:ca,contactId:contact,boardId:ba,priority:'High'});
 await b.createTicket(ob,{title:'Wireless access point failure',companyId:cb,boardId:bb});
 const list=p=>a.listTickets(oa,new URL('https://test/?'+new URLSearchParams({view:'all',...p})));
 for(const q of ['#'+t.id,'QP-'+t.id,'QV-'+t.id,'failure wireless','Jordan','jordan@example.com','North wireless'])assert.deepEqual((await list({q})).tickets.map(x=>x.id),[t.id],q);
 assert.equal((await list({q:'wireless',board:ba,company:ca,priority:'High'})).total,1);
 assert.equal((await list({q:'wireless',priority:'Low'})).total,0);
 assert.equal((await list({q:'wireless',company:cb})).total,0);
 assert.equal((await list({q:'wireless nonexistent'})).total,0);
 }finally{db.close()}
});

test('new service boards accept tickets with their own initial status and board filter',async()=>{
 const {db,a,oa,ca,ba}=await setup();try{
 const board=await a.directory(oa,'boards',{name:'Escalations',description:'Specialist queue',statuses:[{name:'Queued',closed:false},{name:'Done',closed:true}]});
 const ticket=await a.createTicket(oa,{title:'Specialist request',companyId:ca,boardId:board.id});
 assert.equal(ticket.boardId,board.id);assert.equal(ticket.status,'Queued');
 assert.deepEqual((await a.listTickets(oa,new URL('https://test/?view=all&board='+board.id))).tickets.map(t=>t.id),[ticket.id]);
 assert.equal((await a.listTickets(oa,new URL('https://test/?view=all&board='+ba))).total,0);
 }finally{db.close()}
});

test('exact status filters include custom and closed states while respecting board scope',async()=>{
 const {db,a,oa,ca,ba}=await setup();try{
 const board=await a.directory(oa,'boards',{name:'Approval',statuses:[{name:'Awaiting approval',closed:false},{name:'Finished',closed:true}]});
 const t=await a.createTicket(oa,{title:'Approval request',companyId:ca,boardId:board.id});
 const list=(status,boardId=board.id)=>a.listTickets(oa,new URL('https://test/?'+new URLSearchParams({view:'all',status,board:boardId})));
 assert.equal((await list('Awaiting approval')).total,1);
 assert.equal((await list('Awaiting')).total,0);
 assert.equal((await list('Awaiting approval',ba)).total,0);
 await a.updateTicket(oa,String(t.id),{status:'Finished',version:1});
 assert.equal((await list('Finished')).total,1);
 assert.equal((await list('Awaiting approval')).total,0);
 assert.equal((await list("' OR 1=1 --")).total,0);
 }finally{db.close()}
});
