import {PolicyPage} from '@/components/marketing/policy-page';
export const metadata={title:'Acceptable use | Quevian'};
export default function Page(){return <PolicyPage title="Acceptable use" summary="Use Quevian to coordinate legitimate service work. Respect the people and systems connected to it." sections={[
 {id:'lawful-use',title:'1. Respect rights and the law',body:<p>Do not use Quevian for unlawful activity, fraud, impersonation, threats, harassment, exploitation, or material that infringes privacy, intellectual-property, or other rights. Upload and send only information you have authority to process. Do not use the service for unsolicited bulk messages or misleading communications.</p>},
 {id:'systems',title:'2. Protect accounts and systems',body:<p>Do not upload malware, steal credentials, probe another workspace, bypass permissions or quotas, exploit vulnerabilities, disrupt availability, or try to access records you are not authorized to see. Security testing requires advance written permission for the scope of the test. Access granted to one organization does not grant access to another.</p>},
 {id:'data',title:'3. Minimize sensitive information',body:<p>Do not put passwords, private keys, full payment-card information, or unnecessary personal information in the service. Do not submit regulated or specially protected records unless the necessary written arrangements and safeguards have been confirmed. Quevian is not an emergency, medical, or life-critical service.</p>},
 {id:'automation',title:'4. Review messages and automation',body:<p>Use integrations, rules, and AI only for purposes you are authorized to carry out. Check recipients and customer visibility before sending. Review AI drafts for accuracy, confidential information, and suitability. Do not use automated requests to evade controls or overload the service.</p>},
 {id:'reporting',title:'5. Report a concern',body:<p>Report abuse, a security issue, an accessibility problem, or an intellectual-property concern to support@quevian.com. Provide a location or record reference, a description, and contact details for follow-up. For a rights complaint, explain the rights involved and your authority to report. Do not send passwords, exploit code containing secrets, or unnecessary copies of customer records. Acknowledging a report does not guarantee a particular outcome or response time.</p>},
 {id:'enforcement',title:'6. How concerns are handled',body:<p>We may investigate and proportionately restrict content or access to address a violation, security threat, or legal requirement under the <a href="/terms">Terms & conditions</a>. Contact support to explain the circumstances or request review of a restriction. These rules do not waive your legal rights.</p>},
 ]}/>}
