import {PolicyPage} from '@/components/marketing/policy-page';
export const metadata={title:'Privacy policy | Quevian',description:'What Quevian collects, why it is used, service providers, retention, and privacy requests.'};
export default function Page(){return <PolicyPage title="Privacy policy" summary="How information is used when you visit Quevian, sign in, or work with a team’s service records." sections={[
 {id:'scope',title:'1. Who handles your information',body:<><p>Quevian’s service operator handles account administration, security, support, and service operations. Contact <a href="mailto:support@quevian.com">support@quevian.com</a> about this notice or to request the operator details your organization needs before using the service.</p><p>When an organization puts customer or staff information into a workspace, that organization decides why the information is collected and who can use it. Quevian processes those service records to provide the workspace. If your request concerns a service provider’s ticket or customer record, contact that provider first; you may also contact us for help identifying the appropriate contact. This notice does not replace a data-processing agreement required for your organization.</p></>},
 {id:'information',title:'2. Information we collect and its sources',body:<ul>
 <li><strong>Account information:</strong> name, email, sign-in identifiers, organization memberships, assigned permissions, and verification status from you, your sign-in provider, or an inviting organization.</li>
 <li><strong>Workspace content:</strong> companies, contacts, tickets, messages, internal notes, files, projects, assets, schedules, time entries, and related business records entered by staff, customers, imports, or connected email channels.</li>
 <li><strong>Activity and security information:</strong> audit history, timestamps, request and delivery status, authentication events, and technical information such as IP addresses processed by hosting and authentication services. The application uses request information to limit abuse and diagnose failures.</li>
 <li><strong>Billing and support:</strong> subscription and payment-provider references, seat quantities, billing status, and information you send to support. If checkout is enabled, card details are collected by Stripe rather than stored as full card numbers by Quevian.</li>
 <li><strong>Your choices:</strong> browser preferences, saved drafts, and records of the policy version and time you accept service terms. See <a href="/cookies">Cookies & browser storage</a>.</li>
 </ul>},
 {id:'purposes',title:'3. Why information is used',body:<><p>We use information to sign you in, provide authorized access, manage workspaces, deliver requested messages, operate optional integrations, administer authorized billing, respond to requests, prevent abuse, investigate errors, and maintain recovery copies.</p><p>Where a law requires a legal basis, processing depends on its purpose: providing a requested service or performing a contract; protecting and operating the service where a legitimate-interest basis is available; meeting a legal obligation; or consent where required. Workspace organizations are responsible for the basis for their own service records. Accepting terms is not blanket consent for unrelated uses of personal information.</p><p>You can choose not to provide optional information. Some account details and service records are necessary for the feature you request. Please minimize sensitive information and do not include passwords or secrets in tickets, notes, or support requests.</p></>},
 {id:'sharing',title:'4. Who can receive information',body:<><p>Workspace data is available to staff according to their permissions. Customer-portal access is limited by the organization’s company grants. A customer-visible message or file may also be sent by email; recipients can keep their own copies. Organization owners and authorized administrators manage access.</p><p>Service providers process information for these functions:</p><div className="qv-policy-table"><table><caption>Current service providers and their role</caption><thead><tr><th>Provider</th><th>Purpose</th></tr></thead><tbody>
 <tr><td>OpenAI Sites and Cloudflare</td><td>Website hosting, application database, files, and recovery storage.</td></tr>
 <tr><td>Supabase</td><td>Email-account authentication and background job scheduling.</td></tr>
 <tr><td>OpenAI / ChatGPT</td><td>ChatGPT sign-in when selected, and optional AI drafting when enabled and requested.</td></tr>
 <tr><td>Resend</td><td>Transactional email, invitations, and connected ticket-email delivery and receipt.</td></tr>
 <tr><td>Stripe</td><td>Checkout and subscription billing when enabled.</td></tr>
 </tbody></table></div><p>We may disclose information where reasonably necessary to comply with law, respond to lawful requests, protect rights and security, or handle a business transfer subject to applicable privacy obligations. We do not operate advertising trackers in this application or sell workspace content through it. We do not use the application to share personal information for cross-context behavioral advertising.</p></>},
 {id:'ai',title:'5. Optional AI assistance',body:<><p>AI assistance is available only where enabled for a workspace. When an authorized user requests it, relevant prompt and record context is sent to OpenAI to create the draft. Depending on the selected task, this can include ticket text, internal notes, company history, or project information. Customer-update drafts use a restricted source; review every draft before sending.</p><p>The application requests that generated responses not be stored as response objects by the AI API. That setting is not a promise of zero provider retention. Do not send information to an AI feature unless you are authorized to have it processed that way. Asking for a draft does not itself send an email or apply a proposed change.</p></>},
 {id:'retention',title:'6. Retention, exports, and deletion',body:<><p>Business records remain in the workspace until an authorized removal or reviewed deletion is carried out. Closing a ticket, removing access, signing out, or canceling a subscription does not automatically erase those records. Owners can export business records in Settings → Data and submit a workspace-deletion request there. A deletion request is reviewed; submitting it does not immediately delete data or cancel billing.</p><p>Retention depends on the purpose of the record, the organization’s instructions, support and security needs, disputes, and applicable legal obligations. Recovery copies are kept separately from live data. An automatic backup-expiry period is not currently configured, so deletion from the live workspace does not by itself remove backup copies. Contact us before uploading data if you require a fixed deletion deadline or retention schedule.</p><p>When handling a valid request, we assess the live records, retained recovery copies, provider-held information, and any legal exception, and explain applicable limits. Third-party email recipients and your organization may hold separate copies under their own policies.</p></>},
 {id:'requests',title:'7. Your choices and privacy requests',body:<><p>Depending on applicable law, you may have rights to access, correct, delete, or obtain a copy of personal information; object to or restrict processing; withdraw consent for processing based on consent; or complain to a privacy regulator. California residents may also have rights concerning sale, advertising-related sharing, and use of sensitive information where the CCPA applies. We do not penalize people for exercising applicable privacy rights.</p><p>Email support@quevian.com with the type of request, your account email, and the relevant workspace. An authorized agent may contact us; we may need evidence of authority and proportionate identity verification. Please do not send identity documents unless we specifically arrange a secure verification process. If a request is refused, you can ask for the reason and an appeal or further review where available under applicable law.</p><p>Account holders can change information through available account and workspace controls. Workspace owners can access export, deletion-request, and billing controls from the terms-review screen without accepting updated terms. Anyone may contact support without signing in.</p></>},
 {id:'security',title:'8. Security and processing locations',body:<><p>The service uses authenticated access, organization and customer access restrictions, encrypted connections, and operational recovery checks. No online service can guarantee complete security. Report suspected exposure to support@quevian.com with a brief description; do not include a copy of another person’s data or exploit an issue further.</p><p>Our providers may process information outside your country. Quevian does not currently promise a particular data-residency region. If you require local hosting, a specific transfer mechanism, or a data-processing agreement, contact us before submitting information so those requirements can be assessed. This notice is not a claim of privacy-framework certification or universal regulatory compliance.</p></>},
 {id:'children',title:'9. Children',body:<p>Quevian is intended for business use by adults aged 18 or over, not for children. Do not create an account for a child or knowingly submit children’s personal information. If you believe a child has provided information, contact support so we can investigate and address it.</p>},
 {id:'updates',title:'10. Changes to this notice',body:<p>The effective date identifies this notice. We will update it when practices change and provide additional notice or seek consent where required. A new notice does not remove rights relating to information already collected. Provider and retention changes require review before new commitments are made.</p>},
 ]}/>}
