export const boards = ['Help Desk', 'Network Engineering', 'Security', 'On-Site Services'];
export const engineers = ['Unassigned', 'Alex Morgan', 'Jordan Lee', 'Taylor Brooks', 'Sam Rivera', 'Casey Parker', 'Drew Collins', 'Jamie Reed', 'Morgan Ellis'];
export const statuses = ['New', 'Triage', 'In Progress', 'Waiting on Customer', 'Waiting on Vendor', 'Escalated', 'Resolved', 'Closed'];
export const priorities = ['Critical', 'High', 'Normal', 'Low'];
export const companies = ['Northstar Schools', 'Summit Health', 'Westbridge Manufacturing', 'Oakwood Partners', 'Pinecrest County', 'Harbor Financial', 'Cedar Valley Academy', 'Meridian Logistics', 'Lakeside Dental', 'Atlas Architecture'];
export type Note = {id:string; body:string; at:string};
export type Ticket = {id:number; title:string; company:string; board:string; status:string; priority:string; assignee:string; description:string; created:string; updated:string; notes:Note[]; activity:{body:string; at:string}[]};
const titles = ['Wireless access points offline', 'Firewall VPN connection failing', 'New employee laptop setup', 'Core switch replacement', 'Microsoft 365 account locked', 'Camera system connectivity issue', 'Server storage capacity warning', 'Shared printer unavailable', 'Intermittent network connection', 'Email delivery delayed', 'Endpoint security alert', 'Conference room display offline', 'Backup job failed overnight', 'New user access request'];
export function seedTickets():Ticket[] {const seedAt=Date.now();return Array.from({length:54},(_,i)=>({id:1048-i,title:titles[i%titles.length],company:companies[i%companies.length],board:boards[i%4],status:statuses[i%8],priority:priorities[i%4],assignee:i%5===0?'Unassigned':engineers[1+i%8],description:`${titles[i%titles.length]} reported by ${companies[i%companies.length]}. Please investigate the affected service, confirm the impact with the customer, and document the next steps.`,created:new Date(seedAt-i*3600000).toISOString(),updated:new Date(seedAt-i*1800000).toISOString(),notes:[],activity:[{body:'Ticket created in '+boards[i%4],at:new Date(seedAt-i*3600000).toISOString()}]}));}
export const isOpen=(t:Ticket)=>!['Resolved','Closed'].includes(t.status);
export function filterTickets(tickets:Ticket[],query:string,board:string,priority:string,view:string){const q=query.toLowerCase().trim();return tickets.filter(t=>(board==='All boards'||t.board===board)&&(priority==='All priorities'||t.priority===priority)&&(view==='all'||view==='open'&&isOpen(t)||view==='mine'&&t.assignee==='Alex Morgan'&&isOpen(t)||view==='unassigned'&&t.assignee==='Unassigned'&&isOpen(t)||view==='critical'&&t.priority==='Critical'&&isOpen(t)||view==='waiting'&&t.status.startsWith('Waiting'))&&(!q||[t.id,t.title,t.company,t.assignee,t.description,...t.notes.map(n=>n.body)].join(' ').toLowerCase().includes(q)));}
