'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Picker} from './common';
import {api,message} from './common';
import {useRemote,Editor} from './module-common';
import {toast} from 'sonner';
import {can,type Workspace,type TicketRow} from '@/lib/domain';
export type ViewFilters={query:string;priority:string;sort:string;view:string;board:string;company:string;layout:string};
export function BoardControls({org,workspace,filters,apply}:{org:string;workspace:Workspace;filters:ViewFilters;apply:(f:ViewFilters)=>void}){const {data,reload}=useRemote<{records:(ViewFilters&{id:string;name:string})[]}>('/api/workspace/'+org+'/config/saved-view'),[save,setSave]=useState(false);return <div className="section-bar"><div className="heading-actions"><Picker label="Ticket layout" value={filters.layout} options={[{value:'table',label:'Table'},{value:'compact',label:'Compact'},{value:'kanban',label:'Kanban'}]} onChange={layout=>apply({...filters,layout})}/><Picker label="Saved views" value="none" options={[{value:'none',label:'Saved views'},...(data?.records??[]).map(v=>({value:v.id,label:v.name}))]} onChange={id=>{const v=data?.records.find(v=>v.id===id);if(v)apply(v)}}/>{can(workspace.organization,'tickets:write')&&<Button size="sm" variant="outline" onClick={()=>setSave(true)}>Save view</Button>}</div>{filters.layout==='kanban'&&<small>Cards reflect this page’s filtered tickets.</small>}{save&&<Editor org={org} title="Save shared view" description="This filter and layout will be available to the organization." initial={{name:''}} fields={[{key:'name',label:'View name',required:true}]} close={()=>setSave(false)} save={async v=>{await api('/api/workspace/'+org+'/config/saved-view','POST',{name:v.name,...filters});reload();toast.success('View saved')}}/>}</div>}
export function Kanban({org,workspace,tickets,select,reload}:{org:string;workspace:Workspace;tickets:TicketRow[];select:(n:number)=>void;reload:()=>void}){const [drag,setDrag]=useState<TicketRow|null>(null),[busy,setBusy]=useState(false);const states=[...new Set(tickets.map(t=>t.status))];for(const b of workspace.boards)for(const s of b.statuses)if(!states.includes(s.name))states.push(s.name);return <div className="qp-kanban">{states.map(status=><section key={status} onDragOver={e=>{if(drag&&!busy)e.preventDefault()}} onDrop={async e=>{e.preventDefault();if(!drag||busy||drag.status===status)return;setBusy(true);try{await api('/api/workspace/'+org+'/tickets/'+drag.id,'PATCH',{status,version:drag.version});reload();toast.success('Status updated')}catch(e){toast.error(message(e))}finally{setBusy(false);setDrag(null)}}}><h3>{status} <small>{tickets.filter(t=>t.status===status).length}</small></h3>{tickets.filter(t=>t.status===status).map(t=><article key={t.id} draggable={!busy&&can(workspace.organization,'tickets:write')} onDragStart={e=>{e.dataTransfer.setData('text/plain',String(t.id));setDrag(t)}} onDragEnd={()=>setDrag(null)}><small>#{t.id} · {t.priority}</small><button onClick={()=>select(t.id)}>{t.title}</button><p>{t.company}</p><small>{t.assignee}</small></article>)}</section>)}</div>}
