'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {api,Picker,message,Loading,ErrorState} from './common';
import {useRemote,options} from './module-common';
import {can,type Workspace} from '@/lib/domain';
import {toast} from 'sonner';
type Settings={sendingConfigured:boolean;receivingConfigured:boolean;domain:string;routes:{address:string;companyId:string;boardId:string;enabled:number}[];deliveries:{id:string;ticketId:number;recipient:string;status:string;error:string;updated:string}[]};
export function EmailSettings({org,workspace}:{org:string;workspace:Workspace}){return can(workspace.organization,'team:write')?<EmailAdmin org={org} workspace={workspace}/>:<p className="muted">An administrator can configure support inboxes here.</p>}
function EmailAdmin({org,workspace}:{org:string;workspace:Workspace}){const url='/api/workspace/'+org+'/mail',{data,error,reload}=useRemote<Settings>(url),[companyId,setCompany]=useState(workspace.companies[0]?.id??''),[boardId,setBoard]=useState(workspace.boards[0]?.id??''),[busy,setBusy]=useState(false);return <section className="settings-panel"><h2>Support email</h2>{error?<ErrorState error={error} retry={reload}/>:!data?<Loading/>:<><p>Sending: {data.sendingConfigured?'Configured':'Not configured'} · Receiving and delivery events: {data.receivingConfigured?'Configured — verify with a live test':'Setup required'}</p><p className="muted">Each inbox routes messages to one company and service board. Forward your support mailbox to its generated address. Incoming mail does not grant portal access. Email attachments currently remain in Resend.</p>{!data.receivingConfigured&&<p className="form-error">The site operator must configure a Resend receiving domain and webhook signing secret before enabling support email.</p>}<form className="qp-form" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await api(url,'POST',{companyId,boardId});await reload();toast.success('Support inbox created')}catch(e){toast.error(message(e))}finally{setBusy(false)}}}><Picker label="Customer company" value={companyId} options={options(workspace.companies)} onChange={setCompany}/><Picker label="Service board" value={boardId} options={options(workspace.boards)} onChange={setBoard}/><Button disabled={busy||!companyId||!boardId||!data.receivingConfigured}>Create support inbox</Button></form>{data.routes.map(r=><div className="note" key={r.address}><strong>{workspace.companies.find(c=>c.id===r.companyId)?.name} · {workspace.boards.find(b=>b.id===r.boardId)?.name}</strong><p style={{overflowWrap:'anywhere'}}>{r.address}</p><Button variant="outline" disabled={busy} onClick={async()=>{setBusy(true);try{await api(url+'/toggle','POST',{address:r.address,enabled:!r.enabled});await reload()}catch(e){toast.error(message(e))}finally{setBusy(false)}}}>{r.enabled?'Pause new tickets':'Enable new tickets'}</Button></div>)}<h3>Recent email deliveries</h3>{!data.deliveries.length&&<p className="muted">No ticket emails have been sent yet.</p>}{data.deliveries.map(d=><div className="note" key={d.id}><strong>Ticket #{d.ticketId} · {d.status}</strong><p>{d.recipient}</p>{d.error&&<p className="form-error">{d.error}</p>}</div>)}<Button variant="outline" onClick={()=>reload()}>Refresh email status</Button></>}</section>}
