'use client';
import {useRef,useState} from 'react';
import {Paperclip,Download,Upload} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {toast} from 'sonner';
import {Picker,Loading,ErrorState,message,stamp} from './common';
import {useRemote} from './module-common';
import type {Attachment} from '@/lib/domain';
export function Files({url,write,customer=false}:{url:string;write:boolean;customer?:boolean}){const {data,error,reload}=useRemote<{files:Attachment[]}>(url),[file,setFile]=useState<File|null>(null),[visibility,setVisibility]=useState('Internal'),[busy,setBusy]=useState(false),input=useRef<HTMLInputElement>(null);return <div className="file-panel">{error?<ErrorState error={error} retry={reload}/>:!data?<Loading/>:<div className="file-list">{data.files.map(f=><div key={f.id}><Paperclip size={17}/><div><strong>{f.name}</strong><small>{(f.size/1024).toFixed(1)} KB · {stamp(f.at)}{!customer?' · '+f.visibility:''}</small></div><Button variant="ghost" size="icon" asChild><a href={url+'/'+f.id} aria-label={'Download '+f.name}><Download size={16}/></a></Button></div>)}{!data.files.length&&<p className="muted">No files attached.</p>}</div>}{write&&<form className="qp-form" onSubmit={async e=>{e.preventDefault();if(!file)return;if(file.size>5*1024*1024){toast.error('Choose a file up to 5 MB.');return;}setBusy(true);try{const form=new FormData();form.set('file',file);form.set('visibility',customer?'Customer':visibility);const r=await fetch(url,{method:'POST',headers:{'X-Quevian-Request':'1'},body:form});if(!r.ok){const data=await r.json() as {error?:string};throw new Error(data.error??'Upload failed.')}setFile(null);if(input.current)input.current.value='';reload();toast.success('File uploaded')}catch(e){toast.error(message(e))}finally{setBusy(false)}}}><label htmlFor="attachment-file">Attach file (up to 5 MB)</label><Input id="attachment-file" ref={input} type="file" onChange={e=>setFile(e.target.files?.[0]??null)}/>{!customer&&<Picker label="File visibility" value={visibility} options={['Internal','Customer']} onChange={setVisibility}/>}<p className="muted">{customer?'Uploaded files are shared with your service team.':visibility==='Internal'?'Only organization staff can download this file.':'Authorized customers can download this file from the portal.'}</p><Button disabled={!file||busy}><Upload size={14}/>{busy?'Uploading…':'Upload file'}</Button></form>}</div>}
