'use client';
import {useCallback,useEffect,useState} from 'react';
import {ChevronsUpDown,Check,RefreshCw} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Popover,PopoverContent,PopoverTrigger} from '@/components/ui/popover';
import {Command,CommandInput,CommandList,CommandItem,CommandEmpty} from '@/components/ui/command';
import {Checkbox} from '@/components/ui/checkbox';
import {Button} from '@/components/ui/button';
import {api,message,Field,Picker} from './common';
import type {TicketPage} from '@/lib/domain';
export function useRemote<T>(url:string){const [data,setData]=useState<T|null>(null),[error,setError]=useState(''),[revision,setRevision]=useState(0),[loading,setLoading]=useState(true);const reload=useCallback(()=>setRevision(n=>n+1),[]);useEffect(()=>{const c=new AbortController();setLoading(true);api<T>(url,'GET',undefined,c.signal).then(d=>{setData(d);setError('')}).catch(e=>{if(!c.signal.aborted)setError(message(e))}).finally(()=>{if(!c.signal.aborted)setLoading(false)});return()=>c.abort()},[url,revision]);return {data,error,loading,reload};}
export type FormValues=Record<string,string|number|boolean|null>;
export type FormField={key:string;label:string;type?:'text'|'textarea'|'number'|'date'|'datetime-local'|'email'|'checkbox'|'select'|'ticket';options?:{value:string;label:string}[];required?:boolean;max?:number;nullable?:boolean};
export function Editor({title,description,initial,fields,org,save,close,children,readOnly=false}:{title:string;description?:string;initial:FormValues;fields:FormField[];org:string;save:(values:FormValues)=>Promise<void>;close:()=>void;children?:React.ReactNode;readOnly?:boolean}){const [values,setValues]=useState(initial),[error,setError]=useState(''),[busy,setBusy]=useState(false);return <Dialog open onOpenChange={o=>{if(!o&&!busy)close()}}><DialogContent className="directory-dialog"><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>{description??'Save these details to your organization.'}</DialogDescription></DialogHeader><form className="qp-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await save(values);close()}catch(e){setError(message(e))}finally{setBusy(false)}}}><fieldset disabled={busy||readOnly}>{fields.map(f=>f.type==='checkbox'?<label className="checkbox-label" key={f.key}><Checkbox checked={Boolean(values[f.key])} onCheckedChange={v=>setValues({...values,[f.key]:v===true})}/>{f.label}</label>:f.type==='select'?<div className="form-field" key={f.key}><label>{f.label}</label><Picker label={f.label} value={String(values[f.key]??'none')} options={f.options??[]} onChange={v=>setValues({...values,[f.key]:v==='none'&&f.nullable?null:v})}/></div>:f.type==='ticket'?<div className="form-field" key={f.key}><label>{f.label}</label><TicketPicker org={org} value={values[f.key]===null?null:Number(values[f.key])} onChange={v=>setValues({...values,[f.key]:v})} optional={!f.required}/></div>:<Field key={f.key} name={'field-'+f.key} label={f.label} value={String(values[f.key]??'')} onChange={v=>setValues({...values,[f.key]:f.type==='number'?Number(v):v})} required={f.required} type={f.type==='textarea'?'text':f.type??'text'} multiline={f.type==='textarea'} maxLength={f.max??(f.type==='textarea'?10000:180)}/>)}{children}</fieldset>{error&&<p className="form-error" role="alert">{error}</p>}<div className="dialog-actions"><Button type="button" variant="outline" disabled={busy} onClick={close}>Cancel</Button>{!readOnly&&<Button disabled={busy}>{busy?'Saving…':'Save'}</Button>}</div></form></DialogContent></Dialog>}
export function TicketPicker({org,value,onChange,optional=false}:{org:string;value:number|null;onChange:(id:number|null)=>void;optional?:boolean}){const [open,setOpen]=useState(false),[query,setQuery]=useState(''),[rows,setRows]=useState<TicketPage['tickets']>([]),[error,setError]=useState('');useEffect(()=>{if(!open)return;const c=new AbortController(),timer=setTimeout(()=>api<TicketPage>('/api/workspace/'+org+'/tickets?view=all&q='+encodeURIComponent(query),'GET',undefined,c.signal).then(d=>{setRows(d.tickets);setError('')}).catch(e=>{if(!c.signal.aborted)setError(message(e))}),180);return()=>{clearTimeout(timer);c.abort()}},[org,open,query]);return <Popover open={open} onOpenChange={setOpen}><PopoverTrigger asChild><Button variant="outline" role="combobox" aria-expanded={open} className="ticket-picker">{value?'Ticket #'+value:optional?'No ticket':'Choose a ticket'}<ChevronsUpDown size={14}/></Button></PopoverTrigger><PopoverContent className="p-0 w-80"><Command shouldFilter={false}><CommandInput placeholder="Search ticket number or title…" value={query} onValueChange={setQuery}/><CommandList><CommandEmpty>{error||'No matching tickets.'}</CommandEmpty>{optional&&<CommandItem value="none" onSelect={()=>{onChange(null);setOpen(false)}}>No ticket</CommandItem>}{rows.map(t=><CommandItem key={t.id} value={String(t.id)} onSelect={()=>{onChange(t.id);setOpen(false)}}><span>#{t.id} · {t.title}<small className="block text-muted-foreground">{t.company}</small></span>{value===t.id&&<Check size={14}/>}</CommandItem>)}</CommandList></Command></PopoverContent></Popover>}
export function ModuleHeading({eyebrow,title,description,children}:{eyebrow:string;title:string;description:string;children?:React.ReactNode;readOnly?:boolean}){return <section className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}<span className="title-dot">.</span></h1><p>{description}</p></div><div className="heading-actions">{children}</div></section>}
export const localInput=(s:string)=>{const d=new Date(s);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)};
export const today=()=>localInput(new Date().toISOString()).slice(0,10);
export const options=(rows:{id:string;name:string}[],none?:string)=>[...(none?[{value:'none',label:none}]:[]),...rows.map(r=>({value:r.id,label:r.name}))];
export function csvFile(filename:string,rows:unknown[][]){const escape=(v:unknown)=>{let s=String(v??'');if(/^[\s]*[=+@-]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"'};const blob=new Blob(['\ufeff'+rows.map(r=>r.map(escape).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
