'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem} from '@/components/ui/dropdown-menu';
import {TicketForm} from './tickets';
import {Editor,options,localInput,type FormValues,type FormField} from './module-common';
import {api} from './common';
import {can,type Workspace} from '@/lib/domain';
import {toast} from 'sonner';
export function QuickCreate({org,workspace,refresh,openTicket}:{org:string;workspace:Workspace;refresh:()=>Promise<void>;openTicket:(id:number)=>void}){const [kind,setKind]=useState('');const definitions:Record<string,{initial:FormValues;fields:FormField[]}>={companies:{initial:{name:'',email:'',phone:'',address:'',notes:''},fields:[{key:'name',label:'Company name',required:true},{key:'email',label:'Email',type:'email'},{key:'phone',label:'Phone'},{key:'address',label:'Address'}]},contacts:{initial:{name:'',companyId:workspace.companies[0]?.id??'',email:'',phone:'',title:''},fields:[{key:'name',label:'Name',required:true},{key:'companyId',label:'Company',type:'select',options:options(workspace.companies)},{key:'email',label:'Email',type:'email'},{key:'phone',label:'Phone'},{key:'title',label:'Job title'}]},projects:{initial:{name:'',companyId:workspace.companies[0]?.id??'',description:'',ownerId:null,status:'Planning',due:'',estimatedHours:0,visible:false},fields:[{key:'name',label:'Project name',required:true},{key:'companyId',label:'Company',type:'select',options:options(workspace.companies)},{key:'description',label:'Description',type:'textarea'},{key:'due',label:'Target date',type:'date'}]},time:{initial:{ticketId:null,starts:localInput(new Date(Date.now()-3600000).toISOString()),ends:localInput(new Date().toISOString()),description:'',billable:true},fields:[{key:'ticketId',label:'Ticket',type:'ticket',required:true},{key:'starts',label:'Start',type:'datetime-local',required:true},{key:'ends',label:'End',type:'datetime-local',required:true},{key:'description',label:'Work performed',type:'textarea',required:true},{key:'billable',label:'Billable',type:'checkbox'}]}};return <><DropdownMenu><DropdownMenuTrigger asChild><Button>+ Create</Button></DropdownMenuTrigger><DropdownMenuContent>{[['tickets','Ticket','tickets:write'],['companies','Company','directory:write'],['contacts','Contact','directory:write'],['projects','Project','projects:write'],['time','Time entry','time:write']].filter(([, ,cap])=>can(workspace.organization,cap as 'tickets:write')).map(([value,label])=><DropdownMenuItem key={value} onSelect={()=>setKind(value)}>{label}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu>{kind==='tickets'?<TicketForm open org={org} workspace={workspace} close={()=>setKind('')} saved={t=>{setKind('');openTicket(t.id);refresh()}}/>:kind&&<Editor title={'Create '+kind} org={org} initial={definitions[kind].initial} fields={definitions[kind].fields} close={()=>setKind('')} save={async v=>{await api('/api/workspace/'+org+'/'+kind,'POST',kind==='time'?{...v,starts:new Date(String(v.starts)).toISOString(),ends:new Date(String(v.ends)).toISOString()}:v);await refresh();toast.success('Record created')}}/>}</>}
