'use client';
import {useState,useEffect} from 'react';
import QRCode from 'qrcode';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {useRemote} from './module-common';
import {api,message,Picker,ErrorState} from './common';
import {toast} from 'sonner';
import type {ProjectTask} from '@/lib/domain';
export function TaskDependencies({org,projectId,tasks,write}:{org:string;projectId:string;tasks:ProjectTask[];write:boolean}){const {data,error,reload}=useRemote<{dependencies:{taskId:string;dependencyId:string}[]}>('/api/workspace/'+org+'/dependencies/'+projectId),[task,setTask]=useState('none'),[dependency,setDependency]=useState('none');const update=async(taskId:string,dependencyId:string,remove=false)=>{try{await api('/api/workspace/'+org+'/dependencies','POST',{taskId,dependencyId,remove});reload();toast.success('Dependencies saved')}catch(e){toast.error(message(e))}};return <section className="qp-form mt-6"><h3>Task dependencies</h3>{error&&<ErrorState error={error} retry={reload}/>} {data?.dependencies.map(d=><div className="section-bar" key={d.taskId+d.dependencyId}><span>{tasks.find(t=>t.id===d.taskId)?.title} waits for {tasks.find(t=>t.id===d.dependencyId)?.title}</span>{write&&<Button variant="ghost" size="sm" onClick={()=>update(d.taskId,d.dependencyId,true)}>Remove</Button>}</div>)}{write&&<><Picker label="Dependent task" value={task} options={[{value:'none',label:'Task that must wait'},...tasks.map(t=>({value:t.id,label:t.title}))]} onChange={setTask}/><Picker label="Prerequisite task" value={dependency} options={[{value:'none',label:'Prerequisite task'},...tasks.filter(t=>t.id!==task).map(t=>({value:t.id,label:t.title}))]} onChange={setDependency}/><Button variant="outline" disabled={task==='none'||dependency==='none'||task===dependency} onClick={()=>update(task,dependency)}>Add dependency</Button></>}</section>}
export function AssetQR({org,id,name}:{org:string;id:string;name:string}){const [open,setOpen]=useState(false),[src,setSrc]=useState(''),[error,setError]=useState('');useEffect(()=>{if(open){let active=true;const url=new URL('/app',window.location.origin);url.searchParams.set('org',org);url.searchParams.set('asset',id);QRCode.toDataURL(url.href,{width:320,margin:2,errorCorrectionLevel:'M'}).then(s=>{if(active)setSrc(s)}).catch(e=>{if(active)setError(message(e))});return()=>{active=false}}},[open,org,id]);return <><Button variant="ghost" size="sm" onClick={()=>setOpen(true)}>QR label</Button><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>{name}</DialogTitle><DialogDescription>Scan to open this asset in Quevian. Sign-in and organization access are required.</DialogDescription></DialogHeader>{error&&<p role="alert">{error}</p>}{src&&<><img className="mx-auto" width={320} height={320} src={src} alt={'QR code for '+name}/><a className="text-action" href={src} download={'quevian-asset-'+id+'.png'}>Download QR label</a></>}</DialogContent></Dialog></>}
