'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Textarea} from '@/components/ui/textarea';
import {toast} from 'sonner';
import {api,message,Picker,Loading,ErrorState,stamp} from './common';
import {useRemote,options} from './module-common';
import type {PublicMessage} from '@/lib/domain';
export function Conversation({org,id,write,changed}:{org:string;id:number;write:boolean;changed:()=>void}){const templates=useRemote<{records:{id:string;name:string;body:string}[]}>('/api/workspace/'+org+'/config/reply-template');const url='/api/workspace/'+org+'/tickets/'+id+'/messages',{data,error,reload}=useRemote<{messages:PublicMessage[]}>(url),[body,setBody]=useState(''),[busy,setBusy]=useState(false);return <>{error?<ErrorState error={error} retry={reload}/>:!data?<Loading/>:<div className="notes-list">{data.messages.map(m=><article className={'note public-note '+(m.kind==='Customer'?'customer-note':'')} key={m.id}><div><strong>{m.author} · {m.kind}</strong><small>{stamp(m.at)}</small></div><p>{m.body}</p></article>)}{!data.messages.length&&<p className="muted">No customer-facing replies yet.</p>}</div>}{write&&<form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await api(url,'POST',{body});setBody('');reload();changed();toast.success('Reply posted in the customer portal')}catch(e){toast.error(message(e))}finally{setBusy(false)}}}><Picker label="Insert reply template" value="none" options={[{value:"none",label:"Insert a reply template"},...(templates.data?.records??[]).map(r=>({value:r.id,label:r.name}))]} onChange={v=>{const t=templates.data?.records.find(r=>r.id===v);if(t)setBody(t.body)}}/><Textarea aria-label="Customer-facing reply" value={body} onChange={e=>setBody(e.target.value)} placeholder="Write an update for the customer…" maxLength={10000}/><div className="note-actions"><small>Visible to authorized customers in the portal. No email is sent.</small><Button disabled={!body.trim()||busy}>{busy?'Posting…':'Post reply'}</Button></div></form>}</>}
export function Related({org,id,write}:{org:string;id:number;write:boolean}){const url='/api/workspace/'+org+'/tickets/'+id+'/links',{data,error,reload}=useRemote<{links:{projectId:string|null;assetId:string|null}|null;projects:{id:string;name:string}[];assets:{id:string;name:string}[]}>(url),[busy,setBusy]=useState(false);const update=async(field:string,value:string)=>{setBusy(true);try{await api(url,'POST',{projectId:data?.links?.projectId??null,assetId:data?.links?.assetId??null,[field]:value==='none'?null:value});reload();toast.success('Related records saved')}catch(e){toast.error(message(e))}finally{setBusy(false)}};return error?<ErrorState error={error} retry={reload}/>:!data?<Loading/>:<div className="qp-form"><div className="form-field"><label>Project</label><Picker disabled={!write||busy} label="Related project" value={data.links?.projectId??'none'} options={options(data.projects,'No project')} onChange={v=>update('projectId',v)}/></div><div className="form-field"><label>Asset</label><Picker disabled={!write||busy} label="Related asset" value={data.links?.assetId??'none'} options={options(data.assets,'No asset')} onChange={v=>update('assetId',v)}/></div><p className="muted">Only projects and assets belonging to this ticket’s company are available.</p></div>}
