'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Textarea} from '@/components/ui/textarea';
import {toast} from 'sonner';
import {api,message,Picker,Loading,ErrorState,stamp} from './common';
import {useRemote,options} from './module-common';
import type {PublicMessage} from '@/lib/domain';
export function Conversation({org,id,write,changed}:{org:string;id:number;write:boolean;changed:()=>void}){
 const templates=useRemote<{records:{id:string;name:string;body:string}[]}>('/api/workspace/'+org+'/config/reply-template');
 const url='/api/workspace/'+org+'/tickets/'+id+'/messages',mailUrl='/api/workspace/'+org+'/tickets/'+id+'/email';
 const {data,error,reload}=useRemote<{messages:PublicMessage[]}>(url),mail=useRemote<{recipient:string;deliveries:{id:string;status:string;error:string;updated:string}[]}>(mailUrl);
 const [body,setBody]=useState(''),[busy,setBusy]=useState(false),[sendEmail,setSendEmail]=useState(false),[requestId,setRequestId]=useState(()=>crypto.randomUUID());
 return <>{error?<ErrorState error={error} retry={reload}/>:!data?<Loading/>:<div className="notes-list">{data.messages.map(m=><article className={'note public-note '+(m.kind==='Customer'?'customer-note':'')} key={m.id}><div><strong>{m.author} · {m.kind}</strong><small>{stamp(m.at)}</small></div><p>{m.body}</p></article>)}{!data.messages.length&&<p className="muted">No customer-facing replies yet.</p>}</div>}
 {mail.data?.deliveries.map(d=><div className="note" key={d.id}><strong>Email: {d.status}</strong><p>{d.error|| (d.status==='accepted'?'Accepted by Resend; delivery has not been confirmed.':d.status==='delivered'?'Delivered to the recipient’s mail server.':'')}</p>{write&&['retry','pending','sending'].includes(d.status)&&<Button variant="outline" disabled={busy} onClick={async()=>{setBusy(true);try{await api('/api/workspace/'+org+'/mail/retry','POST',{id:d.id});await mail.reload()}catch(e){toast.error(message(e))}finally{setBusy(false)}}}>Retry saved email</Button>}</div>)}
 {mail.error&&<p className="form-error">Email status: {mail.error}</p>}
 <Button variant="ghost" onClick={()=>mail.reload()}>Refresh delivery status</Button>
 {write&&<form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await api(sendEmail?mailUrl:url,'POST',sendEmail?{body,requestId}:{body});setBody('');setRequestId(crypto.randomUUID());reload();mail.reload();changed();toast.success(sendEmail?'Reply saved. Check its email delivery status below.':'Reply posted in the customer portal')}catch(e){toast.error(message(e))}finally{setBusy(false)}}}>
 <Picker label="Insert reply template" value="none" options={[{value:'none',label:'Insert a reply template'},...(templates.data?.records??[]).map(r=>({value:r.id,label:r.name}))]} onChange={v=>{const t=templates.data?.records.find(r=>r.id===v);if(t)setBody(t.body)}}/>
 <Textarea aria-label="Customer-facing reply" value={body} onChange={e=>setBody(e.target.value)} placeholder="Write an update for the customer…" maxLength={10000}/>
 <label className="checkbox-label"><input type="checkbox" checked={sendEmail} onChange={e=>setSendEmail(e.target.checked)}/>Also send by email{mail.data?.recipient?' to '+mail.data.recipient:''}</label>
 <div className="note-actions"><small>{sendEmail?'Sends this reply only. Internal notes and files are excluded.':'Visible in the customer portal only.'}</small><Button disabled={!body.trim()||busy}>{busy?'Saving…':sendEmail?'Send reply':'Post to portal'}</Button></div></form>}</>;
}
export function Related({org,id,write}:{org:string;id:number;write:boolean}){const url='/api/workspace/'+org+'/tickets/'+id+'/links',{data,error,reload}=useRemote<{links:{projectId:string|null;assetId:string|null}|null;projects:{id:string;name:string}[];assets:{id:string;name:string}[]}>(url),[busy,setBusy]=useState(false);const update=async(field:string,value:string)=>{setBusy(true);try{await api(url,'POST',{projectId:data?.links?.projectId??null,assetId:data?.links?.assetId??null,[field]:value==='none'?null:value});reload();toast.success('Related records saved')}catch(e){toast.error(message(e))}finally{setBusy(false)}};return error?<ErrorState error={error} retry={reload}/>:!data?<Loading/>:<div className="qp-form"><div className="form-field"><label>Project</label><Picker disabled={!write||busy} label="Related project" value={data.links?.projectId??'none'} options={options(data.projects,'No project')} onChange={v=>update('projectId',v)}/></div><div className="form-field"><label>Asset</label><Picker disabled={!write||busy} label="Related asset" value={data.links?.assetId??'none'} options={options(data.assets,'No asset')} onChange={v=>update('assetId',v)}/></div><p className="muted">Only projects and assets belonging to this ticket’s company are available.</p></div>}
