import {policyAcceptance} from '@/lib/server/legal';
import {env} from 'cloudflare:workers';
import {z} from 'zod';
import {body,respond} from '@/lib/server/http';
import {HttpError} from '@/lib/server/service';
import {authClient,verifiedUser,safeNext} from '@/lib/auth/server';
import {authConfig,authReady} from '@/lib/auth/config';
import {limitAuth} from '@/lib/auth/rate-limit';
export const dynamic='force-dynamic';
const email=z.string().trim().email().max(254).transform(x=>x.toLowerCase());
const password=z.string().min(12,'Use at least 12 characters.').max(128,'Use no more than 128 characters.');
export async function POST(request:Request,{params}:{params:Promise<{action:string}>}){return respond(async()=>{const {action}=await params;const p=await body(request,8192);if(!authReady())throw new HttpError(503,'Sign-in is temporarily unavailable. Please try again shortly.');if(!env.DB)throw new HttpError(503,'Shared storage is unavailable.');const client=await authClient();const origin=authConfig().site;const fail=(code?:string)=>{throw new HttpError(code==='over_request_rate_limit'||code==='over_email_send_rate_limit'?429:400,code==='email_not_confirmed'?'Verify your email before signing in.':action==='login'?'Unable to sign in. Check your email and password.':'Unable to complete this request. Please try again or request a new email.')};
if(['signup','login','forgot','resend','verify'].includes(action)){const address=email.parse(p.email);await limitAuth(env.DB,action,address,request.headers.get('cf-connecting-ip'));}
if(action==='signup'){const v=policyAcceptance.extend({email,password,name:z.string().trim().min(1).max(120),next:z.string().optional()}).strict().parse(p);const {error}=await client.auth.signUp({email:v.email,password:v.password,options:{data:{full_name:v.name},emailRedirectTo:origin+'/auth/confirm?next='+encodeURIComponent(safeNext(v.next))}});if(error)fail(error.code);return {message:'Check your inbox to verify your email. If you already have an account, sign in or reset your password.'}}
if(action==='login'){const v=z.object({email,password:z.string().min(1).max(128),next:z.string().optional()}).strict().parse(p);const {data,error}=await client.auth.signInWithPassword({email:v.email,password:v.password});if(error)fail(error.code);if(!data.user?.email_confirmed_at||data.user.is_anonymous){await client.auth.signOut();throw new HttpError(403,'Verify your email before signing in.')}return {next:safeNext(v.next)}}
if(action==='forgot'){const v=z.object({email}).strict().parse(p);const {error}=await client.auth.resetPasswordForEmail(v.email,{redirectTo:origin+'/auth/confirm?next=/reset-password'});if(error)fail(error.code);return {message:'If an account exists for that email, a password-reset email is on its way.'}}
if(action==='resend'){const v=z.object({email,next:z.string().optional()}).strict().parse(p);const {error}=await client.auth.resend({type:'signup',email:v.email,options:{emailRedirectTo:origin+'/auth/confirm?next='+encodeURIComponent(safeNext(v.next))}});if(error)fail(error.code);return {message:'If verification is needed, a new email is on its way.'}}
if(action==='verify'){const v=z.object({email,token:z.string().regex(/^\d{6,10}$/),type:z.enum(['signup','recovery']),next:z.string().optional()}).strict().parse(p);const {next,...otp}=v;const {error}=await client.auth.verifyOtp(otp);if(error)fail(error.code);return {next:v.type==='recovery'?'/reset-password':safeNext(v.next)}}
if(action==='confirm'){const v=z.object({token_hash:z.string().min(20).max(300),type:z.enum(['email','signup','recovery','invite']),next:z.string().optional()}).strict().parse(p);await limitAuth(env.DB,'confirm',v.token_hash,request.headers.get('cf-connecting-ip'));const {error}=await client.auth.verifyOtp({token_hash:v.token_hash,type:v.type});if(error)fail(error.code);return {next:v.type==='recovery'?'/reset-password':safeNext(v.next)}}
if(action==='reset'){const v=z.object({password}).strict().parse(p);if(!await verifiedUser())throw new HttpError(401,'Open a valid reset email before setting your password.');const {error}=await client.auth.updateUser({password:v.password});if(error)fail(error.code);await client.auth.signOut({scope:'global'});return {next:'/login',message:'Password updated. Sign in with your new password.'}}
if(action==='logout'){await client.auth.signOut({scope:'local'});return {next:'/login'}}
throw new HttpError(404,'Account action not found.')})}
