import {PolicyPage} from '@/components/marketing/policy-page';
export const metadata={title:'Billing & cancellation | Quevian'};
export default function Page(){return <PolicyPage title="Billing & cancellation" summary="Creating an account does not authorize a charge. Paid plans require a separate, explicit checkout." sections={[
 {id:'checkout',title:'1. Before you pay',body:<><p>Paid checkout may be unavailable while subscriptions are being prepared. When offered, checkout shows the subscription price, billing interval, staff-seat quantity, applicable taxes, and recurring total before you authorize payment. Customer-only portal accounts do not count as staff seats.</p><p>The authorized workspace owner must accept the applicable terms and recurring billing. A website price illustration is not a payment authorization or a promise of a free trial. Review your checkout and confirmation for the terms of your purchase.</p></>},
 {id:'renewal',title:'2. Renewals and seat changes',body:<p>A subscription renews at the interval you select until canceled. An annual plan is billed upfront for the year. Owner-authorized seat changes may create prorated charges or credits; the billing flow presents the change. Reductions cannot go below active staff and pending invitations. A price change for a future renewal requires advance notice as required by applicable law and an opportunity to cancel.</p>},
 {id:'cancel',title:'3. How to cancel',body:<><p>As the workspace owner, open Settings → Subscription → Manage billing to cancel future renewal. Unless the billing flow or a separate agreement states otherwise, cancellation takes effect at the end of the current paid period. Keep the cancellation confirmation and check the displayed end date.</p><p>If you cannot access billing, email support@quevian.com from your account address with your workspace name and a cancellation request. Do not send card details. You do not need to accept updated service terms to request cancellation; the terms-review screen provides access to billing controls for your existing workspace.</p><p>Signing out, deleting records, removing staff, or requesting workspace deletion is not a subscription cancellation.</p></>},
 {id:'refunds',title:'4. Refunds and billing errors',body:<p>Contact support@quevian.com about duplicate charges, incorrect charges, or a refund request. Include the workspace and invoice reference, if available, without payment-card details. This policy does not promise an automatic refund or override a refund, withdrawal, cancellation, or other remedy required by applicable law. Any additional refund entitlement must be stated in your checkout or separate agreement before purchase.</p>},
 {id:'data',title:'5. Data after cancellation',body:<p>Cancellation does not immediately erase workspace records or recovery copies. Export records you need and use Settings → Data or contact support for a deletion request. Deletion is reviewed separately from billing; see the <a href="/privacy">Privacy policy</a> for current retention limits.</p>},
 ]}/>}
